// Offline read-only Git/source extraction. No live capture, runtime write or output-quality selection.
import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import crypto from 'node:crypto';
export const DIR='research/cycle8/md07_unit_calibration/rb_prior_intent';
export const BASE='fd585891214db483112f52d4746106c606afeb43',ORIGINAL='1ecd4db3005fbce72fa88222476bcfafd312ca4c',ACCEPTED='98db3b323c928879d9ff7435d77a980744a66289',ROOT='43d2c7169534cb76cd13c72166b111d0d91d6c06';
export const SOURCE_COMMITS=[ROOT,'c44e59ef67e501d09ac9ec83d7b2c48b421089a1','8d72a03f857f07549c33bbe8ce0835da95159201'];
export const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
export const git=(...args)=>execFileSync('git',['-c','safe.directory='+process.cwd().replaceAll('\\','/'),...args],{encoding:'utf8',maxBuffer:32*1024*1024,windowsHide:true}).replace(/\r\n/g,'\n');
export const blob=(commit,p)=>git('show',commit+':'+p);
const model='model/live_profiles.js',name='priorRbOrthogonalComposite';
const functions=['priorQbPassEpa','priorReceiverWrteEpa','ridgeOrthogonalSlope','partialResidual','priorReceiverResidual',name,'continuousPercentileValue','priorPercentile'];
function body(s,name){const lines=s.split('\n'),start=lines.findIndex(l=>l.includes('function '+name+'('));assert(start>=0,name);let end=start+1;while(end<lines.length&&!/^  }/.test(lines[end]))end++;return {startLine:start+1,endLine:end+1,text:lines.slice(start,end+1).join('\n')};}
export function classify(line){
 if(line.includes('function '+name+'('))return 'DECLARATION';
 if(line.includes('window.FORCE_LIVE_PROFILE='))return 'EXPORT';
 if(line.includes("includes('"+name+"')"))return 'CONTRACT STRING';
 if(/\.map\((?:[A-Za-z]+\.)?priorRbOrthogonalComposite\)/.test(line))return 'DIRECT ARRAY CALLBACK';
 if(/priorRbOrthogonalComposite\(/.test(line))return 'EXPLICIT CALL';
 throw new Error('Unclassified helper occurrence: '+line);
}
function argumentsOf(line){const token=line.indexOf(name),start=line.indexOf('(',token+name.length);if(start<0)return null;let depth=1,end=start+1;while(end<line.length&&depth){if(line[end]==='(')depth++;if(line[end]===')')depth--;end++;}assert.equal(depth,0);return line.slice(start+1,end-1);}
export function occurrences(s,p,commit){return s.split('\n').flatMap((line,i)=>{if(!line.includes(name))return [];const kind=classify(line),start=line.indexOf(name);let frame='not invoked';if(kind==='DIRECT ARRAY CALLBACK')frame='Implicit (profile,index,array): invalid center -> unadjusted receiving; accidental callback behavior, not intended frame';if(kind==='EXPLICIT CALL')frame=line.includes("rbPolicy==='v115-partial-orthogonal'")?'V115 fitted beta/center; non-V115 beta1/center0':argumentsOf(line)&&!argumentsOf(line).includes(',')?'Default beta1/center0 for effective individual prior':'Research explicit/default frame, not production authority';return [{commit,path:p,line:i+1,kind,arguments:kind==='EXPLICIT CALL'?argumentsOf(line):kind==='DECLARATION'?'profile, recvBeta=1, qbCenter=0':kind==='DIRECT ARRAY CALLBACK'?'Array.map implicitly supplies profile,index,array':null,usesDefaults:kind==='DIRECT ARRAY CALLBACK'?'No: extra callback arguments override defaults':kind==='EXPLICIT CALL'&&argumentsOf(line)&&!argumentsOf(line).includes(',')?'Yes: beta1/center0':'See explicit arguments',expectedFrame:frame,lineSHA256:sha(line),excerpt:line.length<=400?line.trim():line.slice(Math.max(0,start-45),start+160),generatedMirror:p.startsWith('public/')}];});}
const snippets=[['v115-design-comment','// V115 learns',4],['fit',"const priorQbPassValues=",4],['live-rb',"const rbRecvResidual=",1],['wr-reference',"const priorReceiverResidualValues=",3],['live-cdf-reference',"const priorRbOrthogonalValuesV109=",1],['effective-reference',"const priorRbOrthogonalValues=",1],['effective-individual',"const priorRbByTeam =",9],['run-prior-analogue',"const priorRunDefenseByTeam =",6],['legacy-rb-score','const scoreRbLegacy=',1],['build-policy-defaults','function buildProfiles(',1],['legacy-live-use',"rbPolicy==='v102-residual-receiving' && priorRbOrthogonalValues.length",2]];
const docs=['scripts/test_v57_unit_regression_rb.js','scripts/test_v102_offense_orthogonalization.js','CHANGELOG_V57.md','CHANGELOG_V102.md','CHANGELOG_V104.md','CHANGELOG_V109.md','CHANGELOG_V114.md','CHANGELOG_V115.md','scripts/test_v104_qb_calibration.js','scripts/test_v104_contract.js','scripts/test_v114_unit_centering.js','scripts/test_v114_contract.js','scripts/test_v115_unit_orthogonalization.js'];
export function extract(){
 assert.equal(git('rev-parse','--is-shallow-repository').trim(),'false');assert.deepEqual(git('rev-list','--max-parents=0',BASE).trim().split('\n'),[ROOT]);
 assert.deepEqual(git('log','--reverse','--format=%H',BASE,'--',model).trim().split('\n'),SOURCE_COMMITS);
 assert.equal(git('rev-parse',ACCEPTED+'^').trim(),ORIGINAL);assert.equal(git('rev-parse',ORIGINAL+'^').trim(),BASE);
 const evidence={},snapshots=[];
 for(const commit of [...SOURCE_COMMITS,BASE]){const s=blob(commit,model),lines=s.split('\n'),prefix=commit===ROOT?'root':commit===BASE?'base':commit.slice(0,7),blocks={};
  for(const fn of functions){const b=body(s,fn);evidence[prefix+'.'+fn]={commit,path:model,...b};blocks[fn]=sha(b.text);}
  for(const [label,token,n] of snippets){const i=lines.findIndex(l=>l.includes(token));assert(i>=0,label);evidence[prefix+'.'+label]={commit,path:model,startLine:i+1,endLine:i+n,text:lines.slice(i,i+n).join('\n')};}
  snapshots.push({commit,sourceSHA256:sha(s),functionSHA256:blocks,callSites:occurrences(s,model,commit)});
 }
 for(const fn of functions)assert(snapshots.every(s=>s.functionSHA256[fn]===snapshots[0].functionSHA256[fn]),fn+' later change');
 const history=SOURCE_COMMITS.map((commit,i)=>{const [date,message]=git('show','-s','--format=%aI%n%s',commit).trim().split('\n'),parent=git('show','-s','--format=%P',commit).trim();const diff=git('show','--format=','--unified=0',commit,'--',model);return {commit,date,message,parent:parent||null,modelDiffSHA256:sha(diff),helperOccurrenceDiff:i===0?Object.entries(evidence).filter(([k])=>k.startsWith('root.')).map(([id,b])=>({evidence:id,addedLines:b.text.split('\n').map(l=>'+'+l)})):diff.split('\n').filter(l=>(l.startsWith('+')||l.startsWith('-'))&&l.includes(name)),relevantDiff:i===0?'Root added entire V149 source; exact relevant added lines retained in root evidence blocks. Not an original V115 introducing diff.':'Only export-list occurrence changed for this helper; RB signatures, calls and fitted construction unchanged.',helperChanged:i===0?'Already present in initial import; original introduction unknown':false};});
 const contractEvidence=docs.map(p=>{const s=blob(ROOT,p),now=blob(BASE,p);assert.equal(s,now,p+' changed since imported');evidence['doc.'+p]={commit:ROOT,path:p,startLine:1,endLine:s.split('\n').length,text:s};return {path:p,earliestLocalCommit:ROOT,sourceSHA256:sha(s),history:git('log',BASE,'--format=%H','--',p).trim().split('\n')};});
 // Fit only the already-used parameters from bundled historical profiles, never new performance metrics.
 const ctx={window:{}};vm.createContext(ctx);vm.runInContext(blob(BASE,'data/matchup-data.js'),ctx);vm.runInContext(blob(BASE,model),ctx);
 const L=ctx.window.FORCE_LIVE_PROFILE,M=ctx.window.MATCHUP_DATA,ps=Object.values(M.profiles),points=ps.map(p=>({x:L.priorQbPassEpa(p),y:Number(p.rb?.adj_recv)})),beta=L.ridgeOrthogonalSlope(points,.50),center=L.medianValue(ps.map(L.priorQbPassEpa));
 const frozen=JSON.parse(fs.readFileSync('research/cycle8/md07_unit_calibration/inputs/current_snapshot.json','utf8'));assert(Math.abs(beta-frozen.teams.KC.raw.rbRecvOrthogonalBeta)<1e-12);assert.equal(center,frozen.teams.KC.raw.receiverEnvironmentCenter);
 const fittedProvenance={season:M.meta.season,profileCount:ps.length,finitePairs:points.filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)).length,requiredFieldsComplete:ps.every(p=>Number.isFinite(p.rb.rush_epa)&&Number.isFinite(p.rb.adj_recv)&&Number.isFinite(L.priorQbPassEpa(p))),beta,center,ridgeFraction:.50,inputSHA256:sha(blob(BASE,'data/matchup-data.js')),meaning:'Reference-season profile population plus model-version ridge rule; recomputed from supplied priors at build time, not fitted from current-season outputs. All32 historical profiles can use the fitted transformation.'};
 const files=git('grep','-l',name,ACCEPTED,'--','*.js','*.mjs','*.py').trim().split('\n').map(p=>p.slice(ACCEPTED.length+1)).sort();
 const acceptedTree=files.flatMap(p=>occurrences(blob(ACCEPTED,p),p,ACCEPTED));
 const otherFileVersions=files.filter(p=>p!==model&&p!=='public/'+model).flatMap(p=>git('log','--reverse','--format=%H',ACCEPTED,'--',p).trim().split('\n').map(commit=>({commit,path:p,sourceSHA256:sha(blob(commit,p)),occurrences:occurrences(blob(commit,p),p,commit)})));
 const callsite={otherFileVersions,scope:'Every tracked JS/MJS/Python helper occurrence at accepted tip; source snapshots cover every model-changing commit on shared-base ancestry. Public mirror, declaration/export and contract strings separated; research callers are retrospective controls.',sourceSnapshots:snapshots.map(s=>({commit:s.commit,occurrences:s.callSites})),acceptedTree};
 const documentationSearch=[ROOT,BASE].flatMap(commit=>git('grep','-n','-i','-E','V115|RB.*orthogonal|partial.orthogonal|running.back.*residual|receiving.beta|prior.reference|reference.distribution|quarterback.context|RB.policy',commit,'--','*.md',':!research/**').trim().split('\n').filter(Boolean).map(line=>{const rest=line.slice(commit.length+1),match=rest.match(/^([^:]+):(\d+):(.*)$/);assert(match);return {commit,path:match[1],line:Number(match[2]),text:match[3].slice(0,600),fullLineSHA256:sha(match[3]),role:commit===ROOT?'Imported release-era document; original authorship chronology unavailable':'Shared-base document; later retrospective evidence is secondary only'};}));
 const h={documentationSearch,base:BASE,original:ORIGINAL,accepted:ACCEPTED,localRoot:ROOT,originalV115IntroducingCommit:'UNAVAILABLE: non-shallow repository begins with V149 import; no older introducing diff or V115-named commit recovered',history,sourceSnapshots:snapshots.map(({callSites,...s})=>s),contracts:contractEvidence,fittedProvenance,evidence};
 return {'history.json':h,'callsite_inventory.json':callsite};
}
export function serialize(x){return Object.fromEntries(Object.entries(x).map(([k,v])=>[k,JSON.stringify(v,null,2)+'\n']));}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){for(const [p,t] of Object.entries(serialize(extract())))fs.writeFileSync(DIR+'/'+p,t);console.log('RB intent: read-only historical extraction complete');}
