import {hash,json,fail,SHA,isId,iso,safeMessage} from './util.mjs';
export const STATE_PATH='research/claude-deep-review/deep-review-state.json';
export const TRIGGERS=Object.freeze({MODEL_SCORING:'Overall FORCE scoring, normalization/raw-display architecture, bridges/cross-unit weighting',UNIT_PLAYER:'Major unit/player aggregation or QB methodology and QB/OL/pressure interactions',OPPONENT_PRIORS:'Opponent adjustment/SOS/prior/continuity/recency architecture',DATA_PROVIDER:'Provider replacement/precedence/fallback/data identity/team mapping',FORECASTING:'FORCEcast/Monte Carlo/score-spread-total distributions/representative scores',PLAYOFFS:'Playoff simulation/probability/seeding/tiebreak architecture',VALIDATION_CALIBRATION:'Calibration/Brier/historical backtest methodology',HISTORICAL:'Historical data/replay/normalization/reference/temporal policy',LUCK_FLAG_DRIVES:'Substantial Luck/FLAG/penalty/drive/scoring-prevention semantics',RUNTIME_RELEASE_TRUST:'Major Worker/container/server/deployment/security/trust/release/launch'});
const CLASSES=['SUBSTANTIVE','HOUSEKEEPING','AMBIGUOUS'];
export function chicagoDate(time,zone='America/Chicago'){const parts=new Intl.DateTimeFormat('en-US',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(iso(time)));return ['year','month','day'].map(k=>parts.find(p=>p.type===k).value).join('-');}
const ordinal=d=>Date.parse(d+'T00:00:00Z')/86400000;
export function initialize(main,now){fail(SHA.test(main),'INVALID_BASELINE_SHA');const state={schema:1,timezone:'America/Chicago',baselineMain:main,lastCompletedDeepReview:null,integrations:[],triggers:[],completionHistory:[],confirmedSubstantiveIntegrations:0,ambiguousIntegrationIds:[],activeMandatoryTriggers:[],lastEvaluation:null};return refresh(state,now);}
export function validateState(s){
 fail(s?.schema===1&&s.timezone==='America/Chicago'&&SHA.test(s.baselineMain)&&Array.isArray(s.integrations)&&Array.isArray(s.triggers)&&Array.isArray(s.completionHistory),'INVALID_CADENCE_STATE');const ids=new Set();
 for(const e of s.integrations){fail(isId(e.id)&&!ids.has(e.id)&&SHA.test(e.main)&&SHA.test(e.previousMain)&&e.main!==e.previousMain&&CLASSES.includes(e.classification)&&safeMessage(e.title)&&safeMessage(e.rationale)&&Array.isArray(e.tags)&&e.tags.every(t=>Object.hasOwn(TRIGGERS,t)),'INVALID_INTEGRATION_EVENT');iso(e.time);ids.add(e.id);}
 ids.clear();for(const t of s.triggers){fail(isId(t.id)&&!ids.has(t.id)&&Object.hasOwn(TRIGGERS,t.category)&&safeMessage(t.rationale)&&typeof t.active==='boolean','INVALID_MANDATORY_TRIGGER');iso(t.time);if(!t.active){iso(t.clearedAt);fail(safeMessage(t.clearRationale),'TRIGGER_CLEAR_RATIONALE_REQUIRED');}ids.add(t.id);}
 if(s.lastCompletedDeepReview){const c=s.lastCompletedDeepReview;iso(c.time);iso(c.targetAsOf);fail(isId(c.runId)&&SHA.test(c.main)&&c.date===chicagoDate(c.time,s.timezone),'INVALID_COMPLETION_RECORD');}
 return s;
}
export function evaluate(s,now){validateState(s);now=iso(now);fail(s.integrations.every(e=>Date.parse(e.time)<=Date.parse(now))&&s.triggers.every(e=>Date.parse(e.time)<=Date.parse(now)),'FUTURE_CADENCE_EVENT');const confirmed=s.integrations.filter(e=>e.classification==='SUBSTANTIVE').length,ambiguous=s.integrations.filter(e=>e.classification==='AMBIGUOUS').map(e=>e.id),active=s.triggers.filter(t=>t.active).map(t=>t.id),last=s.lastCompletedDeepReview;
 const recent=last?Date.parse(now)-Date.parse(last.time)<86400000:false;fail(!last||Date.parse(now)>=Date.parse(last.time),'EVALUATION_BEFORE_COMPLETION');
 let status,reason=[];const days=last?ordinal(chicagoDate(now,s.timezone))-ordinal(last.date):null;
 if(active.length){status='DEEP REVIEW DUE';reason.push(recent?'MANDATORY DEEP REVIEW DUE — LAST AUDIT <24H':'MANDATORY DEEP REVIEW DUE');}
 else if(!last){status='DEEP REVIEW DUE';reason.push('INITIAL BASELINE — NO COMPLETED DEEP REVIEW RECORDED');}
 else if(recent){status='NOT DUE';reason.push('ROUTINE SUPPRESSED — LAST COMPLETED AUDIT <24H');}
 else if(confirmed>=5||days>=7){status='DEEP REVIEW DUE';if(confirmed>=5)reason.push('5 SUBSTANTIVE INTEGRATIONS');if(days>=7)reason.push('7 CALENDAR DAYS IN '+s.timezone);}
 else if(confirmed+ambiguous.length>=5){status='CADENCE AMBIGUOUS — OWNER CLASSIFICATION REQUIRED';reason.push('AMBIGUOUS INTEGRATIONS CAN CHANGE THE 5-EVENT THRESHOLD');}
 else{status='NOT DUE';reason.push('ROUTINE THRESHOLDS NOT REACHED');}
 return {time:now,status,reasons:reason,confirmedSubstantiveIntegrations:confirmed,ambiguousIntegrationIds:ambiguous,activeMandatoryTriggers:active,calendarDaysSinceCompletion:days,routineSuppressed:recent};
}
export function refresh(s,now){const e=evaluate(s,now);return {...s,confirmedSubstantiveIntegrations:e.confirmedSubstantiveIntegrations,ambiguousIntegrationIds:e.ambiguousIntegrationIds,activeMandatoryTriggers:e.activeMandatoryTriggers,lastEvaluation:e};}
export function recordIntegration(s,event,now){validateState(s);fail(!s.integrations.some(x=>x.id===event.id),'DUPLICATE_INTEGRATION_ID');const next=structuredClone(s);fail(event.previousMain===(s.integrations.at(-1)?.main??s.lastCompletedDeepReview?.main??s.baselineMain),'INTEGRATION_CHAIN_MISMATCH');fail(!s.integrations.length||Date.parse(event.time)>=Date.parse(s.integrations.at(-1).time),'INTEGRATION_TIME_ORDER');next.integrations.push({...event,time:iso(event.time),tags:event.tags??[]});for(const tag of event.tags??[])next.triggers.push({id:event.id+'-'+tag,category:tag,rationale:event.rationale,time:iso(event.time),active:true,sourceIntegration:event.id});return refresh(next,now);}
export function classifyIntegration(s,id,classification,rationale,now){fail(CLASSES.includes(classification)&&safeMessage(rationale),'INVALID_CLASSIFICATION');const next=structuredClone(s),event=next.integrations.find(e=>e.id===id);fail(event,'UNKNOWN_INTEGRATION');event.classificationHistory??=[];event.classificationHistory.push({time:iso(now),previous:event.classification,next:classification,rationale});event.classification=classification;event.rationale=rationale;return refresh(next,now);}
export function recordTrigger(s,trigger,now){fail(!s.triggers.some(t=>t.id===trigger.id),'DUPLICATE_TRIGGER');return refresh({...s,triggers:[...s.triggers,{...trigger,time:iso(trigger.time),active:true}]},now);}
export function clearTrigger(s,id,rationale,now){fail(safeMessage(rationale),'CLEAR_RATIONALE_REQUIRED');const next=structuredClone(s),t=next.triggers.find(t=>t.id===id);fail(t?.active,'UNKNOWN_OR_INACTIVE_TRIGGER');t.active=false;t.clearedAt=iso(now);t.clearRationale=rationale;return refresh(next,now);}
export function completeCadence(s,verifiedRun,now,confirm=false){
 fail(confirm===true&&verifiedRun?.verifiedComplete===true&&verifiedRun.apiCalls>0&&verifiedRun.passes>0,'VALID_COMPLETE_RUN_AND_EXPLICIT_CONFIRMATION_REQUIRED');fail(!s.completionHistory.some(c=>c.runId===verifiedRun.runId),'COMPLETION_ALREADY_RECORDED');
 const cutoff=iso(verifiedRun.createdAt),time=iso(now);fail(!s.lastCompletedDeepReview||Date.parse(time)-Date.parse(s.lastCompletedDeepReview.time)>=86400000||verifiedRun.mandatoryReview===true,'ROUTINE_COMPLETION_SUPPRESSED_WITHIN_24H');fail(Date.parse(cutoff)<=Date.parse(time),'INVALID_COMPLETION_TIME');const c={time,date:chicagoDate(time,s.timezone),main:verifiedRun.target,runId:verifiedRun.runId,targetAsOf:cutoff,manifestHash:verifiedRun.manifestHash,toolingHead:verifiedRun.toolingHead};
 // Events after the reviewed snapshot was planned are never silently consumed by a slow audit.
 let directReview=s.directReview;if(verifiedRun.policy==='force-risk-rotation-v3'){fail(verifiedRun.auditType==='ROUTINE'&&verifiedRun.directCoverage?.length&&hash(json(directReview??verifiedRun.directSnapshot))===verifiedRun.directSnapshotHash&&verifiedRun.auditOrdinal===(directReview??verifiedRun.directSnapshot).completedAudits+1,'DIRECT_STATE_STALE_OR_INCOMPLETE');directReview=structuredClone(directReview??verifiedRun.directSnapshot);directReview.completedAudits=verifiedRun.auditOrdinal;for(const f of verifiedRun.directCoverage){const prev=directReview.files[f.path]??{lastRunId:null,lastDate:null,lastTarget:null,lastBlob:null,lastAudit:null,passes:[],selectionReason:null};directReview.files[f.path]={...prev,tier:f.tier,changedSinceLastReview:prev.lastBlob!==f.blob,...(f.directSelected?{lastRunId:verifiedRun.runId,lastDate:time,lastTarget:verifiedRun.target,lastBlob:f.blob,lastAudit:verifiedRun.auditOrdinal,passes:f.passes,selectionReason:f.reasons,changedSinceLastReview:false}:{})};}}const next={...s,...(directReview?{directReview}:{}),lastCompletedDeepReview:c,integrations:s.integrations.filter(e=>Date.parse(e.time)>Date.parse(cutoff)),triggers:s.triggers.map(t=>t.active&&Date.parse(t.time)<=Date.parse(cutoff)?{...t,active:false,clearedAt:time,clearRationale:'Covered by explicitly recorded complete run '+c.runId}:t),completionHistory:[...s.completionHistory,{...c,coveredIntegrations:s.integrations.filter(e=>Date.parse(e.time)<=Date.parse(cutoff))}]};return refresh(next,time);
}