import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {git,hash,json,atomic} from './util.mjs';
import {inventory,EXCLUSIONS,classify,THEMES} from './inventory.mjs';
import {initialDirectState,selectDirect as selectCurrent,analyzeRepository,tierFor,assertSelectionSla,POLICIES,PERIOD} from './selection.mjs';
import {costDecomposition,outputBudget,BUDGET_POLICY,economicClassification} from './economics.mjs';
import {simulateFive,unavoidableInputFloor,simulateTwelve} from './simulation.mjs';
import {compactMap} from './selection.mjs';
import {buildPlan as riskPlanV2} from './risk-plan-v2.mjs';
import {buildPlan as legacyPlan} from './literal-plan-v1.mjs';
import {authorizeBudget} from './run.mjs';
import {buildPlan,chunkBuffer,validateCoverage,HARD_LIMIT} from './plan.mjs';
import {initialize,evaluate,refresh,recordIntegration,classifyIntegration,recordTrigger,clearTrigger,completeCadence,TRIGGERS,chicagoDate} from './cadence.mjs';
import {createRun,loadRun,status,runPass,verifyCompletion,ownerScripts,verifySendEnvironment} from './run.mjs';
import {synthesize} from './synthesis.mjs';
import {DEEP_DOCTRINE,parseDeepReview,NATURES} from './doctrine.mjs';
import {parseArgs} from '../deep-review.mjs';
import {SYSTEM} from '../client.mjs';
const TARGET='1'.repeat(40),NOW='2026-10-08T12:00:00.000Z';
// Retain the original 1/2/4 regression scenarios explicitly; new tests below cover the default SLA.
const selectDirect=(inv,a,state,o={})=>selectCurrent(inv,a,state,{rotationPolicy:'A',...o});
const options={rotationPolicy:'A',runId:'TEST-DEEP-001',chunkBytes:256,coverageBytes:12288,themeBytes:24576,maxTokens:256,maxUsd:5,maxTotalUsd:200};
async function fixture(fn){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'force-deep-test-'));
 try{git(root,['init','-q']);git(root,['config','user.name','Disposable mock']);git(root,['config','user.email','mock@example.invalid']);git(root,['config','core.autocrlf','false']);
  const write=(name,value)=>{const p=path.join(root,name);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,value);};
  const source='// model source\r\nexport const x=1;\r\n';
  for(const [p,s]of Object.entries({'.gitignore':'research/claude-api-reviews/\n','model/source.js':source,'assets/app.js':source,'README.md':'# human methodology\n','unknown.zz':'unknown but readable\n','scripts/test_example.mjs':'// negative control source\n','scripts/run_tests.mjs':'// runner\n','scripts/test_catalog.json':'{}\n','scripts/build_public.py':'# build\n','Dockerfile':'FROM pinned\n','force_server.py':'# source\n','data/seed.js':'export const data={};\n','public/model/source.js':source,'research/example/analyze.mjs':'// generator\n','research/example/results/data.json':'{"a":1}\n','research/example/inputs.json':'{"method":"identity"}\n','scripts/fixtures/contract.json':'{"required":"input"}\n','research/example/fixtures/pop.csv':'team,value\nA,2\n','data/live-cache/cache.json':'{"payload":1}\n','vendor/upstream.js':'// third-party\n'}))write(p,s);
  write('image.png',Buffer.from([0,2,3]));write('odd.bin',Buffer.from([255,254]));write('large.md',('LONG UTF8 αβ🌟\r\n').repeat(1000));write('one-line.txt','🧪'.repeat(1000));
  git(root,['add','.']);git(root,['commit','-qm','target']);const target=git(root,['rev-parse','HEAD']).trim();git(root,['branch','-m','analysis']);
  const directState={...initialDirectState(inventory(root,target)),completedAudits:3};const built=()=>buildPlan(root,target,{...options,directState}),save=()=>{const b=built();return createRun(root,b,initialize(target,NOW),NOW);};await fn({root,target,write,built,save});
 }finally{assert(root.startsWith(path.join(os.tmpdir(),'force-deep-test-')));fs.rmSync(root,{recursive:true,force:true});}
}
function completedState(time='2026-10-01T12:00:00.000Z'){return completeCadence(initialize(TARGET,time),{verifiedComplete:true,apiCalls:1,passes:1,runId:'PAID-BASELINE',target:TARGET,createdAt:time,manifestHash:'2'.repeat(64),toolingHead:TARGET},time,true);}
function events(s,n,classification='SUBSTANTIVE'){for(let i=0;i<n;i++){const previousMain=s.integrations.at(-1)?.main??TARGET;s=recordIntegration(s,{id:'I-'+(s.integrations.length+1),time:'2026-10-02T12:00:00.000Z',main:(s.integrations.length+2).toString(16).padStart(40,'0'),previousMain,title:'Owner-authorized integration',classification,rationale:'Behavioral contract changed',tags:[]},NOW);}return s;}
function outcome(target,findings=[]){return {verdict:findings.some(f=>f.severity==='MINOR')?'ACCEPTED WITH MINORS':'ACCEPTED',summary:'Independent mocked review',findings,limitations:['Mock only'],scope:{start_sha:target,end_sha:target}};}
function finding(p,nature='ACTUAL DEFECT',severity='MINOR',evidence='specific observed source evidence'){return {severity,nature,affected_paths:[p],location:p+':1',evidence,impact:'Concrete contract risk',correction:'Bounded verification',confidence:'HIGH'};}
const mockKey='mock-'+'k'.repeat(40);
function deps(target,change={},counts={keys:0,calls:0},custom){return {environmentVerifier:()=>{},secretLoader:()=>{counts.keys++;return mockKey;},fetcher:async(_u,opt)=>{counts.calls++;const body=JSON.parse(opt.body);assert.equal(body.system[0].text,SYSTEM);assert(body.system[0].cache_control);assert.equal(body.system[1].text,DEEP_DOCTRINE);const raw={type:'message',id:'msg_mock',model:'claude-opus-5-5',stop_reason:'end_turn',content:[{type:'text',text:JSON.stringify(custom??outcome(target))}],usage:{input_tokens:100,output_tokens:50,cache_creation_input_tokens:0,cache_read_input_tokens:0},...change};return new Response(JSON.stringify(raw),{status:200,headers:{'request-id':'req_mock'}});}};}
function sendOptions(run,p,extra={}){return {send:true,toolingHead:run.plan.toolingHead,target:run.plan.target,manifestHash:run.plan.manifestHash,packetHash:p.packetSha256,maxUsd:5,maxTotalUsd:200,...extra};}

test('deterministic target Git inventory, post-target files never leak',()=>fixture(p=>{const a=p.built();p.write('post-target.js','POST_TARGET_SENTINEL');git(p.root,['add','.']);git(p.root,['commit','-qm','tooling after target']);p.write('README.md','DIRTY_WORKTREE_SENTINEL');const b=p.built();assert.equal(a.manifestText,b.manifestText);assert.deepEqual([...a.packets],[...b.packets]);assert(!b.manifest.files.some(f=>f.path==='post-target.js'));assert(![...b.packets.values()].some(s=>s.includes('DIRTY_WORKTREE_SENTINEL')));}));
for(const name of ['model/source.js','README.md','scripts/test_example.mjs','scripts/run_tests.mjs','scripts/test_catalog.json','Dockerfile','force_server.py','data/seed.js','research/example/analyze.mjs','research/example/inputs.json','scripts/fixtures/contract.json','large.md','one-line.txt'])test('actual content eligible: '+name,()=>fixture(p=>{const f=p.built().manifest.files.find(f=>f.path===name);assert(f.eligible);assert(f.ranges.length>0);}));
for(const [name,reason]of [['image.png','BINARY_MEDIA'],['odd.bin','BINARY_MEDIA'],['data/live-cache/cache.json','RAW_PROVIDER_CACHE'],['research/example/fixtures/pop.csv','FIXTURE_POPULATION'],['research/example/results/data.json','GENERATED_EVIDENCE'],['public/model/source.js','EXACT_PUBLIC_MIRROR'],['vendor/upstream.js','VENDORED_THIRD_PARTY']])test('explicit exclusion: '+reason+' '+name,()=>fixture(p=>{const f=p.built().manifest.files.find(f=>f.path===name);assert(!f.eligible);assert.equal(f.exclusionReason,reason);assert(EXCLUSIONS[reason]);}));
test('unknown readable files surface ambiguity and stay covered',()=>fixture(p=>{const f=p.built().manifest.files.find(f=>f.path==='unknown.zz');assert(f.ambiguity.length);assert(f.eligible);}));
test('unproven public mirror and generated evidence remain eligible',()=>fixture(p=>{p.write('public/model/source.js','different generated content');p.write('research/no-source/results/file.json','{}');git(p.root,['add','.']);git(p.root,['commit','-qm','different mirror']);const x=inventory(p.root,git(p.root,['rev-parse','HEAD']).trim());assert(x.files.find(f=>f.path==='public/model/source.js').eligible);assert(x.files.find(f=>f.path==='research/no-source/results/file.json').eligible);}));
test('symlink disposition is explicit and not followed',{skip:process.platform==='win32'},()=>fixture(p=>{fs.symlinkSync('../README.md',path.join(p.root,'model/link'));git(p.root,['add','.']);git(p.root,['commit','-qm','link']);const x=inventory(p.root,git(p.root,['rev-parse','HEAD']).trim());assert.equal(x.files.find(f=>f.path==='model/link').exclusionReason,'NONREGULAR_OBJECT');}));
test('credential-pattern planning refuses content without key lookup',()=>fixture(p=>{p.write('secret-example.txt','sk'+'-ant-'+ 'z'.repeat(30));git(p.root,['add','.']);git(p.root,['commit','-qm','synthetic credential']);assert.throws(()=>inventory(p.root,git(p.root,['rev-parse','HEAD']).trim()),/Credential-pattern/);}));
for(const [name,b]of [['CRLF',Buffer.from('a\r\nb\r\n')],['BOM',Buffer.from('\ufeffa\r\n')],['long UTF8 line',Buffer.from('🌟α'.repeat(100))],['empty',Buffer.alloc(0)],['long ascii',Buffer.from('q'.repeat(100))]])test('lossless deterministic splitting: '+name,()=>{const c=chunkBuffer(b,7);assert.deepEqual(c,chunkBuffer(b,7));assert(Buffer.concat(c.map(c=>Buffer.from(c.text))).equals(b));assert(c.every(c=>c.end-c.start<=7));});
test('every eligible byte covered, chunks assigned correctly across boundaries',()=>fixture(p=>{const a=p.built(),inv=inventory(p.root,p.target);assert(validateCoverage(a.manifest,a.packets,inv));assert(a.manifest.files.find(f=>f.path==='large.md').contentShards.length>1);for(const d of a.plan.passes){assert(d.packetBytes<= (d.kind==='CONTENT'?options.coverageBytes:options.themeBytes));assert(d.packetBytes<HARD_LIMIT-65536);assert.equal(hash(a.packets.get(d.id)),d.packetSha256);}assert.equal(a.plan.summary.inventoryCoveragePercent,100);}));
for(const defect of ['missing-file','excluded-eligible','unknown-reason','coverage-gap','altered-chunk'])test('coverage checker catches '+defect,()=>fixture(p=>{const a=p.built(),inv=inventory(p.root,p.target),m=structuredClone(a.manifest),packets=new Map(a.packets),f=m.files.find(f=>f.path==='README.md');if(defect==='missing-file')m.files.pop();if(defect==='excluded-eligible'){f.eligible=false;f.disposition='EXCLUDED';f.exclusionReason='too_large';}if(defect==='unknown-reason')m.files.find(f=>!f.eligible).exclusionReason='OTHER';if(defect==='coverage-gap')f.ranges[0].start++;if(defect==='altered-chunk'){const body=JSON.parse(packets.get(f.ranges[0].shard));body.content.find(c=>c.path===f.path).text='WRONG';packets.set(f.ranges[0].shard,json(body));}assert.throws(()=>validateCoverage(m,packets,inv));}));
test('four complementary themes expose complete map and selected bytes exactly once',()=>fixture(p=>{const a=p.built(),contents=inventory(p.root,p.target).contents;for(const theme of THEMES){const ds=a.plan.passes.filter(p=>p.theme===theme.id);assert(ds.length);for(const d of ds)assert.equal(JSON.parse(a.packets.get(d.id)).repoMap.rows.length,a.manifest.files.length);}for(const f of a.manifest.files.filter(f=>f.directSelected)){const cs=[...a.packets.values()].flatMap(x=>JSON.parse(x).content).filter(c=>c.path===f.path);assert(Buffer.concat(cs.map(c=>Buffer.from(c.text))).equals(contents.get(f.path)));}}));
test('planning fails on overhead or budgets, never silently drops eligible content',()=>fixture(p=>{assert.throws(()=>buildPlan(p.root,p.target,{...options,directState:p.built().plan.options.directState,chunkBytes:32768,themeBytes:8192}),/OVERHEAD|CHUNK/);assert(buildPlan(p.root,p.target,{...options,maxTotalUsd:0.00001}).plan.budgetWarnings.some(w=>w.includes('TOTAL GUARD')));assert.throws(()=>buildPlan(p.root,p.target,{...options,maxUsd:0.00001}),/PER_CALL/);assert.throws(()=>buildPlan(p.root,p.target,{...options,themeBytes:HARD_LIMIT}),/MARGIN/);}));

test('bootstrap due honestly, no synthetic historical completion',()=>{const s=initialize(TARGET,NOW);assert.equal(s.lastCompletedDeepReview,null);assert.match(s.lastEvaluation.reasons[0],/INITIAL BASELINE/);});
test('five substantive integration events count independently of commit counts',()=>{assert.equal(evaluate(events(completedState(),4),'2026-10-03T12:00:00.000Z').status,'NOT DUE');assert.equal(evaluate(events(completedState(),5),'2026-10-03T12:00:00.000Z').status,'DEEP REVIEW DUE');});
test('housekeeping excluded, ambiguous threshold explicit, reclassification resolves',()=>{let s=events(completedState(),4);s=events(s,1,'AMBIGUOUS');s=events(s,2,'HOUSEKEEPING');const time='2026-10-03T12:00:00.000Z';assert.match(evaluate(s,time).status,/CADENCE AMBIGUOUS/);assert.equal(evaluate(classifyIntegration(s,'I-5','HOUSEKEEPING','Closeout only',NOW),time).status,'NOT DUE');assert.equal(evaluate(classifyIntegration(s,'I-5','SUBSTANTIVE','Behavioral gate',NOW),time).status,'DEEP REVIEW DUE');assert.equal(evaluate(s,NOW).status,'DEEP REVIEW DUE');});
test('seven Chicago calendar dates, not 168 hours; timezone crossing',()=>{const s=completedState('2026-10-01T23:30:00.000Z');assert.equal(evaluate(s,'2026-10-08T05:00:00.000Z').calendarDaysSinceCompletion,7);assert.equal(evaluate(s,'2026-10-08T04:59:59.000Z').status,'NOT DUE');assert.equal(chicagoDate('2026-10-08T04:00:00.000Z'),'2026-10-07');});
test('calendar cadence handles daylight saving independently of elapsed suppression',()=>{const s=completedState('2026-10-26T05:30:00.000Z');assert.equal(evaluate(s,'2026-11-02T06:00:00.000Z').calendarDaysSinceCompletion,7);assert.equal(chicagoDate('2026-11-01T06:30:00.000Z'),chicagoDate('2026-11-01T07:30:00.000Z'));});
test('routine suppressed for rolling elapsed 24h, exactly 24h allowed',()=>{let s=completedState('2026-10-02T11:00:00.000Z');s=events(s,5);assert.equal(evaluate(s,'2026-10-03T10:59:59.000Z').status,'NOT DUE');assert.equal(evaluate(s,'2026-10-03T11:00:00.000Z').status,'DEEP REVIEW DUE');});
for(const category of Object.keys(TRIGGERS))test('mandatory '+category+' bypasses routine suppression explicitly',()=>{const time='2026-10-08T13:00:00.000Z',s=recordTrigger(completedState(NOW),{id:'TRIGGER',category,rationale:'Explicit owner classified major architecture change',time},time),e=evaluate(s,time);assert.equal(e.status,'DEEP REVIEW DUE');assert.match(e.reasons[0],/MANDATORY.*<24H/);assert.equal(evaluate(clearTrigger(s,'TRIGGER','Owner cleared',time),time).status,'NOT DUE');});
test('unknown triggers, duplicate events and future events fail',()=>{assert.throws(()=>recordTrigger(completedState(),{id:'T',category:'UNKNOWN',rationale:'Unclassified',time:NOW},NOW));let s=events(completedState(),1);assert.throws(()=>recordIntegration(s,s.integrations[0],NOW),/DUPLICATE/);assert.throws(()=>evaluate(s,'2026-10-01T12:00:00.000Z'),/FUTURE/);});
test('completion resets covered events, retains integrations/triggers after reviewed snapshot',()=>{let s=events(completedState(),5);s=recordTrigger(s,{id:'NEW',category:'HISTORICAL',rationale:'New after snapshot',time:'2026-10-08T11:00:00.000Z'},NOW);const next=completeCadence(s,{verifiedComplete:true,apiCalls:2,passes:2,runId:'ALL-PASSES',target:TARGET,createdAt:'2026-10-03T12:00:00.000Z',manifestHash:'2'.repeat(64),toolingHead:TARGET},NOW,true,{isAncestor:()=>true});assert.equal(next.integrations.length,0);assert.equal(next.activeMandatoryTriggers.length,1);assert.equal(next.lastCompletedDeepReview.date,'2026-10-08');});
for(const bad of [{verifiedComplete:false},{verifiedComplete:true,apiCalls:0,passes:1},{verifiedComplete:true,apiCalls:1,passes:0}])test('dry/failed/incomplete cannot reset cadence '+JSON.stringify(bad),()=>{const s=initialize(TARGET,NOW);assert.throws(()=>completeCadence(s,bad,NOW,true));assert.equal(s.lastCompletedDeepReview,null);});
test('completion requires explicit confirmation and prevents duplicate run record',()=>{const s=initialize(TARGET,NOW),r={verifiedComplete:true,apiCalls:1,passes:1,runId:'R',target:TARGET,createdAt:NOW,manifestHash:'2'.repeat(64),toolingHead:TARGET};assert.throws(()=>completeCadence(s,r,NOW));const n=completeCadence(s,r,NOW,true);assert.throws(()=>completeCadence(n,r,NOW,true),/ALREADY/);});
test('run plan persistence and idempotent reconstruction, no overwrite',()=>fixture(p=>{const r=p.save();assert.deepEqual(loadRun(p.root,r.plan.runId).plan,r.plan);assert.throws(()=>p.save(),/RUN_ALREADY_EXISTS/);assert(status(r).pending.length);}));
for(const mode of [{},{send:false}])test('default/dry pass never reads key or requests '+JSON.stringify(mode),()=>fixture(async p=>{const r=p.save(),counts={keys:0,calls:0};const result=await runPass(p.root,r.plan.runId,r.plan.passes[0].id,mode,deps(p.target,{},counts));assert.equal(result.mode,'DRY_RUN');assert.deepEqual(counts,{keys:0,calls:0});assert.equal(loadRun(p.root,r.plan.runId).state.passes[r.plan.passes[0].id].status,'PENDING');assert.throws(()=>verifyCompletion(p.root,r.plan.runId),/INCOMPLETE/);}));
for(const [name,extra]of [['total',{maxTotalUsd:0.00001}],['per-call',{maxUsd:0.00001}],['packet-pin',{packetHash:'0'.repeat(64)}]])test(name+' guard before key/request',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],counts={keys:0,calls:0};await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass,extra),deps(p.target,{},counts)));assert.deepEqual(counts,{keys:0,calls:0});assert.equal(loadRun(p.root,r.plan.runId).state.passes[pass.id].attempts.length,0);}));
test('environment pins checked before key access and request intent',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],counts={keys:0,calls:0};await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),{...deps(p.target,{},counts),environmentVerifier:()=>{throw new Error('MAIN_MOVED');}}),/MAIN_MOVED/);assert.equal(counts.keys,0);}));
test('one send produces one request, complete pass cannot resend, resume omits completed',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],counts={keys:0,calls:0};const result=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,{},counts));assert.equal(result.status,'COMPLETED');assert.deepEqual(counts,{keys:1,calls:1});await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,{},counts)),/CANNOT_RESEND/);assert.equal(counts.calls,1);const resumed=loadRun(p.root,r.plan.runId);assert(!status(resumed).pending.includes(pass.id));assert.equal(status(resumed).rows.find(p=>p.id===pass.id).status,'COMPLETED');assert.throws(()=>verifyCompletion(p.root,r.plan.runId),/INCOMPLETE/);}));
for(const [label,change,want]of [['truncation',{stop_reason:'max_tokens'},'TRUNCATED_RESPONSE'],['wrong model',{model:'other-model'},'INVALID_RESPONSE'],['refusal',{stop_details:{type:'refusal'}},'INVALID_RESPONSE'],['wrong response schema',{type:'other'},'INVALID_RESPONSE']])test(label+' persists incomplete and does not auto retry',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],counts={keys:0,calls:0},result=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,change,counts));assert.equal(result.status,want);assert.equal(counts.calls,1);const next=loadRun(p.root,r.plan.runId);assert(status(next).ownerActionRequired.includes(pass.id));assert.throws(()=>verifyCompletion(p.root,r.plan.runId),/INCOMPLETE/);await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,{},counts)),/OWNER_ACTION_REQUIRED/);assert.equal(counts.calls,1);if(label==='truncation')assert.equal(result.telemetry.stopReason,'max_tokens');}));
test('network failure redacts exception, no automatic retry, explicit retry retained and budgeted',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],counts={keys:0,calls:0};const d=deps(p.target,{},counts);d.fetcher=async()=>{counts.calls++;throw new Error(mockKey);};const first=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),d);assert.equal(first.status,'REQUEST_FAILED');assert(!fs.readFileSync(path.join(r.dir,first.resultPath),'utf8').includes(mockKey));await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass,{retry:true,retryReason:'Owner checked failed attempt billing',maxTotalUsd:r.plan.estimatedCeilingUsd}),deps(p.target,{},counts)),/TOTAL_COST/);const second=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass,{retry:true,retryReason:'Explicit owner retry after billing inspection'}),deps(p.target,{},counts));assert.equal(second.status,'COMPLETED');assert.equal(loadRun(p.root,r.plan.runId).state.passes[pass.id].attempts.length,2);assert.equal(counts.calls,2);}));
test('missing secret safe result, zero requests; no plaintext persisted',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],counts={keys:0,calls:0},d=deps(p.target,{},counts);d.secretLoader=()=>{counts.keys++;throw new Error(mockKey);};const result=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),d);assert.equal(result.status,'REQUEST_FAILED');assert.equal(result.apiCalls,0);assert.equal(counts.calls,0);assert(!fs.readFileSync(path.join(r.dir,result.resultPath),'utf8').includes(mockKey));}));
test('unsafe reviewer content withheld with independently safe cost telemetry',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],v=outcome(p.target);v.summary=mockKey;const result=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,{},undefined,v));assert.equal(result.status,'INVALID_RESPONSE');const saved=JSON.parse(fs.readFileSync(path.join(r.dir,result.resultPath),'utf8'));assert.equal(saved.text,null);assert.equal(saved.review,null);assert.equal(saved.telemetry.requestId,'req_mock');assert(!json(saved).includes(mockKey));}));
test('intent saved before request; interrupted request requires owner action on restart',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],d=deps(p.target);const fetch=d.fetcher;d.fetcher=async(...args)=>{const s=JSON.parse(fs.readFileSync(path.join(r.dir,'run-state.json'),'utf8'));assert.equal(s.passes[pass.id].status,'OWNER_ACTION_REQUIRED');assert.equal(s.passes[pass.id].attempts[0].apiCalls,null);return fetch(...args);};await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),d);const state=loadRun(p.root,r.plan.runId).state;fs.unlinkSync(path.join(r.dir,state.passes[pass.id].resultPath));state.passes[pass.id]={status:'OWNER_ACTION_REQUIRED',resultPath:null,attempts:[{index:1,time:NOW,status:'OWNER_ACTION_REQUIRED',packetHash:pass.packetSha256,apiCalls:null,reservedUsd:pass.estimatedCeilingUsd}]};atomic(path.join(r.dir,'run-state.json'),state);await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target)),/OWNER_ACTION_REQUIRED/);}));
test('exclusive run lock refuses overlapping requests before key read',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],counts={keys:0,calls:0};fs.writeFileSync(path.join(r.dir,'run.lock'),'interrupted intent');await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,{},counts)),/run lock/);assert.equal(counts.keys,0);}));
for(const name of ['coverage-manifest.json','plan.json','theme-architecture-001.packet.json'])test('tamper refused before key/request: '+name,()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0];fs.appendFileSync(path.join(r.dir,name),' ');assert.throws(()=>loadRun(p.root,r.plan.runId),/MISMATCH|TAMPER/);}));
test('saved complete result cannot be replaced without integrity failure',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],result=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target));fs.appendFileSync(path.join(r.dir,result.resultPath),' ');assert.throws(()=>loadRun(p.root,r.plan.runId),/RESULT_TAMPER/);}));
test('run path traversal and output junction refused',()=>fixture(p=>{assert.throws(()=>loadRun(p.root,'../escape'),/INVALID_RUN_ID/);const target=path.join(p.root,'elsewhere');fs.mkdirSync(target);fs.mkdirSync(path.join(p.root,'research/claude-api-reviews'),{recursive:true});fs.symlinkSync(target,path.join(p.root,'research/claude-api-reviews/deep'),process.platform==='win32'?'junction':'dir');assert.throws(()=>p.save(),/SYMLINK/);assert.equal(fs.readdirSync(target).length,0);}));
test('local synthesis preserves raw IDs, groups duplicates vs corroboration, flags conflicts and incomplete',()=>fixture(async p=>{const r=p.save(),ps=r.plan.passes.slice(0,3);assert.equal(synthesize(p.root,r.plan.runId).complete,false);for(let i=0;i<ps.length;i++){const f=finding('model/source.js','ACTUAL DEFECT',i===2?'OPTIONAL':'MINOR',i===2?'Independent evidence with different classification':'specific observed source evidence');await runPass(p.root,r.plan.runId,ps[i].id,sendOptions(r,ps[i]),deps(p.target,{},undefined,outcome(p.target,[f])));}const summary=synthesize(p.root,r.plan.runId),report=JSON.parse(fs.readFileSync(summary.reportJSON,'utf8'));assert.equal(report.rawFindings.length,3);assert.equal(report.groups.length,1);assert.match(report.groups[0].relationship,/CORROBORATION/);assert(report.conflicts.length);assert.equal(report.complete,false);assert.equal(report.paidSynthesisCalls,0);assert(report.rawFindings.every(f=>f.passId&&f.id&&f.sourcePacketHash));}));
test('complete all valid passes then explicit cadence completion, not implied acceptance',()=>fixture(async p=>{const r=p.save();for(const pass of r.plan.passes)await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target));const verified=verifyCompletion(p.root,r.plan.runId);assert.equal(verified.passes,r.plan.passes.length);const state={...initialize(p.target,NOW),directReview:r.plan.options.directState};assert.equal(state.lastCompletedDeepReview,null);const next=completeCadence(state,verified,'2026-10-08T15:00:00.000Z',true);assert.equal(next.lastCompletedDeepReview.main,p.target);assert.equal(synthesize(p.root,r.plan.runId).complete,true);}));
test('owner scripts pin HEAD/main/manifest/packet and contain exactly one send each; no send-all',()=>fixture(p=>{const r=p.save(),scripts=ownerScripts(p.root,r.plan.runId,process.execPath,path.join(p.root,'tooling/deep-review.mjs'));assert.equal(scripts.length,r.plan.passes.length);for(const [i,s]of scripts.entries()){const text=fs.readFileSync(s,'utf8');assert.equal((text.match(/--send/g)??[]).length,1);assert(text.includes(r.plan.toolingHead));assert(text.includes(r.plan.target));assert(text.includes(r.plan.manifestHash));assert(text.includes(r.plan.passes[i].packetSha256));assert(text.includes('--max-total-usd'));}assert(fs.existsSync(path.join(r.dir,'complete.ps1')));}));
for(const nature of NATURES)test('deep nature taxonomy: '+nature,()=>{const p={start:TARGET,end:TARGET,paths:['model/a.js']};assert.equal(parseDeepReview(json(outcome(TARGET,[finding('model/a.js',nature)])),p).findings[0].nature,nature);});
test('verdict/severity, exact scope and inventory path consistency remain enforced',()=>{const p={start:TARGET,end:TARGET,paths:['model/a.js']},v=outcome(TARGET,[finding('model/a.js')]);assert.throws(()=>parseDeepReview(json({...v,verdict:'ACCEPTED'}),p),/CONTRADICTION/);assert.throws(()=>parseDeepReview(json({...v,scope:{start_sha:TARGET,end_sha:'0'.repeat(40)}}),p),/SCOPE/);assert.throws(()=>parseDeepReview(json(v),{...p,paths:[]}),/OUTSIDE/);});
test('CLI has no implicit send or send-all; malformed flags fail closed',()=>{assert.equal(parseArgs([]).command,'status');assert(!parseArgs(['pass','--run','R','--pass','P']).values.send);assert.equal(parseArgs(['pass','--run','R','--pass','P','--send']).values.send,true);for(const a of [['send-all'],['pass','--send','--dry-run'],['pass','--send','--send'],['pass','--pass','A','B'],['plan','--send'],['status','--send']])assert.throws(()=>parseArgs(a));});

test('corrupted attempt ledger and orphaned result never permit a fresh paid request',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0];await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target));const st=loadRun(p.root,r.plan.runId).state;st.passes[pass.id]={status:'PENDING',resultPath:null,attempts:[]};atomic(path.join(r.dir,'run-state.json'),st);assert.throws(()=>loadRun(p.root,r.plan.runId),/ORPHANED_RESULT/);}));
test('invalid IDs and calendar timestamps do not coerce into canonical cadence state',()=>{for(const id of [null,undefined,[],{}])assert.throws(()=>recordTrigger(completedState(),{id,category:'HISTORICAL',rationale:'Owner classified',time:NOW},NOW));assert.throws(()=>initialize(TARGET,'2026-02-30T12:00:00Z'),/CALENDAR/);});
test('integration event chain and timestamp ordering must agree with owner-recorded main updates',()=>{const s=events(completedState(),1);assert.throws(()=>recordIntegration(s,{...s.integrations[0],id:'I-2',previousMain:'9'.repeat(40)},NOW),/CHAIN/);});


test('routine completion refused inside 24h; explicitly mandatory run remains permitted',()=>{const s=completedState(NOW),r={verifiedComplete:true,apiCalls:1,passes:1,runId:'SECOND-AUDIT',target:TARGET,createdAt:NOW,manifestHash:'2'.repeat(64),toolingHead:TARGET};assert.throws(()=>completeCadence(s,r,'2026-10-08T13:00:00.000Z',true),/SUPPRESSED/);assert(completeCadence(s,{...r,mandatoryReview:true},'2026-10-08T13:00:00.000Z',true).lastCompletedDeepReview);});
const environmentCodes={head:'TOOLING_HEAD_CHANGED',dirty:'CLEAN_TOOLING_WORKTREE_REQUIRED',main:'SEND_FROM_OFF_MAIN_TOOLING_WORKTREE','local-main':'TARGET_NOT_ANCESTOR_OF_LOCAL_MAIN','tracking-main':'TARGET_NOT_ANCESTOR_OF_TRACKING_MAIN','remote-main':'TARGET_NOT_ANCESTOR_OF_REMOTE_MAIN',origin:'WRONG_FORCE_ORIGIN',pins:'EXACT_SEND_PINS_REQUIRED',target:'TARGET_OBJECT_UNAVAILABLE'};
function environmentFixture(variant='ok',advanced=false){const plan={toolingHead:TARGET,target:TARGET,manifestHash:'2'.repeat(64)},opts={toolingHead:TARGET,target:TARGET,manifestHash:'2'.repeat(64)},newer='f'.repeat(40);if(variant==='pins')opts.manifestHash='3'.repeat(64);const fake=(_root,args)=>{const key=args.join(' ');if(key==='rev-parse HEAD')return variant==='head'?'0'.repeat(40):TARGET;if(key==='symbolic-ref --short HEAD')return variant==='main'?'main':'codex/tooling';if(key.startsWith('status '))return variant==='dirty'?' M changed.js':'';if(key==='rev-parse refs/heads/main')return variant==='local-main'?'0'.repeat(40):advanced?newer:TARGET;if(key==='rev-parse refs/remotes/origin/main')return variant==='tracking-main'?'0'.repeat(40):advanced?newer:TARGET;if(key==='remote get-url origin')return variant==='origin'?'https://github.com/other/repo.git':'https://github.com/pfoeller/force-nfl.git';if(key==='ls-remote origin refs/heads/main')return (variant==='remote-main'?'0'.repeat(40):advanced?newer:TARGET)+'\trefs/heads/main';if(args[0]==='rev-parse'&&key.endsWith('^{commit}')){if(variant==='target'&&args[1]===TARGET+'^{commit}')throw Error('missing');return args[1].slice(0,-9);}if(args[0]==='merge-base'){if(args.at(-1)==='0'.repeat(40))throw Error('not ancestor');return '';}assert.fail('unexpected command '+key);};return {plan,opts,fake};}
for(const variant of ['ok',...Object.keys(environmentCodes)])test('pre-send environment '+variant+' independently checked',()=>{const {plan,opts,fake}=environmentFixture(variant);if(variant==='ok')assert.equal(verifySendEnvironment('.',plan,opts,{git:fake,nodeVersion:'24.19.0'}).mainAdvanced,false);else assert.throws(()=>verifySendEnvironment('.',plan,opts,{git:fake,nodeVersion:'24.19.0'}),new RegExp(environmentCodes[variant]));});


// Policy-amendment regressions: synthetic review states are never product completion evidence.

test('risk tiers derive from present source contracts deterministically',()=>{for(const f of [{path:'model/new-normalizer.js',classification:'model-statistical-source'},{path:'force_server.py',classification:'server-runtime'},{path:'wrangler.jsonc',classification:'config-build-deploy'},{path:'scripts/test_v203_release_hardening.mjs',classification:'tests'}])assert.equal(tierFor(f),1);assert.equal(tierFor({path:'scripts/test_other.mjs',classification:'tests'}),2);assert.equal(tierFor({path:'CHANGELOG_V1.md',classification:'documentation'}),3);});
test('first baseline has complete map and critical content without inventing universal direct review',()=>fixture(p=>{const a=buildPlan(p.root,p.target,options);assert.equal(a.plan.summary.criticalDirectPercent,100);assert.equal(a.manifest.analysis.completeEligibleLocalAnalysis,true);assert.equal(a.manifest.analysis.completeInventory,true);assert(a.manifest.files.some(f=>f.eligible&&!f.directSelected));assert.equal(a.plan.summary.cumulativeCompletedDirectFiles,0);assert.equal(a.plan.summary.neverDirectlyReviewed.length,a.plan.summary.eligible);assert.equal(a.plan.summary.cyclesUntilFullTier3Sweep,4);for(const f of a.manifest.files.filter(f=>f.eligible&&!f.directSelected)){assert.equal(f.ranges.length,0);assert.equal(f.coverageKind,'LOCAL_MAP_ONLY_ROTATION_SCHEDULED');}}));
test('changed ordinary map-only file receives complete direct content automatically',()=>fixture(p=>{const a=buildPlan(p.root,p.target,{...options,rotationPolicy:'E',rotationByteBudget:0}),name=a.manifest.files.find(f=>f.eligible&&!f.directSelected&&f.tier===3).path;p.write(name,'changed ordinary evidence');git(p.root,['add',name]);git(p.root,['commit','-qm','changed evidence']);const target=git(p.root,['rev-parse','HEAD']).trim(),b=buildPlan(p.root,target,{...options,directState:a.plan.options.directState,comparisonTarget:p.target}),f=b.manifest.files.find(f=>f.path===name);assert(f.directSelected);assert(f.selectionReasons.includes('CHANGED_SINCE_LAST_COMPLETED_TARGET'));assert.equal(b.plan.summary.changedDirectPercent,100);}));
test('deterministic Tier2/3 rotation, never-reviewed and overdue deadlines across eight audits',()=>fixture(p=>{const inv=inventory(p.root,p.target),analysis=analyzeRepository(inv,p.root,p.target);let state=initialDirectState(inv);const reviewed=new Map();for(let cycle=1;cycle<=8;cycle++){const a=selectDirect(inv,analysis,state),b=selectDirect(inv,analysis,state);assert.deepEqual([...a.reasons],[...b.reasons]);assert(a.overdue.every(p=>a.reasons.has(p)));for(const f of inv.files.filter(f=>f.eligible)){const period={1:1,2:2,3:4}[tierFor(f)];if(cycle>=period)assert(cycle-(reviewed.get(f.path)??0)<=period);if(a.reasons.has(f.path)){reviewed.set(f.path,cycle);state.files[f.path]={...state.files[f.path],lastAudit:cycle,lastRunId:'SIMULATED-'+cycle,lastDate:NOW,lastTarget:p.target,lastBlob:f.blob};}}state.completedAudits=cycle;if(cycle===4)assert.equal(reviewed.size,inv.files.filter(f=>f.eligible).length);}}));
test('overdue files are forced even outside their selected hash bucket',()=>fixture(p=>{const inv=inventory(p.root,p.target),state=initialDirectState(inv);state.completedAudits=10;const a=selectDirect(inv,analyzeRepository(inv,p.root,p.target),state);assert.equal(a.reasons.size,inv.files.filter(f=>f.eligible).length);assert.equal(a.overdue.length,a.reasons.size);}));
test('full explicit valid completion alone advances selected per-file ages',()=>fixture(async p=>{const r=p.save(),before=structuredClone(r.plan.options.directState),state={...initialize(p.target,NOW),directReview:before};const pass=r.plan.passes[0];await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target));assert.throws(()=>verifyCompletion(p.root,r.plan.runId),/INCOMPLETE/);assert.deepEqual(state.directReview,before);for(const x of r.plan.passes.slice(1))await runPass(p.root,r.plan.runId,x.id,sendOptions(r,x),deps(p.target));const verified=verifyCompletion(p.root,r.plan.runId);assert.throws(()=>completeCadence(state,verified,NOW,false));const next=completeCadence(state,verified,NOW,true);assert.equal(next.directReview.completedAudits,4);for(const f of verified.directCoverage.filter(f=>f.directSelected)){assert.equal(next.directReview.files[f.path].lastRunId,r.plan.runId);assert.equal(next.directReview.files[f.path].lastAudit,4);}assert.deepEqual(state.directReview,before);const stale={...state,directReview:{...before,completedAudits:4}};assert.throws(()=>completeCadence(stale,verified,NOW,true),/STALE/);}));
test('truncated audit never advances per-file direct-review state',()=>fixture(async p=>{const r=p.save(),state={...initialize(p.target,NOW),directReview:r.plan.options.directState},before=json(state),pass=r.plan.passes[0];const x=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,{stop_reason:'max_tokens'}));assert.equal(x.status,'TRUNCATED_RESPONSE');assert.throws(()=>verifyCompletion(p.root,r.plan.runId),/INCOMPLETE/);assert.equal(json(state),before);}));
test('map-only concern produces bounded actual-content escalation and needs separate paid authorization',()=>fixture(async p=>{const b=buildPlan(p.root,p.target,options),name=b.manifest.files.find(f=>f.eligible&&!f.directSelected).path;const e=buildPlan(p.root,p.target,{...options,directState:b.plan.options.directState,escalationPath:name,concern:'Reviewer suspects omitted temporal gate',parentRun:'PARENT'});assert.equal(e.plan.auditType,'ESCALATION');assert(e.plan.passes.some(p=>p.paths.includes(name)));assert([...e.packets.values()].every(t=>JSON.parse(t).exactReviewerConcern==='Reviewer suspects omitted temporal gate'));const r=createRun(p.root,e,initialize(p.target,NOW),NOW),pass=r.plan.passes[0],counts={keys:0,calls:0};await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,{},counts)),/SEPARATE_ESCALATION/);assert.deepEqual(counts,{keys:0,calls:0});for(const x of r.plan.passes)await runPass(p.root,r.plan.runId,x.id,sendOptions(r,x,{authorizeEscalation:true,escalationReason:'Owner explicitly approved this isolated concern'}),deps(p.target));assert.throws(()=>verifyCompletion(p.root,r.plan.runId),/ESCALATION/);}));
test('cost warning and explicit explained owner override protect over-ten spending',()=>{authorizeBudget(10);for(const o of [{},{budgetOverride:true},{budgetOverride:true,overrideReason:' '}])assert.throws(()=>authorizeBudget(10.0001,o),/OVERRIDE/);authorizeBudget(11,{budgetOverride:true,overrideReason:'Required critical coverage justified by owner'});assert.throws(()=>authorizeBudget(100,{budgetOverride:true,overrideReason:'Owner explanation'}),/EXTRAORDINARY/);authorizeBudget(100,{budgetOverride:true,overrideReason:'Extraordinary owner-approved investigation',extraordinaryAuthorization:true});});
test('over-budget preview retains content and warns instead of dropping selection',()=>fixture(p=>{const a=p.built(),b=buildPlan(p.root,p.target,{...a.plan.options,runId:'CHEAP',maxTotalUsd:0.001});assert.deepEqual(b.plan.passes.map(p=>p.paths),a.plan.passes.map(p=>p.paths));assert(b.plan.budgetWarnings.some(w=>w.includes('TOTAL GUARD')));}));
test('invalid direct-review history cannot excuse overdue selection',()=>fixture(p=>{const state=initialDirectState(inventory(p.root,p.target));state.files['README.md'].lastAudit=999;assert.throws(()=>buildPlan(p.root,p.target,{...options,directState:state}),/INVALID_PER_FILE/);}));

test('over-ten complete planned ceiling blocks before credentials without explained owner override',()=>fixture(async p=>{p.write('big-review.md','bounded synthetic fixture '.repeat(110000));git(p.root,['add','.']);git(p.root,['commit','-qm','synthetic large audit']);const target=git(p.root,['rev-parse','HEAD']).trim(),directState={...initialDirectState(inventory(p.root,target)),completedAudits:3},b=buildPlan(p.root,target,{rotationPolicy:'A',runId:'TEST-OVER-TEN',directState,maxTotalUsd:30});assert(b.plan.estimatedCeilingUsd>10);assert(b.plan.budgetWarnings.some(w=>w.includes('OVER $10')));const r=createRun(p.root,b,initialize(target,NOW),NOW),pass=r.plan.passes[0],counts={keys:0,calls:0};await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(target,{},counts)),/OVER_10/);await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass,{budgetOverride:true}),deps(target,{},counts)),/OVER_10/);assert.deepEqual(counts,{keys:0,calls:0});assert.equal(loadRun(p.root,r.plan.runId).state.passes[pass.id].attempts.length,0);}));

test('relative imports map dependencies, test consumers and normalized duplicate evidence locally',()=>fixture(p=>{p.write('scripts/test_dependent.mjs',"import '../model/source.js';\n");p.write('model/source.py','// model source\nexport const x = 1;\n');git(p.root,['add','.']);git(p.root,['commit','-qm','local mapping']);const inv=inventory(p.root,git(p.root,['rev-parse','HEAD']).trim()),a=analyzeRepository(inv,p.root,inv.target),test=a.entries.find(e=>e.path==='scripts/test_dependent.mjs'),model=a.entries.find(e=>e.path==='model/source.js');assert(test.dependencies.includes(model.id));assert(model.tests.includes(test.id));assert(model.parallelCandidates.length);assert(model.normalizedTextMatches.length);}));

test('superseded literal plans remain readable but paid sending is refused before key access',()=>fixture(async p=>{const r=createRun(p.root,legacyPlan(p.root,p.target,options),initialize(p.target,NOW),NOW),pass=r.plan.passes[0],counts={keys:0,calls:0};assert(loadRun(p.root,r.plan.runId));await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass,{budgetOverride:true,overrideReason:'This cannot revive superseded doctrine'}),deps(p.target,{},counts)),/SUPERSEDED_LITERAL/);assert.deepEqual(counts,{keys:0,calls:0});}));
test('completed baseline keeps map-only ages, and next incremental audit uses its exact target',()=>fixture(async p=>{const b=buildPlan(p.root,p.target,options),r=createRun(p.root,b,initialize(p.target,NOW),NOW);for(const pass of r.plan.passes)await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target));const state=completeCadence(initialize(p.target,NOW),verifyCompletion(p.root,r.plan.runId),NOW,true);assert.equal(state.directReview.completedAudits,1);const unseen=b.manifest.files.find(f=>f.eligible&&!f.directSelected);assert.equal(state.directReview.files[unseen.path].lastRunId,null);assert(state.directReview.files['model/source.js'].lastRunId);p.write(unseen.path,'new incremental signal');git(p.root,['add',unseen.path]);git(p.root,['commit','-qm','next target']);const target=git(p.root,['rev-parse','HEAD']).trim(),a=buildPlan(p.root,target,{...options,directState:state.directReview,comparisonTarget:state.lastCompletedDeepReview.main});assert.equal(a.plan.auditOrdinal,2);assert(a.manifest.files.find(f=>f.path===unseen.path).selectionReasons.includes('CHANGED_SINCE_LAST_COMPLETED_TARGET'));assert(a.plan.summary.cumulativeCompletedDirectFiles>0);assert.equal(a.plan.summary.changedDirectPercent,100);}));

// Economics optimization: prior safety tests remain intact.
test('deterministic pass-specific output budgets reserve structured findings and reasoning',()=>{const chunks=n=>Array.from({length:n},(_,i)=>({path:'source-'+i,text:'x'.repeat(10000)}));for(const theme of ['architecture','correctness','statistical','adversarial']){const a=outputBudget(theme,chunks(30)),b=outputBudget(theme,chunks(30));assert.deepEqual(a,b);assert(a.maxTokens>=4096&&a.maxTokens<=32768);assert(a.rationale.includes('reasoning'));}assert(outputBudget('statistical',chunks(80)).maxTokens>outputBudget('architecture',chunks(1)).maxTokens);assert.equal(outputBudget('adversarial',chunks(1),6144).maxTokens,6144);for(const n of [null,undefined])assert.equal(outputBudget('architecture',chunks(1),n).explicitOverride,undefined);for(const n of [255,32769,NaN,1.5])assert.throws(()=>outputBudget('architecture',[],n));});
test('cost decomposition exactly reconciles deterministic packet/input/output/cache ceilings',()=>fixture(p=>{const a=p.built(),b=costDecomposition(a.plan,a.packets);assert.deepEqual(b,costDecomposition(a.plan,a.packets));assert(Math.abs(b.equalityResidualUsd)<1e-9);assert(Math.abs(b.totals.totalCeilingUsd-a.plan.estimatedCeilingUsd)<1e-6);assert.equal(b.totals.duplicateLiteralBytes,0);assert.equal(b.totals.cacheReadUsd,0);assert(b.rows.every(r=>r.inputTokenProxy===r.packetBytes+Buffer.byteLength(DEEP_DOCTRINE)+4096));assert.equal(b.totals.outputReservationUsd,a.plan.passes.length*256*20/1e6);const broken=new Map(a.packets);broken.set(a.plan.passes[0].id,'bad');assert.throws(()=>costDecomposition(a.plan,broken),/COST_PACKET/);}));
test('map sparse encoding preserves zero-index relationships and all default metadata',()=>fixture(p=>{const inv=inventory(p.root,p.target),a=analyzeRepository(inv,p.root,p.target),state=initialDirectState(inv);a.entries[1].dependencies=[0];a.entries[1].tests=[0];const map=compactMap(inv,a,new Map(),state);assert.equal(map.rows.length,inv.files.length);assert.deepEqual(map.rows[1][8].d,[0]);assert.deepEqual(map.rows[1][8].t,[0]);assert.deepEqual(map.detailDefaults.m,[0,0,0,0]);for(const e of a.entries){const detail=map.rows[e.id][8];assert.deepEqual(detail.d??map.detailDefaults.d,e.dependencies);assert.deepEqual(detail.o??map.detailDefaults.o,e.owners);}}));
test('explicit baseline/routine modes and default target/warning/run/absolute budgets',()=>fixture(p=>{const a=buildPlan(p.root,p.target,options);assert.equal(a.plan.plannerMode,'BASELINE');assert.equal(p.built().plan.plannerMode,'ROUTINE');assert.equal(BUDGET_POLICY.targetUsd,8);assert.equal(BUDGET_POLICY.warningUsd,10);assert.equal(buildPlan(p.root,p.target).plan.maxTotalUsd,10);assert.equal(BUDGET_POLICY.absoluteToolMaximumUsd,200);assert.throws(()=>buildPlan(p.root,p.target,{...options,maxTotalUsd:201}),/INVALID_BUDGET/);assert.match(economicClassification('BASELINE',11,10).budgetClassification,/BASELINE PREMIUM/);assert.equal(economicClassification('ROUTINE',11,10).budgetClassification,'ROUTINE COST WARNING');assert.throws(()=>authorizeBudget(201,{budgetOverride:true,overrideReason:'Owner reason',extraordinaryAuthorization:true}),/ABSOLUTE/);}));
test('five-cycle simulation is deterministic, complete by audit four, and cannot create a paid run',()=>fixture(p=>{const state=initialDirectState(inventory(p.root,p.target)),before=json(state),moderateChange=['model/source.js','scripts/test_example.mjs','unknown.zz'],a=simulateFive(p.root,p.target,state,{moderateChange,options}),b=simulateFive(p.root,p.target,state,{moderateChange,options});assert.deepEqual(a,b);assert.equal(json(state),before);assert.equal(a.apiCalls,0);assert.equal(a.realHistoryWritten,false);assert.equal(a.rows.length,5);assert.equal(a.rows[0].plannerMode,'BASELINE');assert(a.rows.slice(1).every(r=>r.plannerMode==='ROUTINE'));assert.equal(a.rows[2].changedDirectPercent,100);assert(a.rows.every(r=>r.tier1Percent===100));assert(a.firstFullOrdinaryExposureAudit<=4);assert.equal(a.rows[3].neverReviewedAfter,0);assert.equal(a.rows[4].cumulativeDirectPercentAfter,100);const fake=buildPlan(p.root,p.target,{...options,directState:state,simulationOnly:true,simulatedChangedPaths:moderateChange});assert.throws(()=>createRun(p.root,fake,initialize(p.target,NOW),NOW),/SIMULATION/);assert.throws(()=>buildPlan(p.root,p.target,{...options,simulatedChangedPaths:moderateChange}),/SIMULATION_ONLY/);assert.throws(()=>buildPlan(p.root,p.target,{...options,simulationOnly:true,simulatedChangedPaths:['not-tracked']}),/INVALID_SIMULATED/);}));
test('risk-tier promotion applies immediately rather than waiting for the old cadence',()=>fixture(p=>{const inv=inventory(p.root,p.target),a=analyzeRepository(inv,p.root,p.target),state=initialDirectState(inv);state.completedAudits=1;const f=inv.files.find(f=>f.path==='unknown.zz');state.files[f.path]={...state.files[f.path],lastRunId:'SIMULATED-1',lastDate:NOW,lastTarget:p.target,lastBlob:f.blob,lastAudit:1};a.entries.find(e=>e.path===f.path).tier=2;const selected=selectDirect(inv,a,state);assert(selected.reasons.get(f.path).includes('RISK_TIER_PROMOTION'));a.entries.find(e=>e.path===f.path).tier=1;assert(selectDirect(inv,a,state).reasons.get(f.path).includes('TIER_1_CRITICAL_EVERY_AUDIT'));}));
test('new eligible file is changed, selected, and has no invented direct review',()=>fixture(p=>{const state=initialDirectState(inventory(p.root,p.target));state.completedAudits=1;p.write('new-ordinary.txt','New eligible fixture only');git(p.root,['add','new-ordinary.txt']);git(p.root,['commit','-qm','new file']);const target=git(p.root,['rev-parse','HEAD']).trim(),b=buildPlan(p.root,target,{...options,directState:state,comparisonTarget:p.target}),f=b.manifest.files.find(f=>f.path==='new-ordinary.txt');assert(f.directSelected);assert.equal(f.lastDirectReview,null);assert.equal(state.files[f.path],undefined);assert(f.selectionReasons.includes('CHANGED_SINCE_LAST_COMPLETED_TARGET'));}));
test('lower input floor states retained tier-interval economics without assuming cache hits',()=>fixture(p=>{const inv=inventory(p.root,p.target),floor=unavoidableInputFloor(inv);assert.equal(floor.originalBytesPerAudit,floor.tierBytes[1]+floor.tierBytes[2]/2+floor.tierBytes[3]/4);assert.equal(floor.minimumMeanInputUsd,floor.originalBytesPerAudit*4/1e6);assert(floor.meaning.includes('not an actual token'));}));
test('escalation preview exposes incremental costs/output and source concern without history advancement',()=>fixture(p=>{const b=buildPlan(p.root,p.target,{...options,escalationPath:'README.md',concern:'Specific suspicious contract from theme-architecture-001',parentRun:'REVIEWED-PARENT',sourcePass:'theme-architecture-001',findingId:'finding-1'});assert.equal(b.plan.plannerMode,'ESCALATION');assert.equal(b.plan.options.parentRun,'REVIEWED-PARENT');assert.equal(b.plan.escalationEstimate.sourcePass,'theme-architecture-001');assert.equal(b.plan.escalationEstimate.incrementalCeilingUsd,b.plan.estimatedCeilingUsd);assert.deepEqual(b.plan.escalationEstimate.requestedPaths,['README.md']);assert(b.plan.costDecomposition.rows.every(r=>r.maxTokens===256));assert(b.plan.passes.every(p=>p.outputBudget.rationale.includes('override')));assert.equal(b.plan.summary.cumulativeCompletedDirectFiles,0);assert.equal(b.plan.costDecomposition.totals.totalCeilingUsd,b.plan.estimatedCeilingUsd);}));
test('previous risk-rotation preview reconstructs unchanged without adopting new planner assumptions',()=>fixture(p=>{const b=riskPlanV2(p.root,p.target,options),r=createRun(p.root,b,initialize(p.target,NOW),NOW),restored=loadRun(p.root,r.plan.runId);assert.equal(restored.plan.policy,'force-risk-rotation-v2');assert.equal(restored.plan.passes[0].maxTokens,256);}));

test('routine historical-test context remains rotation-bound while active contracts stay direct',()=>fixture(p=>{p.write('scripts/test_catalog.json',JSON.stringify({tests:[{file:'test_example.mjs',suites:[],classification:'historical-fixture'},{file:'test_live.mjs',suites:['safe'],classification:'regression'}]}));p.write('scripts/test_example.mjs',"// references assets/app.js\n");p.write('scripts/test_live.mjs',"// references assets/app.js\n");git(p.root,['add','.']);git(p.root,['commit','-qm','execution contract fixture']);const target=git(p.root,['rev-parse','HEAD']).trim(),b=buildPlan(p.root,target,options),state={...b.plan.options.directState,completedAudits:1};const current=b.manifest.files.find(f=>f.path==='scripts/test_live.mjs'),historical=b.manifest.files.find(f=>f.path==='scripts/test_example.mjs');assert(current.selectionReasons.includes('DETERMINISTIC_DEPENDENCY_CONSUMER_TEST_CLOSURE'));assert(historical.selectionReasons.includes('DETERMINISTIC_DEPENDENCY_CONSUMER_TEST_CLOSURE'));const routine=buildPlan(p.root,target,{...options,directState:state,comparisonTarget:target});assert(routine.manifest.files.find(f=>f.path===current.path).selectionReasons.includes('DETERMINISTIC_DEPENDENCY_CONSUMER_TEST_CLOSURE'));const h=routine.manifest.files.find(f=>f.path===historical.path);assert(!h.selectionReasons.includes('DETERMINISTIC_DEPENDENCY_CONSUMER_TEST_CLOSURE'));assert(h.directSelected);assert(h.selectionReasons.includes('OVERDUE_DIRECT_REVIEW'));}));


 test('CLI omitted output cap reaches deterministic planner default without numeric coercion',async()=>{const {outputCapOption}=await import('../deep-review.mjs');assert.equal(outputCapOption(undefined),null);assert.equal(outputCapOption('6144'),6144);for(const value of ['0','NaN',''])assert.throws(()=>outputCapOption(value),/INVALID_NUMERIC/);});

// Revised SLA and implementer declarations: the prior 133 scenarios remain above.
import {pathToFileURL} from 'node:url';
import {syntheticDeclaration,syntheticRisk,validateDeclarations,DECLARATION_FIELDS} from './risks.mjs';
const declaration=(target,files,priority='UNCERTAIN',context=[])=>({...syntheticDeclaration(target,'LOCAL-RISK',[],[syntheticRisk('risk-1',files,priority,context)]),synthetic:false});
test('candidate SLA floors use actual bytes rather than counts',()=>{const inv={files:[{eligible:true,path:'model/x.js',classification:'model-statistical-source',bytes:1000},{eligible:true,path:'scripts/test_x.mjs',classification:'tests',bytes:4000},{eligible:true,path:'history.md',classification:'documentation',bytes:12000}]};assert.equal(unavoidableInputFloor(inv,POLICIES.A.periods).originalBytesPerAudit,6000);assert.equal(unavoidableInputFloor(inv,POLICIES.B.periods).originalBytesPerAudit,1000+4000/3+2000);assert.equal(unavoidableInputFloor(inv,POLICIES.C.periods).originalBytesPerAudit,3500);assert.equal(unavoidableInputFloor(inv,POLICIES.D.periods).originalBytesPerAudit,3000);assert.deepEqual(PERIOD,{1:1,2:4,3:12});});
test('default allocation derives original-byte throughput, not a dollar authorization',()=>fixture(p=>{const a=buildPlan(p.root,p.target,{...options,rotationPolicy:'E'}),s=a.plan.summary.rotationPolicyStats;assert.equal(s.normalSourceByteBudget,s.quietMandatoryBytes+Math.ceil(s.requiredQuietRotationMeanBytes));assert.equal(a.plan.maxTotalUsd,200);assert.equal(a.plan.options.rotationPolicy,'E');assert(a.plan.passes.length>=4);assert.equal(a.plan.summary.criticalDirectPercent,100);}));
test('hard overdue large and small files bypass a zero optional byte budget',()=>fixture(p=>{const inv=inventory(p.root,p.target),a=analyzeRepository(inv,p.root,p.target),state={...initialDirectState(inv),completedAudits:20},s=selectCurrent(inv,a,state,{rotationByteBudget:0});assert.equal(s.reasons.size,inv.files.filter(f=>f.eligible).length);assert(s.reasons.get('large.md').includes('OVERDUE_DIRECT_REVIEW'));assert(s.reasons.get('one-line.txt').includes('OVERDUE_DIRECT_REVIEW'));assertSelectionSla(inv,a,state,s);}));
test('overdue-removal mutation is detected by independent SLA assertion',()=>fixture(async p=>{const sourceFile=new URL('./selection.mjs',import.meta.url);let source=fs.readFileSync(sourceFile,'utf8');assert(source.includes('overdue=enforceOverdue(inv,analysis,state,periods,reasons,ordinal)'));source=source.replace('overdue=enforceOverdue(inv,analysis,state,periods,reasons,ordinal)','overdue=[]').replace(/from '(\.\.?\/[^']+)'/g,(_,r)=>'from '+JSON.stringify(new URL(r,sourceFile).href));const dest=path.join(p.root,'mutated-selection.mjs');fs.writeFileSync(dest,source);const mutant=await import(pathToFileURL(dest)),inv=inventory(p.root,p.target),a=analyzeRepository(inv,p.root,p.target),state={...initialDirectState(inv),completedAudits:20};assert.throws(()=>mutant.selectDirect(inv,a,state,{rotationByteBudget:0}),/SELECTION_SLA_VIOLATION/);}));
test('oversized highest-priority rotation head is not crowded out by tiny files',()=>fixture(p=>{const inv=inventory(p.root,p.target),a=analyzeRepository(inv,p.root,p.target),state=initialDirectState(inv);state.completedAudits=3;for(const f of inv.files.filter(f=>f.eligible))state.files[f.path]={...state.files[f.path],lastAudit:3,lastRunId:'HYPOTHETICAL',lastTarget:p.target,lastBlob:f.blob,lastDate:NOW};state.files['large.md']={...state.files['large.md'],lastAudit:null,lastRunId:null,lastTarget:null,lastBlob:null,lastDate:null};const s=selectCurrent(inv,a,state,{rotationPolicy:'E',rotationByteBudget:1});assert(s.reasons.get('large.md').includes('RISK_AGE_ROTATION_OVERSIZED_HEAD'));assert(s.stats.rotationBytes>1);}));
test('new eligible file is immediate and begins without fabricated history',()=>fixture(p=>{const state=initialDirectState(inventory(p.root,p.target));p.write('new-ordinary.md','new eligibility');git(p.root,['add','.']);git(p.root,['commit','-qm','new evidence']);const target=git(p.root,['rev-parse','HEAD']).trim(),b=buildPlan(p.root,target,{...options,rotationPolicy:'E',directState:state,comparisonTarget:p.target,rotationByteBudget:0}),f=b.manifest.files.find(f=>f.path==='new-ordinary.md');assert(f.directSelected);assert(f.selectionReasons.includes('NEW_ELIGIBLE_IMMEDIATE'));assert.equal(f.lastDirectReview,null);assert.equal(b.plan.summary.changedDirectPercent,100);}));
test('promotion tightens selection immediately before the old SLA is due',()=>fixture(p=>{const inv=inventory(p.root,p.target),a=analyzeRepository(inv,p.root,p.target),state=initialDirectState(inv);state.completedAudits=1;state.files['scripts/test_example.mjs']={...state.files['scripts/test_example.mjs'],tier:3,lastAudit:1,lastRunId:'H',lastTarget:p.target,lastBlob:inv.files.find(f=>f.path==='scripts/test_example.mjs').blob,lastDate:NOW};const s=selectCurrent(inv,a,state,{rotationByteBudget:0});assert(s.reasons.get('scripts/test_example.mjs').includes('RISK_TIER_PROMOTION'));}));
for(const priority of ['CRITICAL REVIEW','HIGH REVIEW','UNCERTAIN','REVIEW'])test('declared '+priority+' is additive mandatory direct content',()=>fixture(p=>{const base=buildPlan(p.root,p.target,{...options,rotationPolicy:'E',rotationByteBudget:0}),d=declaration(p.target,['one-line.txt'],priority),b=buildPlan(p.root,p.target,{...base.plan.options,runId:'DECLARED',riskDeclarations:[d]});assert(b.manifest.files.find(f=>f.path==='one-line.txt').directSelected);assert(b.plan.riskDeclaration.implementerFlaggedPaths.includes('one-line.txt'));for(const f of base.manifest.files.filter(f=>f.directSelected))assert(b.manifest.files.find(g=>g.path===f.path).directSelected);const adv=[...b.packets.values()].find(t=>JSON.parse(t).theme==='adversarial');assert.equal(JSON.parse(adv).implementerRiskDeclarations[0].risks[0].reviewPriority,priority);assert.match(JSON.parse(adv).independenceInstruction,/failed to identify/);assert.equal(b.plan.ownerOverrideRequired,b.plan.estimatedCeilingUsd>10);}));
test('uncertainty expands one-hop tests, callers, mirrors and explicit fixtures',()=>fixture(p=>{p.write('research/example/analyze.mjs',"import '../../model/source.js'; // scripts/fixtures/contract.json\n");git(p.root,['add','.']);git(p.root,['commit','-qm','uncertain dependency']);const target=git(p.root,['rev-parse','HEAD']).trim(),d=declaration(target,['research/example/analyze.mjs'],'UNCERTAIN',['scripts/test_example.mjs']),b=buildPlan(p.root,target,{...options,rotationPolicy:'E',riskDeclarations:[d]});for(const name of ['model/source.js','scripts/fixtures/contract.json','scripts/test_example.mjs'])assert(b.plan.riskDeclaration.implementerNeighborhoodPaths.includes(name));assert(b.plan.riskDeclaration.expansion.includes('No recursive'));}));
test('unflagged critical, changed and deterministic-risk files remain mandatory',()=>fixture(p=>{const state=initialDirectState(inventory(p.root,p.target));p.write('unknown.zz','changed ordinary');p.write('research/example/analyze.mjs','// TODO uncertain static source');git(p.root,['add','.']);git(p.root,['commit','-qm','independent controls']);const target=git(p.root,['rev-parse','HEAD']).trim(),d={...declaration(target,['one-line.txt']),baseSha:p.target,changedFiles:['research/example/analyze.mjs','unknown.zz']},b=buildPlan(p.root,target,{...options,rotationPolicy:'E',directState:state,comparisonTarget:p.target,riskDeclarations:[d],rotationByteBudget:0});for(const name of ['model/source.js','unknown.zz','research/example/analyze.mjs'])assert(b.manifest.files.find(f=>f.path===name).directSelected);assert.equal(b.plan.summary.changedDirectPercent,100);assert(b.plan.riskDeclaration.deterministicRiskPaths.includes('research/example/analyze.mjs'));assert(b.plan.riskDeclaration.independentlySelectedUnflagged.includes('unknown.zz'));}));
test('risk-driven spending is elevated and still refuses before credentials',()=>fixture(async p=>{p.write('research/large-risk.txt','x'.repeat(3000000));git(p.root,['add','.']);git(p.root,['commit','-qm','synthetic risk evidence']);const target=git(p.root,['rev-parse','HEAD']).trim(),state={...initialDirectState(inventory(p.root,target)),completedAudits:3},d=declaration(target,['research/large-risk.txt']),built=buildPlan(p.root,target,{runId:'ELEVATED-RISK',directState:state,rotationByteBudget:0,riskDeclarations:[d],maxTotalUsd:30});assert(built.plan.estimatedCeilingUsd>10);assert.equal(built.plan.reviewClass,'ELEVATED DEEP REVIEW — IMPLEMENTER RISK EXPANSION');const r=createRun(p.root,built,initialize(target,NOW),NOW),pass=r.plan.passes[0],counts={keys:0,calls:0};await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(target,{},counts)),/OVER_10/);assert.deepEqual(counts,{keys:0,calls:0});}));
test('missing declaration is surfaced and does not imply no risks',()=>fixture(p=>{const b=buildPlan(p.root,p.target,{...options,rotationPolicy:'E',substantiveIntegrations:[{id:'UNDISCLOSED'}]});assert.deepEqual(b.plan.riskDeclaration.missingRiskDeclarations,['UNDISCLOSED']);assert.match(b.plan.riskDeclaration.missingDeclarationStatus,/uncertainty, not no risks/);for(const text of b.packets.values())assert.deepEqual(JSON.parse(text).repoMap.implementerRiskCoverage.missingDeclarationIds,['UNDISCLOSED']);assert.equal(b.plan.summary.criticalDirectPercent,100);}));
test('risk schema rejects missing high-recall fields, invented paths and mismatched change lists',()=>fixture(p=>{const inv=inventory(p.root,p.target),d=declaration(p.target,['one-line.txt']);validateDeclarations(p.root,p.target,inv,[d]);for(const field of DECLARATION_FIELDS){const bad=structuredClone(d);delete bad[field];assert.throws(()=>validateDeclarations(p.root,p.target,inv,[bad]),/MANIFEST/);}const bad=structuredClone(d);bad.risks[0].files=['missing.js'];assert.throws(()=>validateDeclarations(p.root,p.target,inv,[bad]),/DECLARED_RISK/);assert.throws(()=>validateDeclarations(p.root,p.target,inv,[{...d,changedFiles:['README.md']}]),/CHANGED_FILES_MISMATCH/);}));
test('12-cycle simulation retains hard SLAs, all-file sweep, independence and private history',()=>fixture(p=>{const state=initialDirectState(inventory(p.root,p.target)),before=json(state),a=simulateTwelve(p.root,p.target,state,{moderateChange:['model/source.js','scripts/test_example.mjs','unknown.zz'],options}),b=simulateTwelve(p.root,p.target,state,{moderateChange:['model/source.js','scripts/test_example.mjs','unknown.zz'],options});assert.deepEqual(a,b);assert.equal(a.rows.length,12);assert(a.firstFullSweepAudit<=12);assert.equal(a.rows.at(-1).neverReviewedAfter,0);assert(a.rows.every(r=>r.tier1Percent===100&&r.overdueAfterCompletion===0&&r.escalationCalls===0));assert(a.rows.filter(r=>r.changedPaths.length).every(r=>r.changedDirectPercent===100&&r.riskDelta));assert.equal(a.rows[5].classification,'ELEVATED / MANDATORY');assert.equal(json(state),before);assert.equal(a.apiCalls,0);assert.equal(a.realHistoryWritten,false);assert(a.rows[0].selectionStats.rotationOnlyPaths.length>0);assert(a.rows.filter(r=>r.riskDelta).every(r=>Number.isFinite(r.riskDelta.incrementalCeilingUsd)));}));
test('policy-v3 preview remains exactly reconstructible and cannot authorize paid sending',()=>fixture(async p=>{const {buildPlan:old}=await import('./risk-plan-v3.mjs'),r=createRun(p.root,old(p.root,p.target,options),initialize(p.target,NOW),NOW);assert.equal(loadRun(p.root,r.plan.runId).plan.policy,'force-risk-rotation-v3');const pass=r.plan.passes[0],counts={keys:0,calls:0};await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,{},counts)),/SUPERSEDED/);assert.deepEqual(counts,{keys:0,calls:0});}));
 test('substantive cadence events surface missing implementer declarations without suppressing due state',()=>{const s=events(completedState(),1),e=evaluate(s,NOW);assert.deepEqual(e.missingRiskDeclarationIds,['I-1']);assert.equal(e.confirmedSubstantiveIntegrations,1);});

import {SELF_CHALLENGE_FIELDS,REVIEW_PRIORITIES} from '../self-challenge.mjs';
test('deep declaration carries standing self-challenge without changing independent mandatory selection',()=>fixture(async p=>{const {RISK_PRIORITIES}=await import('./risks.mjs');assert.equal(RISK_PRIORITIES,REVIEW_PRIORITIES);const d=declaration(p.target,['one-line.txt'],'UNCERTAIN');d.selfChallenge={...Object.fromEntries(SELF_CHALLENGE_FIELDS.map(k=>[k,'Synthetic '+k])),reviewPriority:'UNCERTAIN'};const inv=inventory(p.root,p.target);assert(!validateDeclarations(p.root,p.target,inv,[d]).warning.includes('MISSING'));const b=buildPlan(p.root,p.target,{...options,riskDeclarations:[d]}),a=buildPlan(p.root,p.target,options);for(const f of a.manifest.files.filter(f=>f.directSelected))assert(b.manifest.files.find(g=>g.path===f.path).directSelected);assert(b.manifest.files.find(f=>f.path==='one-line.txt').directSelected);const adv=[...b.packets.values()].find(t=>JSON.parse(t).theme==='adversarial');assert.equal(JSON.parse(adv).implementerRiskDeclarations[0].selfChallenge.reviewPriority,'UNCERTAIN');d.selfChallenge={};assert.match(validateDeclarations(p.root,p.target,inv,[d]).warning,/MISSING IMPLEMENTER SELF-CHALLENGE/);}));

// Bounded post-Opus infrastructure corrections; every paid-looking request below is a mock.
import {contextAdmission} from '../context.mjs';
import {CONFIG} from '../config.mjs';
import {registeredDeclarations,declarationHash} from './risks.mjs';
import {integrationAncestry} from './cadence.mjs';
import {withLock} from './util.mjs';
import {costDrivers} from './drivers.mjs';
import {rotationCompare} from './selection.mjs';
import {simulateScenario,representativeChanges,scenarioCycle,SCENARIOS} from './simulation.mjs';
import {verifyPlanTarget} from './run.mjs';
for(const change of ['unchanged','whitespace','removed','priority','path','context','key-order'])test('registered risk integrity '+change,()=>fixture(p=>{const d=declaration(p.target,['one-line.txt'],'UNCERTAIN',['README.md']),name='research/claude-api-reviews/registered.json',event={id:d.integrationId,classification:'SUBSTANTIVE',riskManifest:name,riskDeclarationHash:declarationHash(d)};const modified=structuredClone(d);if(change==='removed')modified.risks=[];if(change==='priority')modified.risks[0].reviewPriority='REVIEW';if(change==='path')modified.risks[0].files=['README.md'];if(change==='context')modified.risks[0].recommendedContext=[];const value=change==='key-order'?Object.fromEntries(Object.entries(modified).reverse()):modified;p.write(name,JSON.stringify(value,null,change==='whitespace'?4:2));if(['unchanged','whitespace'].includes(change))assert.deepEqual(registeredDeclarations(p.root,[event]),[d]);else assert.throws(()=>registeredDeclarations(p.root,[event]),/RISK_DECLARATION_HASH_MISMATCH/);}));
test('context admission includes full system, suffix, framing and output at exact boundary',()=>{const c=CONFIG.modelContext,output=16384,system=6000,n=c.contextTokens-c.framingReserveTokens-output-system;assert.equal(contextAdmission(n,output,system).remainingTokens,0);assert.equal(contextAdmission(n-1,output,system).remainingTokens,1);assert.throws(()=>contextAdmission(n+1,output,system),/MODEL_CONTEXT_WINDOW_EXCEEDED/);assert.throws(()=>contextAdmission(10,10,10,{...CONFIG,model:'unknown-model'}),/MODEL_CONTEXT_LIMIT_UNVERIFIED/);assert.throws(()=>contextAdmission(10,10,10,{...CONFIG,modelContext:null}),/MODEL_CONTEXT_LIMIT_UNVERIFIED/);for(const invalid of [NaN,-1,Infinity,1.5])assert.throws(()=>contextAdmission(invalid,output,system),/INVALID_CONTEXT_ESTIMATE/);});
test('production runtime remains pinned while unrelated negative guards are independently testable',()=>{const {plan,opts,fake}=environmentFixture('dirty');assert.throws(()=>verifySendEnvironment('.',plan,opts,{git:fake,nodeVersion:'22.0.0'}),/PINNED_NODE_24_19_0_REQUIRED/);assert.throws(()=>verifySendEnvironment('.',plan,opts,{git:fake,nodeVersion:'24.19.0'}),/CLEAN_TOOLING_WORKTREE_REQUIRED/);});
test('environment guard mutation disabling dirty-worktree detection is caught',()=>fixture(async p=>{const file=new URL('./run.mjs',import.meta.url);let code=fs.readFileSync(file,'utf8');const anchor="fail(inspect(root,['status','--porcelain','--untracked-files=normal']).trim()==='','CLEAN_TOOLING_WORKTREE_REQUIRED')";assert(code.includes(anchor));code=code.replace(anchor,'void 0').replace(/from '(\.\.?\/[^']+)'/g,(_,v)=>'from '+JSON.stringify(new URL(v,file).href));const name=path.join(p.root,'mutated-environment.mjs');fs.writeFileSync(name,code);const mutant=await import(pathToFileURL(name)),{plan,opts,fake}=environmentFixture('dirty');assert.throws(()=>assert.throws(()=>mutant.verifySendEnvironment('.',plan,opts,{git:fake,nodeVersion:'24.19.0'}),/CLEAN_TOOLING_WORKTREE_REQUIRED/),/Missing expected exception/);}));
test('plan pins current main but send permits immutable ancestor target after main advances',()=>{const {plan,opts,fake}=environmentFixture('ok',true);assert.throws(()=>verifyPlanTarget('.',TARGET,{git:fake}),/TARGET_MAIN_MOVED_AT_PLAN/);const state=verifySendEnvironment('.',plan,opts,{git:fake,nodeVersion:'24.19.0'});assert(state.mainAdvanced);assert.equal(state.target,TARGET);assert.match(state.message,/CURRENT MAIN ADVANCED — REVIEW REMAINS PINNED TO/);assert.equal(verifyPlanTarget('.',TARGET,{git:environmentFixture().fake}),TARGET);});
test('paid mock audit finishes pinned target after main advances; newer event remains outstanding',()=>fixture(async p=>{const r=p.save(),counts={keys:0,calls:0};for(const pass of r.plan.passes)await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),{...deps(p.target,{},counts),environmentVerifier:()=>({mainAdvanced:true,target:p.target,message:'CURRENT MAIN ADVANCED — REVIEW REMAINS PINNED TO '+p.target}),notify:()=>{}});p.write('newer.txt','newer main event');git(p.root,['add','.']);git(p.root,['commit','-qm','newer main']);const newer=git(p.root,['rev-parse','HEAD']).trim();let state={...initialize(p.target,'2026-10-01T12:00:00.000Z'),directReview:r.plan.options.directState};state=recordIntegration(state,{id:'LATER',previousMain:p.target,main:newer,time:'2026-10-02T12:00:00.000Z',title:'Synthetic later integration',classification:'SUBSTANTIVE',rationale:'Must remain unreviewed',tags:['HISTORICAL']},NOW);const next=completeCadence(state,verifyCompletion(p.root,r.plan.runId),NOW,true,{isAncestor:(e,t)=>integrationAncestry(p.root,e,t)});assert.equal(next.lastCompletedDeepReview.main,p.target);assert.equal(next.integrations[0].main,newer);assert(next.triggers[0].active);assert.equal(next.completionHistory[0].coveredIntegrations.length,0);assert.equal(counts.calls,r.plan.passes.length);}));
test('completion ancestry wins over late registration timestamps and rejects missing/unrelated objects',()=>fixture(p=>{p.write('next.md','included');git(p.root,['add','.']);git(p.root,['commit','-qm','included target']);const target=git(p.root,['rev-parse','HEAD']).trim(),event={id:'INCLUDED',previousMain:p.target,main:target,time:'2026-10-08T11:00:00.000Z',title:'Late-recorded included event',classification:'SUBSTANTIVE',rationale:'Ancestry wins',tags:['HISTORICAL']};let state=recordIntegration(initialize(p.target,'2026-10-01T12:00:00.000Z'),event,NOW);const verified={verifiedComplete:true,apiCalls:1,passes:1,runId:'PINNED',target,createdAt:'2026-10-02T12:00:00.000Z',manifestHash:'2'.repeat(64),toolingHead:TARGET};const next=completeCadence(state,verified,NOW,true,{isAncestor:(e,t)=>integrationAncestry(p.root,e,t)});assert.equal(next.integrations.length,0);assert(!next.triggers[0].active);assert.throws(()=>completeCadence(state,verified,NOW,true),/ANCESTRY_VERIFIER_REQUIRED/);assert.throws(()=>integrationAncestry(p.root,{...event,main:'0'.repeat(40)},target),/SHA_UNAVAILABLE/);git(p.root,['checkout','--orphan','unrelated']);git(p.root,['rm','-rf','.']);p.write('unrelated.txt','orphan');git(p.root,['add','.']);git(p.root,['commit','-qm','unrelated']);const unrelated=git(p.root,['rev-parse','HEAD']).trim();assert.throws(()=>integrationAncestry(p.root,event,unrelated),/TOPOLOGY_AMBIGUOUS/);}));
const driverFile=(bytes,reasons,tier=3)=>({bytes,tier,directSelected:true,selectionReasons:reasons});
for(const [name,files,expected,trigger]of [['deadline tiny risk',[driverFile(10000,['OVERDUE_DIRECT_REVIEW']),driverFile(10,['IMPLEMENTER_DECLARED_RISK: x'])],'OVERDUE_ROTATION',false],['risk heavy',[driverFile(10000,['IMPLEMENTER_DECLARED_RISK: x']),driverFile(10,['OVERDUE_DIRECT_REVIEW'])],'IMPLEMENTER_RISK',false],['changed heavy',[driverFile(10000,['CHANGED_SINCE_LAST_COMPLETED_TARGET']),driverFile(10,['IMPLEMENTER_DECLARED_RISK: x'])],'CHANGED_CONTENT',false],['mandatory trigger',[driverFile(10000,['CHANGED_SINCE_LAST_COMPLETED_TARGET'])],'CHANGED_CONTENT',true],['mixed',[driverFile(300,['LOCAL_TRUST']),driverFile(200,['OVERDUE_DIRECT_REVIEW']),driverFile(100,['IMPLEMENTER_RISK_CONTEXT: x'])],'STATIC_RISK',false]])test('cost drivers '+name,()=>{const result=costDrivers(files,{mandatoryTrigger:trigger});assert.equal(result.primaryDriver,expected);assert.equal(Object.values(result.byDriver).reduce((n,d)=>n+d.exclusiveOriginalBytes,0),result.selectedOriginalBytes);assert.equal(result.allMaterialDrivers.includes('MANDATORY_TRIGGER'),trigger);assert(Object.values(result.byDriver).every(d=>d.incrementalCeilingUsd===null));});
test('optional rotation order is never/age/hash, not path order, and reproducible for oversized heads',()=>{const state={files:{a:{lastAudit:8},z:{lastAudit:null},m:{lastAudit:2}}},periods={2:4,3:12},list=[{path:'a',tier:3},{path:'z',tier:3},{path:'m',tier:3}];assert.deepEqual([...list].sort(rotationCompare(state,periods,10,TARGET)).map(f=>f.path),['z','m','a']);assert.deepEqual([...list].reverse().sort(rotationCompare(state,periods,10,TARGET)).map(f=>f.path),['z','m','a']);assert.notDeepEqual([...list].sort(rotationCompare(state,periods,10,TARGET,'PATH_REFERENCE')).map(f=>f.path),['z','m','a']);});
test('scenario design changes every/most audits, preserves quiet reference and adds burst',()=>fixture(p=>{const inv=inventory(p.root,p.target),baskets=representativeChanges(inv),elevated=['model/source.js'];for(const scenario of SCENARIOS){const rows=Array.from({length:12},(_,i)=>scenarioCycle(scenario,i+1,baskets,elevated));const n=rows.filter(r=>r.changed.length).length;if(scenario==='CHANGE_EVERY')assert.equal(n,11);if(scenario==='CHANGE_MOST')assert.equal(n,8);if(scenario==='QUIET_REFERENCE')assert.equal(n,3);if(scenario==='BURSTY')assert(rows[5].mandatoryTrigger&&n>6);assert.equal(rows[0].changed.length,0);}}));
test('change-heavy private simulations retain deadlines for D and E and do not modify initial ledger',()=>fixture(p=>{const state=initialDirectState(inventory(p.root,p.target)),snapshot=json(state);for(const policy of ['D','E']){const result=simulateScenario(p.root,p.target,state,{scenario:'CHANGE_EVERY',rotationPolicy:policy,cycles:12,options});assert(result.firstFullSweepAudit<=12);assert.equal(result.rows.filter(r=>r.changedPaths.length).length,11);assert(result.rows.every(r=>r.overdueAfterCompletion===0&&r.tier1Percent===100));assert.equal(result.apiCalls,0);assert.equal(json(state),snapshot);assert.equal(result.audit12.neverReviewedAfter,0);}}));
for(const mode of ['exists','open','write','callback','success'])test('lock error and cleanup '+mode,async()=>{const calls=[],io={openSync:()=>{calls.push('open');if(mode==='exists')throw Object.assign(Error(),{code:'EEXIST'});if(mode==='open')throw Object.assign(Error(),{code:'EACCES'});return 7;},writeSync:()=>{calls.push('write');if(mode==='write')throw Object.assign(Error(),{code:'ENOSPC'});},closeSync:fd=>{assert.equal(fd,7);calls.push('close');},unlinkSync:()=>{calls.push('unlink');}};if(mode==='exists')assert.throws(()=>withLock('synthetic',()=>{},io),/run lock exists/);else if(mode==='open')assert.throws(()=>withLock('synthetic',()=>{},io),/LOCK_OPEN_FAILED: EACCES/);else if(mode==='write'){assert.throws(()=>withLock('synthetic',()=>{},io),/LOCK_INITIALIZATION_FAILED: ENOSPC/);assert.deepEqual(calls,['open','write','close','unlink']);}else{const work=()=>{if(mode==='callback')throw Error('callback failure');return 42;};if(mode==='callback')await assert.rejects(withLock('synthetic',work,io),/callback failure/);else assert.equal(await withLock('synthetic',work,io),42);assert.deepEqual(calls,['open','write','close','unlink']);}});
test('budget guards derive canonical warning extraordinary and absolute limits',()=>{authorizeBudget(BUDGET_POLICY.warningUsd,{});assert.throws(()=>authorizeBudget(BUDGET_POLICY.warningUsd+.01),/OVER_10/);assert.throws(()=>authorizeBudget(BUDGET_POLICY.extraordinaryAuthorizationUsd,{budgetOverride:true,overrideReason:'Synthetic owner override'}),/EXTRAORDINARY/);assert.throws(()=>authorizeBudget(BUDGET_POLICY.absoluteToolMaximumUsd+1),/ABSOLUTE/);});
