import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {git,hash,json,atomic} from './util.mjs';
import {inventory,EXCLUSIONS,classify,THEMES} from './inventory.mjs';
import {buildPlan,chunkBuffer,validateCoverage,HARD_LIMIT} from './plan.mjs';
import {initialize,evaluate,refresh,recordIntegration,classifyIntegration,recordTrigger,clearTrigger,completeCadence,TRIGGERS,chicagoDate} from './cadence.mjs';
import {createRun,loadRun,status,runPass,verifyCompletion,ownerScripts,verifySendEnvironment} from './run.mjs';
import {synthesize} from './synthesis.mjs';
import {DEEP_DOCTRINE,parseDeepReview,NATURES} from './doctrine.mjs';
import {parseArgs} from '../deep-review.mjs';
import {SYSTEM} from '../client.mjs';
const TARGET='1'.repeat(40),NOW='2026-10-08T12:00:00.000Z';
const options={runId:'TEST-DEEP-001',chunkBytes:256,coverageBytes:12288,themeBytes:24576,maxTokens:256,maxUsd:5,maxTotalUsd:200};
async function fixture(fn){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'force-deep-test-'));
 try{git(root,['init','-q']);git(root,['config','user.name','Disposable mock']);git(root,['config','user.email','mock@example.invalid']);git(root,['config','core.autocrlf','false']);
  const write=(name,value)=>{const p=path.join(root,name);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,value);};
  const source='// model source\r\nexport const x=1;\r\n';
  for(const [p,s]of Object.entries({'.gitignore':'research/claude-api-reviews/\n','model/source.js':source,'assets/app.js':source,'README.md':'# human methodology\n','unknown.zz':'unknown but readable\n','scripts/test_example.mjs':'// negative control source\n','scripts/run_tests.mjs':'// runner\n','scripts/test_catalog.json':'{}\n','scripts/build_public.py':'# build\n','Dockerfile':'FROM pinned\n','force_server.py':'# source\n','data/seed.js':'export const data={};\n','public/model/source.js':source,'research/example/analyze.mjs':'// generator\n','research/example/results/data.json':'{"a":1}\n','research/example/inputs.json':'{"method":"identity"}\n','scripts/fixtures/contract.json':'{"required":"input"}\n','research/example/fixtures/pop.csv':'team,value\nA,2\n','data/live-cache/cache.json':'{"payload":1}\n','vendor/upstream.js':'// third-party\n'}))write(p,s);
  write('image.png',Buffer.from([0,2,3]));write('odd.bin',Buffer.from([255,254]));write('large.md',('LONG UTF8 αβ🌟\r\n').repeat(1000));write('one-line.txt','🧪'.repeat(1000));
  git(root,['add','.']);git(root,['commit','-qm','target']);const target=git(root,['rev-parse','HEAD']).trim();git(root,['branch','-m','analysis']);
  const built=()=>buildPlan(root,target,options),save=()=>{const b=built();return createRun(root,b,initialize(target,NOW),NOW);};await fn({root,target,write,built,save});
 }finally{assert(root.startsWith(path.join(os.tmpdir(),'force-deep-test-')));fs.rmSync(root,{recursive:true,force:true});}
}
function completedState(time='2026-10-01T12:00:00.000Z'){return completeCadence(initialize(TARGET,time),{verifiedComplete:true,apiCalls:1,passes:1,runId:'PAID-BASELINE',target:TARGET,createdAt:time,manifestHash:'2'.repeat(64),toolingHead:TARGET},time,true);}
function events(s,n,classification='SUBSTANTIVE'){for(let i=0;i<n;i++){const previousMain=s.integrations.at(-1)?.main??TARGET;s=recordIntegration(s,{id:'I-'+(s.integrations.length+1),time:'2026-10-02T12:00:00.000Z',main:(s.integrations.length+2).toString(16).padStart(40,'0'),previousMain,title:'Owner-authorized integration',classification,rationale:'Behavioral contract changed',tags:[]},NOW);}return s;}
function outcome(target,findings=[]){return {verdict:findings.some(f=>f.severity==='MINOR')?'ACCEPTED WITH MINORS':'ACCEPTED',summary:'Independent mocked review',findings,limitations:['Mock only'],scope:{start_sha:target,end_sha:target}};}
function finding(p,nature='ACTUAL DEFECT',severity='MINOR',evidence='specific observed source evidence'){return {severity,nature,affected_paths:[p],location:p+':1',evidence,impact:'Concrete contract risk',correction:'Bounded verification',confidence:'HIGH'};}
const mockKey='mock-'+'k'.repeat(40);
function deps(target,change={},counts={keys:0,calls:0},custom){return {environmentVerifier:()=>{},secretLoader:()=>{counts.keys++;return mockKey;},fetcher:async(_u,opt)=>{counts.calls++;const body=JSON.parse(opt.body);assert.equal(body.system[0].text,SYSTEM);assert(body.system[0].cache_control);assert.equal(body.system[1].text,DEEP_DOCTRINE);const raw={type:'message',id:'msg_mock',model:'claude-opus-5-5',stop_reason:'end_turn',content:[{type:'text',text:JSON.stringify(custom??outcome(target))}],usage:{input_tokens:100,output_tokens:50,cache_creation_input_tokens:0,cache_read_input_tokens:0},...change};return new Response(JSON.stringify(raw),{status:200,headers:{'request-id':'req_mock'}});}};}
function sendOptions(run,p,extra={}){return {send:true,toolingHead:run.plan.toolingHead,target:run.plan.target,manifestHash:run.plan.manifestHash,packetHash:p.packetSha256,maxUsd:5,maxTotalUsd:200,...extra};}

test('deterministic target Git inventory, post-target files never leak',()=>fixture(p=>{const a=p.built();p.write('post-target.js','POST_TARGET_SENTINEL');git(p.root,['add','.']);git(p.root,['commit','-qm','tooling after target']);p.write('README.md','DIRTY_WORKTREE_SENTINEL');const b=p.built();assert.equal(a.manifestText,b.manifestText);assert.deepEqual([...a.packets],[...b.packets]);assert(!b.manifest.files.some(f=>f.path==='post-target.js'));assert(![...b.packets.values()].some(s=>s.includes('DIRTY_WORKTREE_SENTINEL')));}));
for(const name of ['model/source.js','README.md','scripts/test_example.mjs','scripts/run_tests.mjs','scripts/test_catalog.json','Dockerfile','force_server.py','data/seed.js','research/example/analyze.mjs','research/example/inputs.json','scripts/fixtures/contract.json','large.md','one-line.txt'])test('actual content eligible: '+name,()=>fixture(p=>{const f=p.built().manifest.files.find(f=>f.path===name);assert(f.eligible);assert(f.ranges.length>0);}));
for(const [name,reason]of [['image.png','BINARY_MEDIA'],['odd.bin','BINARY_MEDIA'],['data/live-cache/cache.json','RAW_PROVIDER_CACHE'],['research/example/fixtures/pop.csv','FIXTURE_POPULATION'],['research/example/results/data.json','GENERATED_EVIDENCE'],['public/model/source.js','EXACT_PUBLIC_MIRROR'],['vendor/upstream.js','VENDORED_THIRD_PARTY']])test('explicit exclusion: '+reason+' '+name,()=>fixture(p=>{const f=p.built().manifest.files.find(f=>f.path===name);assert(!f.eligible);assert.equal(f.exclusionReason,reason);assert(EXCLUSIONS[reason]);}));
test('unknown readable files surface ambiguity and stay covered',()=>fixture(p=>{const f=p.built().manifest.files.find(f=>f.path==='unknown.zz');assert(f.ambiguity.length);assert(f.eligible);}));
test('unproven public mirror and generated evidence remain eligible',()=>fixture(p=>{p.write('public/model/source.js','different generated content');p.write('research/no-source/results/file.json','{}');git(p.root,['add','.']);git(p.root,['commit','-qm','different mirror']);const x=inventory(p.root,git(p.root,['rev-parse','HEAD']).trim());assert(x.files.find(f=>f.path==='public/model/source.js').eligible);assert(x.files.find(f=>f.path==='research/no-source/results/file.json').eligible);}));
test('symlink disposition is explicit and not followed',{skip:process.platform==='win32'},()=>fixture(p=>{fs.symlinkSync('../README.md',path.join(p.root,'model/link'));git(p.root,['add','.']);git(p.root,['commit','-qm','link']);const x=inventory(p.root,git(p.root,['rev-parse','HEAD']).trim());assert.equal(x.files.find(f=>f.path==='model/link').exclusionReason,'NONREGULAR_OBJECT');}));
test('credential-pattern planning refuses content without key lookup',()=>fixture(p=>{p.write('secret-example.txt','sk'+'-ant-'+ 'z'.repeat(30));git(p.root,['add','.']);git(p.root,['commit','-qm','synthetic credential']);assert.throws(()=>inventory(p.root,git(p.root,['rev-parse','HEAD']).trim()),/Credential-pattern/);}));
for(const [name,b]of [['CRLF',Buffer.from('a\r\nb\r\n')],['BOM',Buffer.from('\ufeffa\r\n')],['long UTF8 line',Buffer.from('🌟α'.repeat(100))],['empty',Buffer.alloc(0)],['long ascii',Buffer.from('q'.repeat(100))]])test('lossless deterministic splitting: '+name,()=>{const c=chunkBuffer(b,7);assert.deepEqual(c,chunkBuffer(b,7));assert(Buffer.concat(c.map(c=>Buffer.from(c.text))).equals(b));assert(c.every(c=>c.end-c.start<=7));});
test('every eligible byte covered, chunks assigned correctly across boundaries',()=>fixture(p=>{const a=p.built(),inv=inventory(p.root,p.target);assert(validateCoverage(a.manifest,a.packets,inv));assert(a.manifest.files.find(f=>f.path==='large.md').contentShards.length>1);for(const d of a.plan.passes){assert(d.packetBytes<= (d.kind==='CONTENT'?options.coverageBytes:options.themeBytes));assert(d.packetBytes<HARD_LIMIT-65536);assert.equal(hash(a.packets.get(d.id)),d.packetSha256);}assert.equal(a.plan.summary.uncoveredEligible,0);}));
for(const defect of ['missing-file','excluded-eligible','unknown-reason','coverage-gap','altered-chunk'])test('coverage checker catches '+defect,()=>fixture(p=>{const a=p.built(),inv=inventory(p.root,p.target),m=structuredClone(a.manifest),packets=new Map(a.packets),f=m.files.find(f=>f.path==='README.md');if(defect==='missing-file')m.files.pop();if(defect==='excluded-eligible'){f.eligible=false;f.disposition='EXCLUDED';f.exclusionReason='too_large';}if(defect==='unknown-reason')m.files.find(f=>!f.eligible).exclusionReason='OTHER';if(defect==='coverage-gap')f.ranges[0].start++;if(defect==='altered-chunk'){const body=JSON.parse(packets.get(f.ranges[0].shard));body.content.find(c=>c.path===f.path).text='WRONG';packets.set(f.ranges[0].shard,json(body));}assert.throws(()=>validateCoverage(m,packets,inv));}));
test('all four themes have full inventory plus actual selected source, split with no truncation',()=>fixture(p=>{const a=p.built();for(const theme of THEMES){const ds=a.plan.passes.filter(p=>p.theme===theme.id);assert(ds.length);const wanted=a.manifest.files.filter(f=>f.eligible&&theme.select(f));for(const f of wanted){const chunks=ds.flatMap(d=>JSON.parse(a.packets.get(d.id)).content).filter(c=>c.path===f.path);assert(Buffer.concat(chunks.map(c=>Buffer.from(c.text))).equals(inventory(p.root,p.target).contents.get(f.path)));assert(f.thematicPasses.length);}for(const d of ds){const body=JSON.parse(a.packets.get(d.id));assert.equal(body.fullTrackedInventory.length,a.manifest.files.length);assert(body.sourceBackedArchitecture.length);}}}));
test('planning fails on overhead or budgets, never silently drops eligible content',()=>fixture(p=>{assert.throws(()=>buildPlan(p.root,p.target,{...options,themeBytes:8192}),/OVERHEAD|CHUNK/);assert.throws(()=>buildPlan(p.root,p.target,{...options,maxTotalUsd:0.00001}),/TOTAL_COST/);assert.throws(()=>buildPlan(p.root,p.target,{...options,maxUsd:0.00001}),/PER_CALL/);assert.throws(()=>buildPlan(p.root,p.target,{...options,themeBytes:HARD_LIMIT}),/MARGIN/);}));

test('bootstrap due honestly, no synthetic historical completion',()=>{const s=initialize(TARGET,NOW);assert.equal(s.lastCompletedDeepReview,null);assert.match(s.lastEvaluation.reasons[0],/INITIAL BASELINE/);});
test('five substantive integration events count independently of commit counts',()=>{assert.equal(evaluate(events(completedState(),4),'2026-10-03T12:00:00.000Z').status,'NOT DUE');assert.equal(evaluate(events(completedState(),5),'2026-10-03T12:00:00.000Z').status,'DEEP REVIEW DUE');});
test('housekeeping excluded, ambiguous threshold explicit, reclassification resolves',()=>{let s=events(completedState(),4);s=events(s,1,'AMBIGUOUS');s=events(s,2,'HOUSEKEEPING');const time='2026-10-03T12:00:00.000Z';assert.match(evaluate(s,time).status,/CADENCE AMBIGUOUS/);assert.equal(evaluate(classifyIntegration(s,'I-5','HOUSEKEEPING','Closeout only',NOW),time).status,'NOT DUE');assert.equal(evaluate(classifyIntegration(s,'I-5','SUBSTANTIVE','Behavioral gate',NOW),time).status,'DEEP REVIEW DUE');assert.equal(evaluate(s,NOW).status,'DEEP REVIEW DUE');});
test('seven Chicago calendar dates, not 168 hours; timezone crossing',()=>{const s=completedState('2026-10-01T23:30:00.000Z');assert.equal(evaluate(s,'2026-10-08T05:00:00.000Z').calendarDaysSinceCompletion,7);assert.equal(evaluate(s,'2026-10-08T04:59:59.000Z').status,'NOT DUE');assert.equal(chicagoDate('2026-10-08T04:00:00.000Z'),'2026-10-07');});
test('calendar cadence handles daylight saving independently of elapsed suppression',()=>{const s=completedState('2026-10-26T05:30:00.000Z');assert.equal(evaluate(s,'2026-11-02T06:00:00.000Z').calendarDaysSinceCompletion,7);assert.equal(chicagoDate('2026-11-01T06:30:00.000Z'),chicagoDate('2026-11-01T07:30:00.000Z'));});
test('routine suppressed for rolling elapsed 24h, exactly 24h allowed',()=>{let s=completedState('2026-10-02T11:00:00.000Z');s=events(s,5);assert.equal(evaluate(s,'2026-10-03T10:59:59.000Z').status,'NOT DUE');assert.equal(evaluate(s,'2026-10-03T11:00:00.000Z').status,'DEEP REVIEW DUE');});
for(const category of Object.keys(TRIGGERS))test('mandatory '+category+' bypasses routine suppression explicitly',()=>{const time='2026-10-08T13:00:00.000Z',s=recordTrigger(completedState(NOW),{id:'TRIGGER',category,rationale:'Explicit owner classified major architecture change',time},time),e=evaluate(s,time);assert.equal(e.status,'DEEP REVIEW DUE');assert.match(e.reasons[0],/MANDATORY.*<24H/);assert.equal(evaluate(clearTrigger(s,'TRIGGER','Owner cleared',time),time).status,'NOT DUE');});
test('unknown triggers, duplicate events and future events fail',()=>{assert.throws(()=>recordTrigger(completedState(),{id:'T',category:'UNKNOWN',rationale:'Unclassified',time:NOW},NOW));let s=events(completedState(),1);assert.throws(()=>recordIntegration(s,s.integrations[0],NOW),/DUPLICATE/);assert.throws(()=>evaluate(s,'2026-10-01T12:00:00.000Z'),/FUTURE/);});
test('completion resets covered events, retains integrations/triggers after reviewed snapshot',()=>{let s=events(completedState(),5);s=recordTrigger(s,{id:'NEW',category:'HISTORICAL',rationale:'New after snapshot',time:'2026-10-08T11:00:00.000Z'},NOW);const next=completeCadence(s,{verifiedComplete:true,apiCalls:2,passes:2,runId:'ALL-PASSES',target:TARGET,createdAt:'2026-10-03T12:00:00.000Z',manifestHash:'2'.repeat(64),toolingHead:TARGET},NOW,true);assert.equal(next.integrations.length,0);assert.equal(next.activeMandatoryTriggers.length,1);assert.equal(next.lastCompletedDeepReview.date,'2026-10-08');});
for(const bad of [{verifiedComplete:false},{verifiedComplete:true,apiCalls:0,passes:1},{verifiedComplete:true,apiCalls:1,passes:0}])test('dry/failed/incomplete cannot reset cadence '+JSON.stringify(bad),()=>{const s=initialize(TARGET,NOW);assert.throws(()=>completeCadence(s,bad,NOW,true));assert.equal(s.lastCompletedDeepReview,null);});
test('completion requires explicit confirmation and prevents duplicate run record',()=>{const s=initialize(TARGET,NOW),r={verifiedComplete:true,apiCalls:1,passes:1,runId:'R',target:TARGET,createdAt:NOW,manifestHash:'2'.repeat(64),toolingHead:TARGET};assert.throws(()=>completeCadence(s,r,NOW));const n=completeCadence(s,r,NOW,true);assert.throws(()=>completeCadence(n,r,NOW,true),/ALREADY/);});
test('run plan persistence and idempotent reconstruction, no overwrite',()=>fixture(p=>{const r=p.save();assert.deepEqual(loadRun(p.root,r.plan.runId).plan,r.plan);assert.throws(()=>p.save(),/RUN_ALREADY_EXISTS/);assert(status(r).pending.length);}));
for(const mode of [{},{send:false}])test('default/dry pass never reads key or requests '+JSON.stringify(mode),()=>fixture(async p=>{const r=p.save(),counts={keys:0,calls:0};const result=await runPass(p.root,r.plan.runId,r.plan.passes[0].id,mode,deps(p.target,{},counts));assert.equal(result.mode,'DRY_RUN');assert.deepEqual(counts,{keys:0,calls:0});assert.equal(loadRun(p.root,r.plan.runId).state.passes[r.plan.passes[0].id].status,'PENDING');assert.throws(()=>verifyCompletion(p.root,r.plan.runId),/INCOMPLETE/);}));
for(const [name,extra]of [['total',{maxTotalUsd:0.00001}],['per-call',{maxUsd:0.00001}],['packet-pin',{packetHash:'0'.repeat(64)}]])test(name+' guard before key/request',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],counts={keys:0,calls:0};await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass,extra),deps(p.target,{},counts)));assert.deepEqual(counts,{keys:0,calls:0});assert.equal(loadRun(p.root,r.plan.runId).state.passes[pass.id].attempts.length,0);}));
test('environment pins checked before key access and request intent',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],counts={keys:0,calls:0};await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),{...deps(p.target,{},counts),environmentVerifier:()=>{throw new Error('MAIN_MOVED');}}),/MAIN_MOVED/);assert.equal(counts.keys,0);}));
test('one send produces one request, complete pass cannot resend, resume omits completed',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],counts={keys:0,calls:0};const result=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,{},counts));assert.equal(result.status,'COMPLETED');assert.deepEqual(counts,{keys:1,calls:1});await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,{},counts)),/CANNOT_RESEND/);assert.equal(counts.calls,1);const resumed=loadRun(p.root,r.plan.runId);assert(!status(resumed).pending.includes(pass.id));assert.equal(status(resumed).rows.find(p=>p.id===pass.id).status,'COMPLETED');assert.throws(()=>verifyCompletion(p.root,r.plan.runId),/INCOMPLETE/);}));
for(const [label,change,want]of [['truncation',{stop_reason:'max_tokens'},'TRUNCATED_RESPONSE'],['wrong model',{model:'other-model'},'INVALID_RESPONSE'],['refusal',{stop_details:{type:'refusal'}},'INVALID_RESPONSE'],['wrong response schema',{type:'other'},'INVALID_RESPONSE']])test(label+' persists incomplete and does not auto retry',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],counts={keys:0,calls:0},result=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,change,counts));assert.equal(result.status,want);assert.equal(counts.calls,1);const next=loadRun(p.root,r.plan.runId);assert(status(next).ownerActionRequired.includes(pass.id));assert.throws(()=>verifyCompletion(p.root,r.plan.runId),/INCOMPLETE/);await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,{},counts)),/OWNER_ACTION_REQUIRED/);assert.equal(counts.calls,1);if(label==='truncation')assert.equal(result.telemetry.stopReason,'max_tokens');}));
test('network failure redacts exception, no automatic retry, explicit retry retained and budgeted',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],counts={keys:0,calls:0};const d=deps(p.target,{},counts);d.fetcher=async()=>{counts.calls++;throw new Error(mockKey);};const first=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),d);assert.equal(first.status,'REQUEST_FAILED');assert(!fs.readFileSync(path.join(r.dir,first.resultPath),'utf8').includes(mockKey));await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass,{retry:true,retryReason:'Owner checked failed attempt billing',maxTotalUsd:r.plan.estimatedCeilingUsd}),deps(p.target,{},counts)),/TOTAL_COST/);const second=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass,{retry:true,retryReason:'Explicit owner retry after billing inspection'}),deps(p.target,{},counts));assert.equal(second.status,'COMPLETED');assert.equal(loadRun(p.root,r.plan.runId).state.passes[pass.id].attempts.length,2);assert.equal(counts.calls,2);}));
test('missing secret safe result, zero requests; no plaintext persisted',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],counts={keys:0,calls:0},d=deps(p.target,{},counts);d.secretLoader=()=>{counts.keys++;throw new Error(mockKey);};const result=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),d);assert.equal(result.status,'REQUEST_FAILED');assert.equal(result.apiCalls,0);assert.equal(counts.calls,0);assert(!fs.readFileSync(path.join(r.dir,result.resultPath),'utf8').includes(mockKey));}));
test('unsafe reviewer content withheld with independently safe cost telemetry',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],v=outcome(p.target);v.summary=mockKey;const result=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,{},undefined,v));assert.equal(result.status,'INVALID_RESPONSE');const saved=JSON.parse(fs.readFileSync(path.join(r.dir,result.resultPath),'utf8'));assert.equal(saved.text,null);assert.equal(saved.review,null);assert.equal(saved.telemetry.requestId,'req_mock');assert(!json(saved).includes(mockKey));}));
test('intent saved before request; interrupted request requires owner action on restart',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],d=deps(p.target);const fetch=d.fetcher;d.fetcher=async(...args)=>{const s=JSON.parse(fs.readFileSync(path.join(r.dir,'run-state.json'),'utf8'));assert.equal(s.passes[pass.id].status,'OWNER_ACTION_REQUIRED');assert.equal(s.passes[pass.id].attempts[0].apiCalls,null);return fetch(...args);};await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),d);const state=loadRun(p.root,r.plan.runId).state;fs.unlinkSync(path.join(r.dir,state.passes[pass.id].resultPath));state.passes[pass.id]={status:'OWNER_ACTION_REQUIRED',resultPath:null,attempts:[{index:1,time:NOW,status:'OWNER_ACTION_REQUIRED',packetHash:pass.packetSha256,apiCalls:null,reservedUsd:pass.estimatedCeilingUsd}]};atomic(path.join(r.dir,'run-state.json'),state);await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target)),/OWNER_ACTION_REQUIRED/);}));
test('exclusive run lock refuses overlapping requests before key read',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],counts={keys:0,calls:0};fs.writeFileSync(path.join(r.dir,'run.lock'),'interrupted intent');await assert.rejects(runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target,{},counts)),/run lock/);assert.equal(counts.keys,0);}));
for(const name of ['coverage-manifest.json','plan.json','coverage-001.packet.json'])test('tamper refused before key/request: '+name,()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0];fs.appendFileSync(path.join(r.dir,name),' ');assert.throws(()=>loadRun(p.root,r.plan.runId),/MISMATCH|TAMPER/);}));
test('saved complete result cannot be replaced without integrity failure',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0],result=await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target));fs.appendFileSync(path.join(r.dir,result.resultPath),' ');assert.throws(()=>loadRun(p.root,r.plan.runId),/RESULT_TAMPER/);}));
test('run path traversal and output junction refused',()=>fixture(p=>{assert.throws(()=>loadRun(p.root,'../escape'),/INVALID_RUN_ID/);const target=path.join(p.root,'elsewhere');fs.mkdirSync(target);fs.mkdirSync(path.join(p.root,'research/claude-api-reviews'),{recursive:true});fs.symlinkSync(target,path.join(p.root,'research/claude-api-reviews/deep'),process.platform==='win32'?'junction':'dir');assert.throws(()=>p.save(),/SYMLINK/);assert.equal(fs.readdirSync(target).length,0);}));
test('local synthesis preserves raw IDs, groups duplicates vs corroboration, flags conflicts and incomplete',()=>fixture(async p=>{const r=p.save(),ps=r.plan.passes.slice(0,3);assert.equal(synthesize(p.root,r.plan.runId).complete,false);for(let i=0;i<ps.length;i++){const f=finding('model/source.js','ACTUAL DEFECT',i===2?'OPTIONAL':'MINOR',i===2?'Independent evidence with different classification':'specific observed source evidence');await runPass(p.root,r.plan.runId,ps[i].id,sendOptions(r,ps[i]),deps(p.target,{},undefined,outcome(p.target,[f])));}const summary=synthesize(p.root,r.plan.runId),report=JSON.parse(fs.readFileSync(summary.reportJSON,'utf8'));assert.equal(report.rawFindings.length,3);assert.equal(report.groups.length,1);assert.match(report.groups[0].relationship,/CORROBORATION/);assert(report.conflicts.length);assert.equal(report.complete,false);assert.equal(report.paidSynthesisCalls,0);assert(report.rawFindings.every(f=>f.passId&&f.id&&f.sourcePacketHash));}));
test('complete all valid passes then explicit cadence completion, not implied acceptance',()=>fixture(async p=>{const r=p.save();for(const pass of r.plan.passes)await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target));const verified=verifyCompletion(p.root,r.plan.runId);assert.equal(verified.passes,r.plan.passes.length);const state=initialize(p.target,NOW);assert.equal(state.lastCompletedDeepReview,null);const next=completeCadence(state,verified,'2026-10-08T15:00:00.000Z',true);assert.equal(next.lastCompletedDeepReview.main,p.target);assert.equal(synthesize(p.root,r.plan.runId).complete,true);}));
test('owner scripts pin HEAD/main/manifest/packet and contain exactly one send each; no send-all',()=>fixture(p=>{const r=p.save(),scripts=ownerScripts(p.root,r.plan.runId,process.execPath,path.join(p.root,'tooling/deep-review.mjs'));assert.equal(scripts.length,r.plan.passes.length);for(const [i,s]of scripts.entries()){const text=fs.readFileSync(s,'utf8');assert.equal((text.match(/--send/g)??[]).length,1);assert(text.includes(r.plan.toolingHead));assert(text.includes(r.plan.target));assert(text.includes(r.plan.manifestHash));assert(text.includes(r.plan.passes[i].packetSha256));assert(text.includes('--max-total-usd'));}assert(fs.existsSync(path.join(r.dir,'complete.ps1')));}));
for(const nature of NATURES)test('deep nature taxonomy: '+nature,()=>{const p={start:TARGET,end:TARGET,paths:['model/a.js']};assert.equal(parseDeepReview(json(outcome(TARGET,[finding('model/a.js',nature)])),p).findings[0].nature,nature);});
test('verdict/severity, exact scope and inventory path consistency remain enforced',()=>{const p={start:TARGET,end:TARGET,paths:['model/a.js']},v=outcome(TARGET,[finding('model/a.js')]);assert.throws(()=>parseDeepReview(json({...v,verdict:'ACCEPTED'}),p),/CONTRADICTION/);assert.throws(()=>parseDeepReview(json({...v,scope:{start_sha:TARGET,end_sha:'0'.repeat(40)}}),p),/SCOPE/);assert.throws(()=>parseDeepReview(json(v),{...p,paths:[]}),/OUTSIDE/);});
test('CLI has no implicit send or send-all; malformed flags fail closed',()=>{assert.equal(parseArgs([]).command,'status');assert(!parseArgs(['pass','--run','R','--pass','P']).values.send);assert.equal(parseArgs(['pass','--run','R','--pass','P','--send']).values.send,true);for(const a of [['send-all'],['pass','--send','--dry-run'],['pass','--send','--send'],['pass','--pass','A','B'],['plan','--send'],['status','--send']])assert.throws(()=>parseArgs(a));});

test('corrupted attempt ledger and orphaned result never permit a fresh paid request',()=>fixture(async p=>{const r=p.save(),pass=r.plan.passes[0];await runPass(p.root,r.plan.runId,pass.id,sendOptions(r,pass),deps(p.target));const st=loadRun(p.root,r.plan.runId).state;st.passes[pass.id]={status:'PENDING',resultPath:null,attempts:[]};atomic(path.join(r.dir,'run-state.json'),st);assert.throws(()=>loadRun(p.root,r.plan.runId),/ORPHANED_RESULT/);}));
test('invalid IDs and calendar timestamps do not coerce into canonical cadence state',()=>{for(const id of [null,undefined,[],{}])assert.throws(()=>recordTrigger(completedState(),{id,category:'HISTORICAL',rationale:'Owner classified',time:NOW},NOW));assert.throws(()=>initialize(TARGET,'2026-02-30T12:00:00Z'),/CALENDAR/);});
test('integration event chain and timestamp ordering must agree with owner-recorded main updates',()=>{const s=events(completedState(),1);assert.throws(()=>recordIntegration(s,{...s.integrations[0],id:'I-2',previousMain:'9'.repeat(40)},NOW),/CHAIN/);});


test('routine completion refused inside 24h; explicitly mandatory run remains permitted',()=>{const s=completedState(NOW),r={verifiedComplete:true,apiCalls:1,passes:1,runId:'SECOND-AUDIT',target:TARGET,createdAt:NOW,manifestHash:'2'.repeat(64),toolingHead:TARGET};assert.throws(()=>completeCadence(s,r,'2026-10-08T13:00:00.000Z',true),/SUPPRESSED/);assert(completeCadence(s,{...r,mandatoryReview:true},'2026-10-08T13:00:00.000Z',true).lastCompletedDeepReview);});
for(const variant of ['ok','head','dirty','main','local-main','tracking-main','remote-main','origin','pins'])test('pre-send environment '+variant+' independently checked',()=>{const plan={toolingHead:TARGET,target:TARGET,manifestHash:'2'.repeat(64)},opts={toolingHead:TARGET,target:TARGET,manifestHash:'2'.repeat(64)};if(variant==='pins')opts.manifestHash='3'.repeat(64);const fake=(_root,args)=>{const key=args.join(' ');if(key==='rev-parse HEAD')return variant==='head'?'0'.repeat(40):TARGET;if(key==='symbolic-ref --short HEAD')return variant==='main'?'main':'codex/tooling';if(key.startsWith('status '))return variant==='dirty'?' M changed.js':'';if(key==='rev-parse refs/heads/main')return variant==='local-main'?'0'.repeat(40):TARGET;if(key==='rev-parse refs/remotes/origin/main')return variant==='tracking-main'?'0'.repeat(40):TARGET;if(key==='remote get-url origin')return variant==='origin'?'https://github.com/other/repo.git':'https://github.com/pfoeller/force-nfl.git';if(key==='ls-remote origin refs/heads/main')return (variant==='remote-main'?'0'.repeat(40):TARGET)+'\trefs/heads/main';assert.fail('unexpected command '+key);};if(variant==='ok')verifySendEnvironment('.',plan,opts,{git:fake});else assert.throws(()=>verifySendEnvironment('.',plan,opts,{git:fake}));});
