import {fail} from './util.mjs';
import {CONFIG} from '../config.mjs';
import {SYSTEM,upperCost} from '../client.mjs';
import {DEEP_DOCTRINE} from './doctrine.mjs';
export const BUDGET_POLICY=Object.freeze({targetUsd:8,warningUsd:10,defaultRunBudgetUsd:10,absoluteToolMaximumUsd:200});
const bytes=v=>Buffer.byteLength(typeof v==='string'?v:JSON.stringify(v));
export function outputBudget(theme,chunks,override=null){
 const paths=new Set(chunks.map(c=>c.path)),evidenceBytes=chunks.reduce((n,c)=>n+bytes(c.text),0);
 if(override!==null&&override!==undefined){fail(Number.isInteger(override)&&override>=256&&override<=32768,'INVALID_OUTPUT_CAP');return {maxTokens:override,rationale:'Explicit owner/test override; supported range 256–32768. No completion on max_tokens.',explicitOverride:true};}
 const findingSlots=Math.min(12,Math.max(4,Math.ceil(paths.size/12)+Math.ceil(evidenceBytes/196608))),schemaEnvelope=512,tokensPerFinding=350,reasoningHeadroom=1536,themeHeadroom=['statistical','adversarial'].includes(theme)?512:0;
 const maxTokens=Math.max(4096,Math.ceil((schemaEnvelope+tokensPerFinding*findingSlots+reasoningHeadroom+themeHeadroom)/1024)*1024);
 return {maxTokens,findingSlots,schemaEnvelope,tokensPerFinding,reasoningHeadroom,themeHeadroom,paths:paths.size,evidenceBytes,rationale:'Bounded '+findingSlots+' detailed eight-field findings at 350 tokens each, 512 envelope/limitations, 1536 reasoning headroom'+(themeHeadroom?', 512 extra model/adversarial context':'')+'; rounded to 1024, minimum 4096. This planning allowance is not measured truncation performance; truncated responses stay incomplete.'};
}
export function costDecomposition(plan,packets){
 const seen=new Map(),p=CONFIG.pricing;
 const rows=plan.passes.map(pass=>{const text=packets.get(pass.id);fail(typeof text==='string'&&bytes(text)===pass.packetBytes,'COST_PACKET_BYTES_MISMATCH');const body=JSON.parse(text);let directContentBytes=0,duplicateLiteralBytes=0;for(const c of body.content){const n=bytes(c.text);directContentBytes+=n;const key=c.path+'|'+c.blob,prev=seen.get(key)??[];duplicateLiteralBytes+=prev.reduce((sum,r)=>sum+Math.max(0,Math.min(r.end,c.end)-Math.max(r.start,c.start)),0);prev.push({start:c.start,end:c.end});prev.sort((a,b)=>a.start-b.start);const merged=[];for(const r of prev){const last=merged.at(-1);if(last&&r.start<=last.end)last.end=Math.max(last.end,r.end);else merged.push({...r});}seen.set(key,merged);}
 const inputTokenProxy=pass.packetBytes+bytes(DEEP_DOCTRINE)+4096,cacheTokenProxy=bytes(SYSTEM)+4096,inputUsd=inputTokenProxy*p.input/1e6,outputReservationUsd=pass.maxTokens*p.output/1e6,cacheWriteUsd=cacheTokenProxy*p.cacheWrite5m/1e6,unrounded=inputUsd+outputReservationUsd+cacheWriteUsd;
 return {passId:pass.id,theme:pass.theme,packetBytes:pass.packetBytes,inputTokenProxy,directContentBytes,serializedContentBytes:bytes(body.content),commonMapBytes:bytes(body.repoMap),duplicateLiteralBytes,maxTokens:pass.maxTokens,outputBudget:pass.outputBudget??null,inputUsd,outputReservationUsd,cacheWriteUsd,cacheReadUsd:0,inputBufferUsd:4096*p.input/1e6,prefixBufferUsd:4096*p.cacheWrite5m/1e6,totalCeilingUsd:pass.estimatedCeilingUsd,roundingUsd:pass.estimatedCeilingUsd-unrounded};});
 const keys=['packetBytes','directContentBytes','serializedContentBytes','commonMapBytes','duplicateLiteralBytes','inputUsd','outputReservationUsd','cacheWriteUsd','cacheReadUsd','inputBufferUsd','prefixBufferUsd','roundingUsd','totalCeilingUsd'],totals=Object.fromEntries(keys.map(k=>[k,(k.endsWith('Usd')?Number(rows.reduce((n,r)=>n+r[k],0).toFixed(12)):rows.reduce((n,r)=>n+r[k],0))]));
 return {tokenProxy:'One UTF8 byte per token; 4096 input and 4096 stable-prefix buffers. Conservative proxy, not tokenizer output.',cacheAssumption:'Every call pays full stable-prefix 5m cache write; zero cache-read savings assumed; dynamic repo map is not cached.',otherReserves:'Input/prefix buffers already included in input/cache components; only upward microdollar rounding is additional.',rows,totals,repeatedMapBytes:Math.max(0,totals.commonMapBytes-(rows[0]?.commonMapBytes??0)),equalityResidualUsd:totals.totalCeilingUsd-(totals.inputUsd+totals.outputReservationUsd+totals.cacheWriteUsd+totals.roundingUsd)};
}
export function economicClassification(mode,total,guard){return {plannerMode:mode,budgetPolicy:BUDGET_POLICY,budgetClassification:total>10?(mode==='BASELINE'?'BASELINE PREMIUM — OWNER OVERRIDE REQUIRED':mode==='ESCALATION'?'ESCALATION COST WARNING — SEPARATE OWNER AUTHORIZATION REQUIRED':'ROUTINE COST WARNING'):'WITHIN WARNING THRESHOLD',ownerOverrideRequired:total>10,withinPreferredTarget:total<=8,withinConfiguredGuard:total<=guard};}
