import fs from 'node:fs';
import {guarded} from './util.mjs';
const registeredText=(root,p)=>fs.readFileSync(guarded(root,p),'utf8');
import {fail,SHA,git,hash,json} from './util.mjs';
import {REVIEW_PRIORITIES,assessSelfChallenge} from '../self-challenge.mjs';
export const declarationHash=d=>hash(json(d));
export function registeredDeclarations(root,events){return events.filter(e=>e.classification==='SUBSTANTIVE'&&e.riskManifest).map(e=>{const d=JSON.parse(registeredText(root,e.riskManifest));fail(typeof e.riskDeclarationHash==='string'&&declarationHash(d)===e.riskDeclarationHash,'RISK_DECLARATION_HASH_MISMATCH: '+e.id);return d;});}
export const RISK_PRIORITIES=REVIEW_PRIORITIES;
export const DECLARATION_FIELDS=Object.freeze(['changedFiles','affectedSubsystems','indirectConsumers','truthOwners','testsRun','testsNotRun','assumptions','invariants','unresolvedQuestions','shortcuts','compatibilityFallback','dataProviderSemantics','modelStatisticalSemantics','runtimeBuildDeploymentSemantics','parallelImplementations','staleContracts','lowConfidenceAreas']);
const text=v=>typeof v==='string'&&v.trim().length>0&&v.length<=10000;
const strings=v=>Array.isArray(v)&&v.length<=2000&&v.every(text)&&new Set(v).size===v.length;
export function validateDeclarations(root,target,inv,declarations=[],{simulationOnly=false,simulatedChangedPaths=[]}={}){
 fail(Array.isArray(declarations)&&declarations.length<=100,'INVALID_RISK_DECLARATIONS');const selfWarnings=[],paths=new Set(inv.files.map(f=>f.path)),eligible=new Set(inv.files.filter(f=>f.eligible).map(f=>f.path)),ids=new Set();
 for(const d of declarations){fail(d&&d.schema===1&&text(d.integrationId)&&!ids.has(d.integrationId)&&SHA.test(d.baseSha)&&SHA.test(d.resultSha)&&Array.isArray(d.risks),'INVALID_RISK_MANIFEST');ids.add(d.integrationId);if(Object.hasOwn(d,'selfChallenge')){const a=assessSelfChallenge({implementationClassification:'SUBSTANTIVE',selfChallenge:d.selfChallenge});if(a.missingFields.length)selfWarnings.push(d.integrationId+': '+a.status+' ['+a.missingFields.join(', ')+']');}for(const field of DECLARATION_FIELDS)fail(strings(d[field]),'INVALID_RISK_MANIFEST_FIELD: '+field);
  fail(d.indirectConsumers.every(p=>paths.has(p))&&d.truthOwners.every(p=>paths.has(p))&&d.parallelImplementations.every(p=>paths.has(p))&&d.staleContracts.every(p=>paths.has(p)),'RISK_DECLARATION_UNKNOWN_PATH');
  if(d.synthetic===true){fail(simulationOnly&&d.baseSha===target&&d.resultSha===target&&json([...d.changedFiles].sort())===json([...simulatedChangedPaths].sort()),'SYNTHETIC_RISK_ONLY_IN_MATCHING_SIMULATION');}
  else{fail(d.synthetic===undefined||d.synthetic===false,'INVALID_SYNTHETIC_RISK_FLAG');git(root,['merge-base','--is-ancestor',d.baseSha,d.resultSha]);git(root,['merge-base','--is-ancestor',d.resultSha,target]);const actual=git(root,['diff','--name-only','--no-renames',d.baseSha,d.resultSha]).trim().split('\n').filter(Boolean).sort();fail(json([...d.changedFiles].sort())===json(actual),'RISK_DECLARATION_CHANGED_FILES_MISMATCH');}
  const riskIds=new Set();for(const r of d.risks){fail(r&&text(r.riskId)&&!riskIds.has(r.riskId)&&strings(r.files)&&r.files.length>0&&r.files.every(p=>eligible.has(p))&&RISK_PRIORITIES.includes(r.reviewPriority),'INVALID_DECLARED_RISK');riskIds.add(r.riskId);for(const field of ['subsystem','category','explanation','potentialFailureMode','blastRadius'])fail(text(r[field]),'INVALID_DECLARED_RISK_FIELD: '+field);for(const field of ['recommendedContext','relevantTests','dependenciesConsumers'])fail(strings(r[field])&&r[field].every(p=>paths.has(p)),'INVALID_DECLARED_RISK_CONTEXT');for(const field of ['implementationConfidence','validationConfidence'])fail(['HIGH','MEDIUM','LOW','UNKNOWN'].includes(r[field]),'INVALID_RISK_CONFIDENCE');}
 }
 return {declarations,declarationHash:hash(json(declarations)),warning:'Implementer declarations are additive, not evidence that unflagged files are safe. UNCERTAIN is elevated. No declaration authorizes spending.'+(selfWarnings.length?' '+selfWarnings.join('; '):'')};
}
export function riskEvidence(analysis,inv,declarations,substantiveIntegrations=[]){
 fail(Array.isArray(substantiveIntegrations)&&substantiveIntegrations.every(e=>e&&text(e.id)),'INVALID_SUBSTANTIVE_INTEGRATION_LIST');const found=new Set(declarations.map(d=>d.integrationId)),missing=substantiveIntegrations.filter(e=>!found.has(e.id)).map(e=>e.id);const index=new Map(analysis.entries.map(e=>[e.path,e])),flags=new Map(),neighbors=new Map();
 for(const d of declarations)for(const r of d.risks)for(const p of r.files){const e=index.get(p),reason=d.integrationId+'/'+r.riskId+' ['+r.reviewPriority+']';if(!flags.has(p))flags.set(p,[]);flags.get(p).push(reason);const ids=new Set([...e.dependencies,...e.consumers,...e.tests,...e.parallelCandidates,...e.owners.map(p=>index.get(p)?.id).filter(i=>i!==undefined),...r.recommendedContext.concat(r.relevantTests,r.dependenciesConsumers).map(p=>index.get(p)?.id).filter(i=>i!==undefined)]);for(const id of ids){const f=inv.files[id];if(!f?.eligible||r.files.includes(f.path))continue;if(!neighbors.has(f.path))neighbors.set(f.path,[]);neighbors.get(f.path).push('ONE_HOP_FROM '+p+' via '+reason);}}
 return {flags,neighbors,missingRiskDeclarations:missing,missingDeclarationStatus:missing.length?'MISSING IMPLEMENTER RISK DECLARATION — uncertainty, not no risks':'NO KNOWN MISSING DECLARATIONS; absence of flags never establishes safety',expansion:'One declared root hop only; eligible direct callers/callees, tests, peers, truth owners and explicit bounded fixture/config/provider/state context. No recursive expansion.'};
}
export function syntheticDeclaration(target,id,changed,risks){return {schema:1,synthetic:true,integrationId:id,baseSha:target,resultSha:target,...Object.fromEntries(DECLARATION_FIELDS.map(f=>[f,f==='changedFiles'?[...changed]:f==='affectedSubsystems'?['Synthetic planner sizing only']:[]])),assumptions:['Current committed bytes size synthetic future change metadata; no actual product defect is asserted.'],invariants:['Critical/changed/static-risk/deadline coverage must survive additive declarations.'],risks};}
export function syntheticRisk(id,files,priority='UNCERTAIN',context=[]){return {riskId:id,files,subsystem:'SYNTHETIC PLANNER FIXTURE',category:'Uncertainty propagation fixture',explanation:'Synthetic potential interaction for testing selection, not a finding about production.',potentialFailureMode:'Independent reviewer might require additional actual-content context.',blastRadius:'Synthetic bounded dependency neighborhood',implementationConfidence:'UNKNOWN',validationConfidence:'UNKNOWN',reviewPriority:priority,recommendedContext:context,relevantTests:[],dependenciesConsumers:[]};}