import path from 'node:path';
import {hash,git,compare,fail} from './util.mjs';
export const REVIEW_POLICY='force-risk-rotation-v3';
export const PERIOD={1:1,2:2,3:4};
// Derive categories from the target tree and declared consumers, not a historical version list.
export function tierFor(f){
 const p=f.path;
 if(['model-statistical-source','server-runtime','config-build-deploy','provider-ingestion'].includes(f.classification)||p==='assets/app.js'||p==='index.html'||/^data\/(?:predictive-feature-gates|production-config|original-tuned-config)/.test(p)||/^scripts\/lib\/(?:test_safety|sitecustomize|current_version)/.test(p)||/^scripts\/test_(?:runtime|qb_correctness|md08_model_display_separation|v[0-9]+_release_hardening|v[0-9]+_public_refresh)/.test(p))return 1;
 if(['tests','test-infrastructure','production-data-contract','frontend','research-methodology-source','roadmap-governance','review-tooling','fixtures-snapshots'].includes(f.classification)||['README.md','model/README.md','DEPLOYMENT_STRUCTURE.md','PREDICTIVE_FEATURE_POLICY_V30.md'].includes(p))return 2;
 return 3;
}
function refs(text){return [...new Set([...text.matchAll(/(?:from\s*|require\(\s*|src=|import\s+)["']([^"'\n]+)["']/g)].map(m=>m[1]))].sort(compare);}
function pathsIn(text,paths){const result=[];for(const p of paths)if(text.includes(p)||p.startsWith('model/')&&text.includes(p.slice(6)))result.push(p);return result;}
export function analyzeRepository(inv,root,comparisonTarget){
 const paths=inv.files.map(f=>f.path),index=new Map(paths.map((p,i)=>[p,i])),changed=new Set();
 if(comparisonTarget&&comparisonTarget!==inv.target){git(root,['merge-base','--is-ancestor',comparisonTarget,inv.target]);for(const p of git(root,['diff','--name-only','--no-renames',comparisonTarget,inv.target]).trim().split('\n').filter(Boolean))changed.add(p);}
 let catalog={tests:[]};try{catalog=JSON.parse(inv.contents.get('scripts/test_catalog.json')?.toString('utf8')??'{\"tests\":[]}');}catch{throw new Error('INVALID_TARGET_TEST_CATALOG');}const testContracts=new Map((catalog.tests??[]).map(t=>['scripts/'+t.file,t]));const entries=inv.files.map((f,id)=>{const text=f.eligible?inv.contents.get(f.path).toString('utf8'):'',declared=refs(text),dependencies=[...new Set([...pathsIn(text,paths.filter(p=>p!==f.path)),...declared.filter(r=>r.startsWith('.')).map(r=>path.posix.normalize(path.posix.join(path.posix.dirname(f.path),r))).filter(p=>index.has(p)&&p!==f.path)])].sort(compare),markers={todo:(text.match(/\b(?:TODO|FIXME)\b/g)??[]).length,legacy:(text.match(/\b(?:legacy|deprecated|superseded)\b/gi)??[]).length,trustBoundary:(text.match(/\b(?:DPAPI|compare_digest|timingSafeEqual|authorization|csrf|cors|x-api-key)\b/gi)??[]).length,provider:(text.match(/\b(?:FTN|StatRankings|nflverse|PFR|fallback)\b/g)??[]).length};return {id,path:f.path,subsystem:f.path.includes('/')?f.path.split('/')[0]:'root',tier:f.eligible?tierFor(f):null,changed:changed.has(f.path),changeState:changed.has(f.path)?'CHANGED':'UNCHANGED_VS_ANCHOR',testContractState:f.classification==='tests'?(testContracts.get(f.path)?.suites?.length?'CURRENT_SELECTED':'HISTORICAL_EXCLUDED_OR_UNMAPPED'):null,testCatalogSuites:testContracts.get(f.path)?.suites??[],localAnalytic:f.eligible?'INSPECTED_DETERMINISTICALLY':'EXCLUDED_METADATA_ONLY',declaredReferences:declared,dependencies:dependencies.map(p=>index.get(p)),consumers:[],tests:[],owners:f.sourcePaths,markers,lineCount:text?text.split('\n').length:0,longestLineBytes:text?text.split('\n').reduce((m,s)=>Math.max(m,Buffer.byteLength(s)),0):0,parallelCandidates:[]};});
 for(const e of entries)for(const d of e.dependencies){entries[d].consumers.push(e.id);if(inv.files[e.id].classification==='tests')entries[d].tests.push(e.id);}
 for(const e of entries){const stem=e.path.replace(/\.(?:m?js|cjs|py)$/,'');e.parallelCandidates=entries.filter(o=>o.id!==e.id&&o.path.replace(/\.(?:m?js|cjs|py)$/,'')===stem).map(o=>o.id);}
 for(const e of entries){const f=inv.files[e.id];e.exactDuplicates=entries.filter(o=>o.id!==e.id&&inv.files[o.id].sha256===f.sha256).map(o=>o.id);e.normalizedTextFingerprint=f.eligible?hash(inv.contents.get(f.path).toString('utf8').replace(/\s+/g,'')):null;e.versionReferences=f.eligible?[...new Set((inv.contents.get(f.path).toString('utf8').match(/\bV\d{1,3}\b/g)??[]))].sort(compare):[];}for(const e of entries)e.normalizedTextMatches=e.normalizedTextFingerprint?entries.filter(o=>o.id!==e.id&&o.normalizedTextFingerprint===e.normalizedTextFingerprint).map(o=>o.id):[];return {schema:2,target:inv.target,comparisonTarget,comparisonMeaning:'Last completed audit target; for bootstrap use the explicitly unreviewed baseline anchor. UNCHANGED never implies reviewed.',completeInventory:entries.length===inv.files.length,completeEligibleLocalAnalysis:entries.filter(e=>e.localAnalytic==='INSPECTED_DETERMINISTICALLY').length===inv.files.filter(f=>f.eligible).length,entries};
}
export function compactMap(inv,analysis,selected,state){
 const classes=[...new Set(inv.files.map(f=>f.classification))].sort(compare),dirs=[...new Set(inv.files.map(f=>f.path.includes('/')?f.path.slice(0,f.path.lastIndexOf('/')):''))].sort(compare),exclusions=[...new Set(inv.files.map(f=>f.exclusionReason).filter(Boolean))].sort(compare);
 const rows=analysis.entries.map(e=>{const f=inv.files[e.id],dir=f.path.includes('/')?f.path.slice(0,f.path.lastIndexOf('/')):'',detail={};for(const [k,v]of Object.entries({d:e.dependencies,t:e.tests,p:e.parallelCandidates,u:e.exactDuplicates,n:e.normalizedTextMatches,o:e.owners,a:state.files[e.path]?.lastAudit,m:[e.markers.todo,e.markers.legacy,e.markers.trustBoundary,e.markers.provider],c:e.testContractState})){if(v!==null&&v!==undefined&&(!Array.isArray(v)||(k==='m'?v.some(x=>x!==0):v.length>0)))detail[k]=v;}return [e.id,dirs.indexOf(dir),f.path.split('/').at(-1),classes.indexOf(f.classification),f.eligible?e.tier:0,(e.changed?1:0)|(selected.has(f.path)?2:0),f.bytes,f.exclusionReason===null?-1:exclusions.indexOf(f.exclusionReason),detail];});
 return {schema:3,meaning:'Complete tracked inventory + LOCAL analytic map; only supplied content is direct review. Sparse encoding removes repeated empty metadata, not paths or relationships.',columns:['id','directory','filename','class','tier (0 excluded)','flags (1 changed, 2 direct-selected)','bytes','exclusion (-1 none)','sparse details'],detailKeys:{d:'dependency IDs',t:'test consumer IDs',p:'cross-language candidates',u:'exact duplicates',n:'whitespace-normalized matches, not semantic equivalence',o:'truth owners',a:'last completed direct audit',m:'TODO/legacy/trust/provider counts',c:'test catalog execution contract'},detailDefaults:{d:[],t:[],p:[],u:[],n:[],o:[],a:null,m:[0,0,0,0],c:null},directories:dirs,classes,exclusions,rows};
}
export function initialDirectState(inv){return {schema:1,baselineTarget:inv.target,completedAudits:0,files:Object.fromEntries(inv.files.filter(f=>f.eligible).map(f=>[f.path,{tier:tierFor(f),lastRunId:null,lastDate:null,lastTarget:null,lastBlob:null,lastAudit:null,passes:[],selectionReason:null,changedSinceLastReview:true}]))};}
export function selectDirect(inv,analysis,state,{escalationPath=null,concern=null}={}){
 fail(state?.schema===1&&Number.isInteger(state.completedAudits)&&state.completedAudits>=0&&/^[a-f0-9]{40}$/.test(state.baselineTarget)&&state.files&&typeof state.files==='object'&&!Array.isArray(state.files),'INVALID_DIRECT_REVIEW_STATE');for(const [p,f]of Object.entries(state.files)){fail(typeof p==='string'&&f&&[1,2,3].includes(f.tier)&&((f.lastAudit===null&&f.lastRunId===null)||(Number.isInteger(f.lastAudit)&&f.lastAudit>0&&f.lastAudit<=state.completedAudits&&typeof f.lastRunId==='string'&&/^[a-f0-9]{40}$/.test(f.lastTarget)&&/^[a-f0-9]{40}$/.test(f.lastBlob)&&Number.isFinite(Date.parse(f.lastDate)))),'INVALID_PER_FILE_REVIEW_HISTORY');}const ordinal=state.completedAudits+1,reasons=new Map(),eligible=analysis.entries.filter(e=>inv.files[e.id].eligible),seed=state.baselineTarget;
 const select=(p,r)=>{if(!reasons.has(p))reasons.set(p,[]);if(!reasons.get(p).includes(r))reasons.get(p).push(r);};
 if(escalationPath){const e=eligible.find(e=>e.path===escalationPath);fail(e&&typeof concern==='string'&&concern.trim(),'ELIGIBLE_ESCALATION_PATH_AND_EXACT_CONCERN_REQUIRED');select(e.path,'OPUS_TRIGGERED_ESCALATION: '+concern);for(const id of [...e.dependencies,...e.consumers,...e.tests])if(inv.files[id].eligible)select(inv.files[id].path,'ESCALATION_DEPENDENCY_CONSUMER_TEST');return {ordinal,reasons,overdue:[],rotation:[],state};}
 const order={};for(const tier of [2,3]){const period=PERIOD[tier],buckets=Array.from({length:period},(_,i)=>({id:i,bytes:0}));for(const e of eligible.filter(e=>e.tier===tier)){const slot=parseInt(hash(seed+'|'+e.path).slice(0,8),16)%period;buckets[slot].bytes+=inv.files[e.id].bytes;}order[tier]=buckets.sort((a,b)=>(a.bytes===0)-(b.bytes===0)||a.bytes-b.bytes||a.id-b.id).map(b=>b.id);}
 const rotation=[],overdue=[];
 for(const e of eligible){const f=inv.files[e.id],last=state.files[e.path],period=PERIOD[e.tier],slot=parseInt(hash(seed+'|'+e.path).slice(0,8),16)%period;
  if(last&&e.tier<last.tier)select(e.path,'RISK_TIER_PROMOTION');if(e.tier===1)select(e.path,'TIER_1_CRITICAL_EVERY_AUDIT');if(e.changed)select(e.path,'CHANGED_SINCE_LAST_COMPLETED_TARGET');
  // Strong syntax markers on live source are candidate evidence, not Codex defect verdicts.
  if(e.tier<=2&&e.markers.todo>0&&!['tests','documentation','roadmap-governance'].includes(f.classification))select(e.path,'LOCAL_TODO_FIXME_SOURCE_SIGNAL');
  if(e.tier===2&&(e.markers.trustBoundary>0||e.parallelCandidates.length>0)&&f.classification!=='tests')select(e.path,'LOCAL_TRUST_OR_PARALLEL_SOURCE_SIGNAL');
  const age=last?.lastAudit==null?ordinal:ordinal-last.lastAudit;
  if(age>=period){select(e.path,'OVERDUE_DIRECT_REVIEW');overdue.push(e.path);}
  if(e.tier>1&&slot===order[e.tier][(ordinal-1)%period]){select(e.path,'DETERMINISTIC_TIER_'+e.tier+'_ROTATION');rotation.push(e.path);}
  if(['FORCE_ROADMAP.md','README.md','model/README.md','DEPLOYMENT_STRUCTURE.md','PREDICTIVE_FEATURE_POLICY_V30.md'].includes(e.path))select(e.path,'CURRENT_ARCHITECTURE_METHODOLOGY_TRUTH_OWNER');
 }
 // Baseline inspects broad related-test backlog. Routine retains current catalog contracts; historical/non-selected tests still get mandatory Tier-2 rotation, changed/risk and overdue inclusion.
 // One-hop evidence closure. Explicit source references/consumers and mapped tests, not guessed transitively infinite graphs.
 const roots=[...reasons.keys()].map(p=>eligible.find(e=>e.path===p));for(const e of roots.filter(e=>e.tier===1||e.changed||reasons.get(e.path).some(r=>r.startsWith('LOCAL_')||r==='RISK_TIER_PROMOTION'))){for(const id of [...e.dependencies,...e.tests,...e.consumers.filter(id=>inv.files[id].classification!=='tests')]){const f=inv.files[id];if(state.completedAudits>0&&f.classification==='tests'&&analysis.entries[id].testContractState!=='CURRENT_SELECTED')continue;if(f.eligible&&['model-statistical-source','server-runtime','frontend','production-data-contract','config-build-deploy','tests','test-infrastructure'].includes(f.classification))select(f.path,'DETERMINISTIC_DEPENDENCY_CONSUMER_TEST_CLOSURE');}}
 return {ordinal,reasons,overdue,rotation,state,rotationOrder:order};
}
export function coverageMetrics(inv,analysis,selection){const eligible=analysis.entries.filter(e=>inv.files[e.id].eligible),chosen=eligible.filter(e=>selection.reasons.has(e.path)),changed=eligible.filter(e=>e.changed),critical=eligible.filter(e=>e.tier===1),seen=eligible.filter(e=>selection.state.files[e.path]?.lastRunId),never=eligible.filter(e=>!selection.state.files[e.path]?.lastRunId);return {inventoryCoveragePercent:100,localAnalyticCoveragePercent:100,tierCounts:Object.fromEntries([1,2,3].map(t=>[t,eligible.filter(e=>e.tier===t).length])),changedEligible:changed.length,directContentFilesPlanned:chosen.length,directContentPercentPlanned:100*chosen.length/eligible.length,changedDirectPercent:changed.length?100*changed.filter(e=>selection.reasons.has(e.path)).length/changed.length:null,criticalDirectPercent:critical.length?100*critical.filter(e=>selection.reasons.has(e.path)).length/critical.length:100,rotationSelectedOrdinary:selection.rotation.filter(p=>analysis.entries.find(e=>e.path===p).tier===3),cumulativeCompletedDirectFiles:seen.length,cumulativeCompletedDirectPercent:100*seen.length/eligible.length,neverDirectlyReviewed:never.map(e=>e.path),oldestCompletedReviewDate:seen.map(e=>selection.state.files[e.path].lastDate).sort(compare)[0]??null,oldestCompletedReviewAgeAudits:seen.length?Math.max(...seen.map(e=>selection.state.completedAudits-selection.state.files[e.path].lastAudit)):null,cyclesUntilFullTier3Sweep:never.filter(e=>e.tier===3).length?Math.max(...never.filter(e=>e.tier===3).map(e=>Math.max(1,4-selection.state.completedAudits))):0,maximumTier3Interval:4,overdue:selection.overdue};}