import {hash,compare,fail} from './util.mjs';
import {tierFor,analyzeRepository,compactMap,initialDirectState} from './selection-v3.mjs';
import {riskEvidence} from './risks.mjs';
export {tierFor,analyzeRepository,compactMap,initialDirectState};
export const REVIEW_POLICY='force-risk-rotation-v4';
export const POLICIES=Object.freeze({A:{periods:{1:1,2:2,3:4},method:'FIXED'},B:{periods:{1:1,2:3,3:6},method:'FIXED'},C:{periods:{1:1,2:4,3:8},method:'FIXED'},D:{periods:{1:1,2:4,3:12},method:'FIXED'},E:{periods:{1:1,2:4,3:12},method:'RISK_AGE_BYTES'}});
export const DEFAULT_ROTATION_POLICY='D';
export const PERIOD=POLICIES.D.periods;
const ageOf=(state,p,ordinal)=>state.files[p]?.lastAudit==null?ordinal:ordinal-state.files[p].lastAudit;
const sum=(inv,paths)=>inv.files.filter(f=>paths.has(f.path)).reduce((n,f)=>n+f.bytes,0);
const select=(reasons,p,r)=>{if(!reasons.has(p))reasons.set(p,[]);if(!reasons.get(p).includes(r))reasons.get(p).push(r);};
function mandatory(inv,analysis,state,{includeChanges=true,includeTransitions=true,legacyBaseline=false}={}){
 const reasons=new Map(),eligible=analysis.entries.filter(e=>inv.files[e.id].eligible);
 for(const e of eligible){const f=inv.files[e.id],last=state.files[e.path];if(e.tier===1)select(reasons,e.path,'TIER_1_CRITICAL_EVERY_AUDIT');if(includeChanges&&e.changed)select(reasons,e.path,'CHANGED_SINCE_LAST_COMPLETED_TARGET');if(includeTransitions&&!last)select(reasons,e.path,'NEW_ELIGIBLE_IMMEDIATE');if(includeTransitions&&last&&e.tier<last.tier)select(reasons,e.path,'RISK_TIER_PROMOTION');if(e.tier<=2&&e.markers.todo>0&&!['tests','documentation','roadmap-governance'].includes(f.classification))select(reasons,e.path,'LOCAL_TODO_FIXME_SOURCE_SIGNAL');if(e.tier===2&&(e.markers.trustBoundary>0||e.parallelCandidates.length>0)&&f.classification!=='tests')select(reasons,e.path,'LOCAL_TRUST_OR_PARALLEL_SOURCE_SIGNAL');if(['FORCE_ROADMAP.md','README.md','model/README.md','DEPLOYMENT_STRUCTURE.md','PREDICTIVE_FEATURE_POLICY_V30.md'].includes(e.path))select(reasons,e.path,'CURRENT_ARCHITECTURE_METHODOLOGY_TRUTH_OWNER');}
 const roots=[...reasons.keys()].map(p=>eligible.find(e=>e.path===p));for(const e of roots.filter(e=>e.tier===1||includeChanges&&e.changed||reasons.get(e.path).some(r=>r.startsWith('LOCAL_')||r==='RISK_TIER_PROMOTION'||r==='NEW_ELIGIBLE_IMMEDIATE'))){for(const id of [...e.dependencies,...e.tests,...e.consumers.filter(id=>inv.files[id].classification!=='tests')]){const f=inv.files[id];if(!(legacyBaseline&&state.completedAudits===0)&&f.classification==='tests'&&analysis.entries[id].testContractState!=='CURRENT_SELECTED')continue;if(f.eligible&&['model-statistical-source','server-runtime','frontend','production-data-contract','config-build-deploy','tests','test-infrastructure'].includes(f.classification))select(reasons,f.path,'DETERMINISTIC_DEPENDENCY_CONSUMER_TEST_CLOSURE');}}
 return reasons;
}
export function enforceOverdue(inv,analysis,state,periods,reasons,ordinal){const overdue=[];for(const e of analysis.entries.filter(e=>inv.files[e.id].eligible))if(ageOf(state,e.path,ordinal)>=periods[e.tier]){select(reasons,e.path,'OVERDUE_DIRECT_REVIEW');overdue.push(e.path);}return overdue;}
export function assertSelectionSla(inv,analysis,state,selection){for(const e of analysis.entries.filter(e=>inv.files[e.id].eligible)){const selected=selection.reasons.has(e.path),last=state.files[e.path];fail(!(e.tier===1||e.changed||!last||e.tier<last.tier||ageOf(state,e.path,selection.ordinal)>=selection.periods[e.tier])||selected,'SELECTION_SLA_VIOLATION: '+e.path);}for(const p of selection.implementerFlags.keys())fail(selection.reasons.has(p),'DECLARED_RISK_OMITTED');for(const p of selection.implementerNeighbors.keys())fail(selection.reasons.has(p),'DECLARED_RISK_CONTEXT_OMITTED');}
export function selectDirect(inv,analysis,state,o={}){
 fail(state?.schema===1&&Number.isInteger(state.completedAudits)&&state.completedAudits>=0&&/^[a-f0-9]{40}$/.test(state.baselineTarget)&&state.files&&typeof state.files==='object'&&!Array.isArray(state.files),'INVALID_DIRECT_REVIEW_STATE');for(const [p,f]of Object.entries(state.files))fail(typeof p==='string'&&f&&[1,2,3].includes(f.tier)&&((f.lastAudit===null&&f.lastRunId===null)||(Number.isInteger(f.lastAudit)&&f.lastAudit>0&&f.lastAudit<=state.completedAudits&&typeof f.lastRunId==='string'&&/^[a-f0-9]{40}$/.test(f.lastTarget)&&/^[a-f0-9]{40}$/.test(f.lastBlob)&&Number.isFinite(Date.parse(f.lastDate)))),'INVALID_PER_FILE_REVIEW_HISTORY');
 const policy=POLICIES[o.rotationPolicy??DEFAULT_ROTATION_POLICY];fail(policy,'UNKNOWN_ROTATION_POLICY');const periods=policy.periods,ordinal=state.completedAudits+1,eligible=analysis.entries.filter(e=>inv.files[e.id].eligible),seed=state.baselineTarget;
 if(o.escalationPath){const e=eligible.find(e=>e.path===o.escalationPath),reasons=new Map();fail(e&&typeof o.concern==='string'&&o.concern.trim(),'ELIGIBLE_ESCALATION_PATH_AND_EXACT_CONCERN_REQUIRED');select(reasons,e.path,'OPUS_TRIGGERED_ESCALATION: '+o.concern);for(const id of [...e.dependencies,...e.consumers,...e.tests])if(inv.files[id].eligible)select(reasons,inv.files[id].path,'ESCALATION_DEPENDENCY_CONSUMER_TEST');return {ordinal,reasons,periods,overdue:[],rotation:[],state,stats:{escalationPaths:[...reasons.keys()]}};}
 const reasons=mandatory(inv,analysis,state,{legacyBaseline:(o.rotationPolicy??DEFAULT_ROTATION_POLICY)==='A'}),independentBeforeRisk=new Set([...reasons.keys(),...eligible.filter(e=>ageOf(state,e.path,ordinal)>=periods[e.tier]).map(e=>e.path)]),evidence=riskEvidence(analysis,inv,o.riskDeclarations??[],o.substantiveIntegrations??[]);
 for(const [p,rs]of evidence.flags)for(const r of rs)select(reasons,p,'IMPLEMENTER_DECLARED_RISK: '+r);for(const [p,rs]of evidence.neighbors)for(const r of rs)select(reasons,p,'IMPLEMENTER_RISK_CONTEXT: '+r);
 const quietCore=mandatory(inv,analysis,state,{includeChanges:false,includeTransitions:false}),quietPaths=new Set(eligible.filter(e=>!quietCore.has(e.path)).map(e=>e.path)),throughput=eligible.filter(e=>quietPaths.has(e.path)).reduce((n,e)=>n+inv.files[e.id].bytes/periods[e.tier],0),derivedRotationBudget=Math.ceil(throughput);fail(o.rotationByteBudget===undefined||o.rotationByteBudget===null||Number.isInteger(o.rotationByteBudget)&&o.rotationByteBudget>=0,'INVALID_ROTATION_BYTE_BUDGET');
 const normalSourceBudget=sum(inv,quietCore)+derivedRotationBudget,overdue=enforceOverdue(inv,analysis,state,periods,reasons,ordinal),mandatoryPaths=new Set(reasons.keys()),mandatoryBytes=sum(inv,mandatoryPaths),rotation=[],budget=o.rotationByteBudget??Math.max(0,normalSourceBudget-mandatoryBytes),candidates=eligible.filter(e=>!reasons.has(e.path));
 if(policy.method==='FIXED'){const order={};for(const tier of [2,3]){const buckets=Array.from({length:periods[tier]},(_,id)=>({id,bytes:0}));for(const e of eligible.filter(e=>e.tier===tier))buckets[parseInt(hash(seed+'|'+e.path).slice(0,8),16)%periods[tier]].bytes+=inv.files[e.id].bytes;order[tier]=buckets.sort((a,b)=>(a.bytes===0)-(b.bytes===0)||a.bytes-b.bytes||a.id-b.id).map(b=>b.id);}const scheduled=eligible.filter(e=>e.tier>1&&parseInt(hash(seed+'|'+e.path).slice(0,8),16)%periods[e.tier]===order[e.tier][(ordinal-1)%periods[e.tier]]);const elastic=policy===POLICIES.D&&(evidence.flags.size>0||analysis.entries.some(e=>e.changed));let used=0;for(const e of scheduled){if(reasons.has(e.path)){rotation.push(e.path);continue;}const n=inv.files[e.id].bytes;if(elastic&&(budget<=0||used>0&&used+n>budget))break;select(reasons,e.path,'DETERMINISTIC_TIER_'+e.tier+'_ROTATION');rotation.push(e.path);used+=n;if(elastic&&used>=budget)break;}}
 else{const priority=e=>({ageRatio:ageOf(state,e.path,ordinal)/periods[e.tier],never:state.files[e.path]?.lastAudit==null?1:0,criticalConsumers:e.consumers.filter(id=>analysis.entries[id].tier===1).length,fan:e.dependencies.length+e.consumers.length,tie:hash(seed+'|'+e.path)});candidates.sort((a,b)=>{const x=priority(a),y=priority(b);return y.ageRatio-x.ageRatio||y.never-x.never||y.criticalConsumers-x.criticalConsumers||y.fan-x.fan||compare(x.tie,y.tie);});const allocate=(list,capacity)=>{let used=0;for(const e of list){if(capacity<=0)break;const n=inv.files[e.id].bytes;if(used+n>capacity&&used>0)break;select(reasons,e.path,used+n>capacity?'RISK_AGE_ROTATION_OVERSIZED_HEAD':'RISK_AGE_BYTE_ROTATION');rotation.push(e.path);used+=n;if(used>=capacity)break;}};if(state.completedAudits===0){for(const tier of [2,3]){const share=Math.ceil(eligible.filter(e=>e.tier===tier&&quietPaths.has(e.path)).reduce((n,e)=>n+inv.files[e.id].bytes/periods[tier],0));allocate(candidates.filter(e=>e.tier===tier),Math.min(budget,share));}}else allocate(candidates,budget);}
 const riskOnly=new Set([...reasons.keys()].filter(p=>!independentBeforeRisk.has(p)&&(evidence.flags.has(p)||evidence.neighbors.has(p)))),result={ordinal,reasons,periods,overdue,rotation,state,implementerFlags:evidence.flags,implementerNeighbors:evidence.neighbors,stats:{method:policy.method,quietMandatoryBytes:sum(inv,quietCore),requiredQuietRotationMeanBytes:throughput,derivedRotationByteBudget:derivedRotationBudget,normalSourceByteBudget:normalSourceBudget,availableRotationByteBudget:budget,mandatoryBytes,rotationBytes:sum(inv,new Set([...reasons.keys()].filter(p=>!mandatoryPaths.has(p)))),totalDirectBytes:sum(inv,reasons),mandatoryFiles:mandatoryPaths.size,overdueBeforeSelection:overdue.length,implementerFlaggedPaths:[...evidence.flags.keys()],implementerNeighborhoodPaths:[...evidence.neighbors.keys()],independentlySelectedUnflagged:[...reasons.keys()].filter(p=>!evidence.flags.has(p)&&!evidence.neighbors.has(p)),deterministicRiskPaths:[...reasons].filter(([,rs])=>rs.some(r=>r.startsWith('LOCAL_'))).map(([p])=>p),rotationOnlyPaths:[...reasons.keys()].filter(p=>!mandatoryPaths.has(p)),riskDrivenAdditionalBytes:sum(inv,riskOnly),missingRiskDeclarations:evidence.missingRiskDeclarations,missingDeclarationStatus:evidence.missingDeclarationStatus,expansion:evidence.expansion,budgetMeaning:'Source-byte planning capacity derived from mandatory quiet evidence + mean quiet-file bytes required by the SLA. It is separate from dollar authorization. Quiet fixed schedules retain their full bucket; changed/risk audits use remaining soft capacity. Overdue/mandatory content and an oversized highest-priority head bypass that capacity; no small-file fit search.'}};assertSelectionSla(inv,analysis,state,result);return result;
}
export function coverageMetrics(inv,analysis,s){const eligible=analysis.entries.filter(e=>inv.files[e.id].eligible),chosen=eligible.filter(e=>s.reasons.has(e.path)),changed=eligible.filter(e=>e.changed),critical=eligible.filter(e=>e.tier===1),seen=eligible.filter(e=>s.state.files[e.path]?.lastRunId),never=eligible.filter(e=>!s.state.files[e.path]?.lastRunId);return {inventoryCoveragePercent:100,localAnalyticCoveragePercent:100,tierCounts:Object.fromEntries([1,2,3].map(t=>[t,eligible.filter(e=>e.tier===t).length])),changedEligible:changed.length,directContentFilesPlanned:chosen.length,directContentPercentPlanned:100*chosen.length/eligible.length,changedDirectPercent:changed.length?100*changed.filter(e=>s.reasons.has(e.path)).length/changed.length:null,criticalDirectPercent:critical.length?100*critical.filter(e=>s.reasons.has(e.path)).length/critical.length:100,rotationSelectedOrdinary:s.rotation.filter(p=>analysis.entries.find(e=>e.path===p).tier===3),cumulativeCompletedDirectFiles:seen.length,cumulativeCompletedDirectPercent:100*seen.length/eligible.length,neverDirectlyReviewed:never.map(e=>e.path),oldestCompletedReviewDate:seen.map(e=>s.state.files[e.path].lastDate).sort(compare)[0]??null,oldestCompletedReviewAgeAudits:seen.length?Math.max(...seen.map(e=>s.state.completedAudits-s.state.files[e.path].lastAudit)):null,cyclesUntilFullTier3Sweep:never.some(e=>e.tier===3)?Math.max(0,s.periods[3]-s.state.completedAudits):0,maximumTier3Interval:s.periods[3],maximumTier2Interval:s.periods[2],overdue:s.overdue,rotationPolicyStats:s.stats};}