import {buildPlan} from './plan.mjs';
import {inventory} from './inventory.mjs';
import {POLICIES,DEFAULT_ROTATION_POLICY,tierFor} from './selection.mjs';
import {syntheticDeclaration,syntheticRisk} from './risks.mjs';
import {hash,json,fail,compare} from './util.mjs';
import {hypotheticalCompletion,MODERATE_CHANGE} from './simulation-v3.mjs';
export {simulateFive} from './simulation-v3.mjs';
export {hypotheticalCompletion,MODERATE_CHANGE};
const mean=xs=>xs.reduce((n,x)=>n+x,0)/xs.length;
export function distribution(rows){const costs=rows.map(r=>r.ceilingUsd).sort((a,b)=>a-b),n=costs.length;return {cycles:n,minUsd:costs[0],medianUsd:n%2?costs[(n-1)/2]:(costs[n/2-1]+costs[n/2])/2,meanUsd:mean(costs),maxUsd:costs.at(-1),callRange:[Math.min(...rows.map(r=>r.calls)),Math.max(...rows.map(r=>r.calls))],meanOriginalBytes:mean(rows.map(r=>r.totalDirectBytes)),meanDirectFiles:mean(rows.map(r=>r.directFiles)),meanDirectPercent:mean(rows.map(r=>r.directPercent)),maxReviewAge:Math.max(...rows.map(r=>r.oldestReviewedAgeAuditsAfter))};}
export function unavoidableInputFloor(inv,periods={1:1,2:2,3:4}){const tiers=Object.fromEntries([1,2,3].map(t=>[t,inv.files.filter(f=>f.eligible&&tierFor(f)===t).reduce((n,f)=>n+f.bytes,0)])),originalBytesPerAudit=[1,2,3].reduce((n,t)=>n+tiers[t]/periods[t],0);return {tierBytes:tiers,periods,originalBytesPerAudit,minimumMeanInputUsd:originalBytesPerAudit*4/1e6,meaning:'Original-source lower bound under the one-byte-per-token proxy; not an actual token/billing prediction. Ignores mandatory closure, maps, outputs and buffers.'};}
export function simulateTwelve(root,target,initial,{rotationPolicy=DEFAULT_ROTATION_POLICY,moderateChange=MODERATE_CHANGE,cycles=12,quietOnly=false,risks=true,options={},runPrefix='FORCE-SLA'}={}){
 fail(initial?.completedAudits===0&&Number.isInteger(cycles)&&cycles>=12,'SIMULATION_REQUIRES_UNREVIEWED_BASELINE_AND_12_CYCLES');const snapshot=hash(json(initial)),inv=inventory(root,target),eligible=inv.files.filter(f=>f.eligible),periods=POLICIES[rotationPolicy]?.periods;fail(periods,'UNKNOWN_SIMULATION_POLICY');let state=structuredClone(initial);const rows=[];
 const elevated=eligible.filter(f=>tierFor(f)===1).slice(0,16).map(f=>f.path),ordinary=eligible.filter(f=>tierFor(f)===3).sort((a,b)=>compare(a.path,b.path)),small=ordinary.find(f=>f.bytes>0&&f.bytes<8000)?.path,large=[...ordinary].sort((a,b)=>b.bytes-a.bytes)[0]?.path;
 for(let audit=1;audit<=cycles;audit++){const substantive=!quietOnly&&[3,6,8].includes(audit),mandatoryTrigger=!quietOnly&&audit===6,changed=substantive?(mandatoryTrigger?elevated:[...moderateChange]):[],integrationId='SYNTHETIC-'+rotationPolicy+'-'+audit,decl=substantive&&risks?[syntheticDeclaration(target,integrationId,changed,[syntheticRisk('changed-uncertainty',[mandatoryTrigger?changed[0]:(changed[2]??changed[0])],'UNCERTAIN'),syntheticRisk(mandatoryTrigger?'broad-state-risk':'indirect-contract-risk',[mandatoryTrigger?large:small],'HIGH REVIEW')])]:[],integrations=substantive?[{id:integrationId}]:[];
 const built=buildPlan(root,target,{...options,runId:runPrefix+'-'+rotationPolicy+'-'+audit,directState:state,comparisonTarget:target,rotationPolicy,simulationOnly:true,simulatedChangedPaths:changed,mandatoryTrigger,riskDeclarations:decl,substantiveIntegrations:integrations}),selected=built.manifest.files.filter(f=>f.directSelected),stats=built.plan.summary.rotationPolicyStats,after=hypotheticalCompletion(state,built,new Date(Date.UTC(2026,9,8+(audit-1)*7,12)).toISOString()),never=eligible.filter(f=>after.files[f.path]?.lastAudit==null),seen=eligible.filter(f=>after.files[f.path]?.lastAudit!=null);
 for(const f of eligible){const record=after.files[f.path],age=record.lastAudit===null?audit:audit-record.lastAudit;fail(age<periods[tierFor(f)],'SIMULATION_ROTATION_DEADLINE_MISSED: '+f.path);if(tierFor(f)===1)fail(selected.some(x=>x.path===f.path),'SIMULATION_CRITICAL_OMITTED');}fail(changed.every(p=>selected.some(f=>f.path===p)),'SIMULATION_CHANGED_OMITTED');
 let riskDelta=null;if(decl.length){const without=buildPlan(root,target,{...built.plan.options,runId:built.plan.runId,riskDeclarations:[]});riskDelta={implementerRiskFiles:stats.implementerFlaggedPaths.length,neighborhoodFiles:stats.implementerNeighborhoodPaths.length,independentlySelectedUnflagged:stats.independentlySelectedUnflagged.length,riskDrivenDirectBytes:stats.riskDrivenAdditionalBytes,rotationBytesDisplaced:Math.max(0,without.plan.summary.rotationPolicyStats.rotationBytes-stats.rotationBytes),incrementalCeilingUsd:Number((built.plan.estimatedCeilingUsd-without.plan.estimatedCeilingUsd).toFixed(6)),counterfactualCeilingUsd:without.plan.estimatedCeilingUsd,meaning:'Signed cost delta versus the same history/change metadata without declarations; flags may displace optional rotation. Synthetic flags are not product findings.'};}
 rows.push({audit,scenario:audit===1?'INITIAL BASELINE':mandatoryTrigger?'SYNTHETIC LARGE CHANGE + MANDATORY EVENT':substantive?'SYNTHETIC MODERATE INTEGRATION':'QUIET',classification:built.plan.reviewClass,calls:built.plan.plannedCalls,ceilingUsd:built.plan.estimatedCeilingUsd,mandatoryBytes:stats.mandatoryBytes,rotationBytes:stats.rotationBytes,totalDirectBytes:stats.totalDirectBytes,directFiles:selected.length,directPercent:100*selected.length/eligible.length,tierDirect:Object.fromEntries([1,2,3].map(t=>[t,selected.filter(f=>f.tier===t).length])),tier1Percent:100,changedPaths:changed,changedDirectPercent:changed.length?100:null,cumulativeDirectPercentAfter:100*(eligible.length-never.length)/eligible.length,oldestReviewedAgeAuditsAfter:Math.max(...seen.map(f=>audit-after.files[f.path].lastAudit)),oldestAgeByTier:Object.fromEntries([1,2,3].map(t=>[t,Math.max(0,...eligible.filter(f=>tierFor(f)===t).map(f=>after.files[f.path].lastAudit===null?audit:audit-after.files[f.path].lastAudit))])),overdueBeforeSelection:stats.overdueBeforeSelection,overdueAfterCompletion:0,escalationCalls:0,neverReviewedAfter:never.length,riskDelta,selectionStats:stats,selectedPaths:selected.map(f=>f.path),rotationStateAfter:Object.fromEntries(eligible.map(f=>[f.path,{tier:tierFor(f),lastHypotheticalAudit:after.files[f.path].lastAudit}]))});state=after;
 }
 fail(hash(json(initial))===snapshot,'SIMULATION_MUTATED_REAL_LEDGER');const routine=rows.filter(r=>r.classification==='QUIET ROUTINE'||r.classification==='NORMAL ROUTINE'),quiet=rows.filter(r=>r.classification==='QUIET ROUTINE'),normal=rows.filter(r=>r.classification==='NORMAL ROUTINE');return {schema:2,simulationOnly:true,target,rotationPolicy,periods,apiCalls:0,keyReads:0,spendUsd:0,realHistoryWritten:false,baselineCountsAsCycleOne:true,firstFullSweepAudit:rows.find(r=>r.neverReviewedAfter===0)?.audit??null,guaranteedInitialSweepAudit:Math.max(...Object.values(periods)),routineDistribution:distribution(routine),quietDistribution:distribution(quiet),normalDistribution:normal.length?distribution(normal):null,normalCostTargetDemonstrated:routine.every(r=>r.ceilingUsd<=8&&r.calls>=4&&r.calls<=8),sourceOnlySlaFloor:unavoidableInputFloor(inv,periods),quietCoreFloorUsd:rows[0].selectionStats.quietMandatoryBytes*4/1e6,packetFeasible:true,contentSizing:'Current target bytes only; future metadata/risks are explicit synthetic overlays, no product conclusions or Git writes.',rows};
}
export function comparePolicies(root,target,initial,options={}){return Object.fromEntries(Object.keys(POLICIES).map(rotationPolicy=>[rotationPolicy,simulateTwelve(root,target,initial,{...options,rotationPolicy})]));}