import {buildPlan} from './plan.mjs';
import {inventory} from './inventory.mjs';
import {initialDirectState,tierFor} from './selection.mjs';
import {hash,json,fail} from './util.mjs';
export const MODERATE_CHANGE=Object.freeze(['model/unit_prior_controller.js','assets/app.js','scripts/test_v37_unit_prior.js','scripts/lib/force_app_harness.js','data/predictive-feature-gates.js','CHANGELOG_V37.md']);
export function hypotheticalCompletion(state,built,date){
 const next=structuredClone(state);next.completedAudits++;for(const f of built.manifest.files.filter(f=>f.eligible)){const prev=next.files[f.path]??{lastRunId:null,lastDate:null,lastTarget:null,lastBlob:null,lastAudit:null,passes:[],selectionReason:null};next.files[f.path]={...prev,tier:f.tier,changedSinceLastReview:prev.lastBlob!==f.blob,...(f.directSelected?{lastRunId:'HYPOTHETICAL-'+next.completedAudits,lastDate:date,lastTarget:built.plan.target,lastBlob:f.blob,lastAudit:next.completedAudits,passes:f.contentShards,selectionReason:f.selectionReasons,changedSinceLastReview:false}:{})};}return next;
}
export function unavoidableInputFloor(inv){const tiers=Object.fromEntries([1,2,3].map(t=>[t,inv.files.filter(f=>f.eligible&&tierFor(f)===t).reduce((n,f)=>n+f.bytes,0)])),originalBytesPerAudit=tiers[1]+tiers[2]/2+tiers[3]/4;return {tierBytes:tiers,originalBytesPerAudit,minimumMeanInputUsd:originalBytesPerAudit*4/1e6,meaning:'Long-run lower bound for original selected bytes using the retained $4/M byte-as-token proxy and 1/2/4 intervals. Excludes maps, escaping, metadata, outputs, buffers, changes and extra repeated related evidence. It is not an actual token/billing prediction.'};}
export function simulateFive(root,target,initial,{moderateChange=MODERATE_CHANGE,runPrefix='FORCE-ECONOMICS',options={}}={}){
 fail(initial?.completedAudits===0,'SIMULATION_REQUIRES_REAL_UNREVIEWED_BASELINE_SNAPSHOT');const baselineHash=hash(json(initial)),inv=inventory(root,target),eligible=inv.files.filter(f=>f.eligible);let state=structuredClone(initial);const rows=[];
 const scenarios=['CURRENT BASELINE','QUIET ROUTINE','SYNTHETIC MODERATE INTEGRATION','QUIET / ROTATION PRESSURE','ROTATION COMPLETION PRESSURE'];
 for(let i=1;i<=5;i++){const changed=i===3?[...moderateChange]:[],built=buildPlan(root,target,{...options,runId:runPrefix+'-'+i,directState:state,comparisonTarget:target,simulationOnly:true,simulatedChangedPaths:changed}),chosen=built.manifest.files.filter(f=>f.directSelected),after=hypotheticalCompletion(state,built,new Date(Date.UTC(2026,9,8+(i-1)*7,12)).toISOString()),seen=eligible.filter(f=>after.files[f.path]?.lastRunId),never=eligible.filter(f=>!after.files[f.path]?.lastRunId),neverOrdinary=never.filter(f=>tierFor(f)===3);
 for(const f of eligible){const record=after.files[f.path],age=record.lastAudit===null?i:i-record.lastAudit;fail(age<({1:1,2:2,3:4}[tierFor(f)]),'SIMULATION_ROTATION_DEADLINE_MISSED: '+f.path);if(tierFor(f)===1)fail(chosen.some(x=>x.path===f.path),'SIMULATION_CRITICAL_OMITTED');}fail(changed.every(p=>chosen.some(f=>f.path===p)),'SIMULATION_CHANGED_OMITTED');
 rows.push({audit:i,scenario:scenarios[i-1],plannerMode:built.plan.plannerMode,simulationOnly:true,contentSizing:'Original committed target bytes; cycle 3 overlays synthetic change metadata only, not future product code or a forecast of new-code size.',calls:built.plan.plannedCalls,thematicCalls:built.plan.thematicCalls,additionalContentShardCalls:built.plan.additionalContentShardCalls,escalationCalls:0,ceilingUsd:built.plan.estimatedCeilingUsd,directFiles:chosen.length,directPercent:100*chosen.length/eligible.length,tierDirect:Object.fromEntries([1,2,3].map(t=>[t,chosen.filter(f=>f.tier===t).length])),tier1Percent:100,changedPaths:changed,changedDirectPercent:changed.length?100:null,cumulativeDirectPercentAfter:100*seen.length/eligible.length,neverReviewedAfter:never.length,neverOrdinaryAfter:neverOrdinary.length,oldestReviewedAgeAuditsAfter:Math.max(...seen.map(f=>i-after.files[f.path].lastAudit)),expectedCyclesUntilFullOrdinaryExposure:neverOrdinary.length?Math.max(0,4-i):0,selectedPaths:chosen.map(f=>f.path),outputCaps:built.plan.passes.map(p=>({pass:p.id,maxTokens:p.maxTokens,rationale:p.outputBudget.rationale})),costDecomposition:built.plan.costDecomposition,rotationStateAfter:Object.fromEntries(eligible.map(f=>[f.path,{tier:after.files[f.path].tier,lastHypotheticalAudit:after.files[f.path].lastAudit}]))});state=after;
 }
 fail(hash(json(initial))===baselineHash,'SIMULATION_MUTATED_REAL_BASELINE');const routine=rows.slice(1);return {schema:1,simulationOnly:true,productionTarget:target,initialSnapshotHash:baselineHash,realHistoryWritten:false,apiCalls:0,keyReads:0,spendUsd:0,baselineCountsAsCycleOne:true,firstFullOrdinaryExposureAudit:rows.find(r=>r.neverOrdinaryAfter===0)?.audit??null,guaranteedFirstFullOrdinaryExposureAudit:4,interpretation:'Every Tier-3 file is included by completed audit 4, including baseline as audit 1; ongoing maximum four-completed-audit intervals. Cycles advance ONLY hypothetically in private simulation state.',unavoidableInputFloor:unavoidableInputFloor(inv),routineCallRange:[Math.min(...routine.map(r=>r.calls)),Math.max(...routine.map(r=>r.calls))],routineCostRange:[Math.min(...routine.map(r=>r.ceilingUsd)),Math.max(...routine.map(r=>r.ceilingUsd))],preferredEnvelopeDemonstrated:routine.every(r=>r.calls>=4&&r.calls<=8&&r.ceilingUsd<=8),rows};
}
