import fs from 'node:fs';
import path from 'node:path';
import {hash,json,writeNew,fail} from './util.mjs';
import {loadRun,status,validResult} from './run.mjs';
export function synthesize(root,id){
 const run=loadRun(root,id),runStatus=status(run),raw=[];
 for(const p of run.plan.passes){const ps=run.state.passes[p.id];if(ps.status!=='COMPLETED')continue;const result=validResult(root,run.plan,p,ps);for(const [i,f]of result.review.findings.entries())raw.push({...f,id:p.id+'-finding-'+String(i+1).padStart(3,'0'),passId:p.id,sourceKind:p.kind,theme:p.theme,sourcePacketHash:p.packetSha256,sourceResult:ps.resultPath,subsystems:[...new Set(f.affected_paths.map(s=>s.includes('/')?s.split('/')[0]:'root'))]});}
 const normalized=s=>s.toLowerCase().replace(/\s+/g,' ').trim();const grouped=new Map();
 for(const f of raw){const key=f.affected_paths.slice().sort().join('|')+'::'+normalized(f.location);if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(f);}
 const groups=[...grouped.values()].map((fs,i)=>{const passes=[...new Set(fs.map(f=>f.passId))],evidence=new Set(fs.map(f=>hash(normalized(f.evidence))));return {id:'group-'+String(i+1).padStart(3,'0'),findingIds:fs.map(f=>f.id),affectedPaths:fs[0].affected_paths,location:fs[0].location,severities:[...new Set(fs.map(f=>f.severity))],natures:[...new Set(fs.map(f=>f.nature))],passes,themes:[...new Set(fs.map(f=>f.theme??'coverage'))],subsystems:[...new Set(fs.flatMap(f=>f.subsystems))],relationship:fs.length===1?'SINGLE FINDING':evidence.size===1?'LIKELY DUPLICATE':passes.length>1?'POSSIBLE INDEPENDENT CORROBORATION — HUMAN CHECK REQUIRED':'RELATED SAME-PASS FINDINGS',conflict: new Set(fs.map(f=>f.severity)).size>1||new Set(fs.map(f=>f.nature)).size>1?'POTENTIALLY CONFLICTING CLASSIFICATION — HUMAN CHECK REQUIRED':null};});
 const indexed=key=>Object.fromEntries([...new Set(raw.flatMap(f=>Array.isArray(f[key])?f[key]:[f[key]??'coverage']))].sort().map(k=>[k,raw.filter(f=>Array.isArray(f[key])?f[key].includes(k):(f[key]??'coverage')===k).map(f=>f.id)]));
 const report={schema:1,runId:id,target:run.plan.target,manifestHash:run.plan.manifestHash,complete:runStatus.complete,missingPasses:runStatus.rows.filter(p=>p.status!=='COMPLETED'),paidSynthesisCalls:0,authority:'Local mechanical grouping only; no owner/model/integration decision, no findings discarded.',rawFindings:raw,groups,indices:{severity:indexed('severity'),subsystem:indexed('subsystems'),theme:indexed('theme'),path:indexed('affected_paths')},conflicts:groups.filter(g=>g.conflict)};
 const lines=[`# Deep review synthesis: ${id}`,`Target: ${run.plan.target}`,`Status: ${report.complete?'ALL REQUIRED PASSES VALID':'INCOMPLETE — NOT A COMPLETED AUDIT'}`,report.authority,`Raw findings: ${raw.length}; groups: ${groups.length}; missing passes: ${report.missingPasses.length}.`];
 for(const g of groups){lines.push(`\n## ${g.id}: ${g.relationship}`,`Finding IDs: ${g.findingIds.join(', ')}`,`Paths: ${g.affectedPaths.join(', ')}`,`Severities: ${g.severities.join(', ')}`,g.conflict??'');for(const f of raw.filter(f=>g.findingIds.includes(f.id)))lines.push(`\n### ${f.id} (${f.severity}; ${f.nature}; confidence ${f.confidence})`,`Evidence: ${f.evidence}`,`Impact: ${f.impact}`,`Smallest next step: ${f.correction}`);}
 if(report.missingPasses.length)lines.push('\n## Incomplete passes',...report.missingPasses.map(p=>`- ${p.id}: ${p.status}`));
 let n=1;while(fs.existsSync(path.join(run.dir,'synthesis-'+String(n).padStart(3,'0')+'.json')))n++;const stem='synthesis-'+String(n).padStart(3,'0');writeNew(path.join(run.dir,stem+'.json'),report);writeNew(path.join(run.dir,stem+'.md'),lines.join('\n')+'\n');return {complete:report.complete,rawFindings:raw.length,groups:groups.length,reportJSON:path.join(run.dir,stem+'.json'),reportMarkdown:path.join(run.dir,stem+'.md')};
}