// RESEARCH ONLY: central-cache envelope, not a quote or an adopted poller.
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
process.chdir(fileURLToPath(new URL('../..',import.meta.url)));
const monthlyUSD=39.99,pollMinutes=210,activeMonths=6;
// Retain one cursor per game. Full reconciliation runs periodically, staggered
// across games. Games/status is batched once per minute across all active games.
const low={scope:'LOW / weekly featured',games:21,gamePollMinutes:21*pollMinutes,sharedGamesMinutes:21*pollMinutes,tailCalls:21*pollMinutes,fullRereadExtraCalls:21*3,peakCallsMinute:3,nominalPeakCallsMinute:2,note:'Three two-page full rereads per event replace a tail call: +1 extra each; two tail/status calls normally, three calls at a two-page reread. Nominal 8820; with extra pages 8883. Assumption, not observed page size.'};
low.calls=low.sharedGamesMinutes+low.tailCalls+low.fullRereadExtraCalls;
const expected={scope:'EXPECTED / all games (paid or public)',games:285,gamePollMinutes:285*pollMinutes,sharedGamesMinutes:21000,tailCalls:285*pollMinutes,fullRereadExtraCalls:285*pollMinutes*.2,concurrentGamesPlanning:11,peakCallsMinute:Math.ceil(1+11*1.2),note:'21000 shared live-window minutes is a calendar assumption, not sum of per-game minutes. 20% extra pages amortizes periodic full rereads; stagger and rate-limit extra requests. 11 is a planning concurrency, not a verified schedule maximum.'};
expected.calls=expected.sharedGamesMinutes+expected.tailCalls+expected.fullRereadExtraCalls;
const worst={scope:'STRESSED / deliberately overcounting upper envelope',durationMinutes:360,games:285,requestsPerPoll:22,calls:360*285*22,peakCallsMinute:16*22,headroomAt600:600-16*22,note:'Retained outer ceiling: 10 pages plus metadata per game, doubled for bounded retry allowance; overcounts shared games status. 16 simultaneous games is theoretical/unreachable in the actual calendar, not realistic concurrency. Fail closed beyond page cap. Not the cursor-tail operating model.'};
const output={assumptions:{pollMinutes,cadenceSeconds:60,regularGames:272,postseasonGames:13,sharedGamesCallsMinute:1,tailCallsPerGameMinute:1,periodicFullReread:true,BDLmonthlyUSD:monthlyUSD,activeMonths,BDLseasonArithmeticUSD:monthlyUSD*activeMonths,BDLGOATlimitPerMinute:600,BDLALLSTAR:{monthlyUSD:9.99,requestsMinute:60,plays:false},pricingBoundary:'Six months is arithmetic at checked monthly price, not locked seasonal pricing; no purchase authorization'},envelopes:{low,expected,stressed:worst},worst,scopeBoundary:'Featured/primetime/all and paid/public remain owner choices; batches depend on filtered active games fitting one page. Other calendars need recalculation.',hostCosts:{upstreamUSDPerCall:0,note:'Fixed BDL monthly tier; quote-only SDIO/Sportradar unknown (null), not affordable. Hosting/cache/fanout unpriced.',SDIOcommercialUSD:null,SportradarUSD:null,downstreamExample:{viewers:1000,hours:4,payloadKiB:2,oneMinuteReads:1000*4*60,egressMiB:1000*4*60*2/1024}}};
fs.writeFileSync('research/cycle7/results/costs.json',JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify(output,null,2));
