const fs=require('fs');
const app=fs.readFileSync('assets/app.js','utf8'), live=fs.readFileSync('model/live_profiles.js','utf8'), server=fs.readFileSync('force_server.py','utf8');
let n=0; const ok=(x,m)=>{if(!x)throw new Error(m);n++;};
ok(server.includes("APP_VERSION = 'V121'"),'server V111');
ok(server.includes("SERVER_DIAG_VERSION = 'V121-DIAG-1'"),'server diagnostic V111');
ok(app.includes('expected FORCE V121'),'client V111');
ok(server.includes("'weight':0.30 if is_botched else 1.0"),'botched snaps downweighted');
ok(server.includes("'fumble_team_expected_recovery':0.80 if is_botched else 0.50"),'botched snap offense baseline');
ok(live.includes('fumble_expected_recoveries'),'expected recovery accounting');
ok(live.includes('fumble_recovery_excess'),'fumble excess accounting');
ok(app.includes('const LUCK_DISPLAY_V113 = Object.freeze({softness:22})'),'nonlinear Luck display calibration');
ok(app.includes('rawOverallLuckScore:rawLuckContextScore(l)'),'raw Luck retained in debug');
ok(app.includes('displayedLuckScore:luckContextScore(l)'),'displayed Luck exposed in debug');
ok(app.includes('expectedWinsDisplayed:l.exp_w!=null?Math.round(Number(l.exp_w)):null'),'rounded expected wins debug/UI contract');
ok(!app.includes('EXPECTED RECORD'),'normal UI removes expected-record band');
ok(!app.includes('fmt(luck.exp_w)}–${fmt(luck.exp_l)'),'team KPI no longer shows expected W-L band');
ok(app.includes('Math.round(Number(l.exp_w))} expected wins'),'context UI shows one rounded expected-wins estimate');
ok(app.includes("receiverPolicy: 'v115-partial-orthogonal'"),'V109 receiver retained');
ok(app.includes("rbPolicy: 'v115-partial-orthogonal'"),'V109 RB retained');
console.log(`PASS: V111 contract (${n} checks)`);
