const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const ctx={window:{}};ctx.globalThis=ctx.window;vm.createContext(ctx);
for(const rel of ['model/live_profiles.js','model/unit_force_bridge.js']) vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel});
const LP=ctx.window.FORCE_LIVE_PROFILE,U=ctx.window.FORCE_UNIT_FORCE_BRIDGE_MODEL;
let n=0; const ok=(x,m)=>{n++;if(!x)throw new Error(m)}; const near=(a,b,e=1e-10)=>Math.abs(a-b)<=e;
const W=LP.DEFENSE_WEIGHTS;
ok(near(W.coverageIndex,.36)&&near(W.passRushIndex,.16)&&near(W.runDefenseIndex,.28)&&near(W.pointsAllowedPerDriveIndex,.20),'V100 defense weights must be 36/16/28/20');
const kcInput={coverageIndex:55,passRushIndex:55,runDefenseIndex:55,pointsAllowedPerDriveIndex:85};
const bufInput={coverageIndex:55,passRushIndex:55,runDefenseIndex:55,pointsAllowedPerDriveIndex:20};
const kcRaw=LP.rawDefenseCompositeFrom(kcInput), bufRaw=LP.rawDefenseCompositeFrom(bufInput);
const kc=LP.defenseCompositeFrom(kcInput), buf=LP.defenseCompositeFrom(bufInput);
ok(near(kcRaw,61),'KC raw synthetic defense should be 61');
ok(near(bufRaw,48),'BUF raw synthetic defense should be 48');
ok(near(kc,LP.calibrateComposite(61,LP.COMPOSITE_V108.defense)),'KC calibrated defense');
ok(near(buf,LP.calibrateComposite(48,LP.COMPOSITE_V108.defense)),'BUF calibrated defense');
ok(kcRaw-bufRaw===13,'20% PPD component must create a 13-point raw separation for 65 index points');
const weights=U.WEIGHTS;
ok(near(Object.values(weights).reduce((a,b)=>a+b,0),1),'unit bridge weights must remain normalized');
ok(near(weights.pointsAllowedPerDriveIndex,.09),'PPD must be 20% of the 45% defensive bridge block');
ok(near(weights.coverageIndex+.0, .162)&&near(weights.passRushIndex,.072)&&near(weights.runDefenseIndex,.126),'remaining defensive bridge shares must preserve 36/16/28 proportions');
console.log(`PASS: V100 simple defensive points/drive model (${n} checks)`);
