const fs=require('fs'),vm=require('vm');
const code=fs.readFileSync('model/live_profiles.js','utf8');
const ctx={window:{},console};vm.createContext(ctx);vm.runInContext(code,ctx);
const L=ctx.window.FORCE_LIVE_PROFILE;let n=0;const ok=(x,m)=>{if(!x)throw new Error(m);n++;};
ok(L.receiverResidualPolicyActive('v115-partial-orthogonal'),'V115 receiver policy active');
ok(L.rbResidualPolicyActive('v115-partial-orthogonal'),'V115 RB policy active');
ok(L.UNIT_V115.receiverResidualStabilizerTargets===80,'receiver stabilization relaxed');
ok(L.UNIT_V115.rbRushStabilizerCarries===50,'RB rushing stabilization relaxed');
ok(L.UNIT_V115.rbRecvResidualStabilizerTargets===40,'RB receiving stabilization relaxed');
const pts=[{x:-1,y:-.5},{x:0,y:0},{x:1,y:.5},{x:2,y:1},{x:3,y:1.5},{x:4,y:2},{x:5,y:2.5},{x:6,y:3}];
const beta=L.ridgeOrthogonalSlope(pts,.5);
ok(beta>0 && beta<.5,'ridge slope is positive but shrunk below OLS');
const partial=L.partialResidual(.5,.4,.5,.1);
ok(Math.abs(partial-.35)<1e-12,'partial residual subtracts only fitted environment excess');
const sample={receivers:{adj_epa:.30,targets:100},rb:{adj_recv:.10,targets:20},qb:{epaoe:.20}};
ok(Math.abs(L.priorReceiverWrteEpa(sample)-.35)<1e-12,'historical WR/TE rate removes RB receiving by targets');
const src=code;
const bridge=fs.readFileSync('model/unit_force_bridge.js','utf8');
ok(src.includes('receiverOrthogonalBeta=receiverPassBeta'),'receiver fitted coefficient exposed');
ok(src.includes('rbRecvOrthogonalBeta=rbRecvPassBeta'),'RB receiving fitted coefficient exposed');
ok(src.includes('r.rbStabilizedRushEpa=stabilizeToward'),'RB rushing remains direct and stabilized rather than OL-subtracted');
ok(src.includes('V115 WR/TE-only receiving EPA/target'),'V115 receiver provenance');
ok(src.includes('V115 RB/FB room: rushing EPA/carry stays directly credited'),'V115 RB provenance');
ok(bridge.includes('receiverIndex:0.08')&&bridge.includes('rbIndex:0.07'),'predictive bridge weights unchanged');
console.log(`PASS: V115 partial orthogonalization + upper-tail room (${n} checks)`);
