const fs=require('fs');
let checks=0;const ok=(c,m)=>{checks++;if(!c)throw new Error(m)};
const app=fs.readFileSync('assets/app.js','utf8');
const css=fs.readFileSync('assets/styles.css','utf8');
const html=fs.readFileSync('index.html','utf8');
ok(app.includes("['update', 'Update']"),'Update tab is present in primary navigation');
ok(app.includes('function updateCenter()'),'Update Center renderer exists');
ok(app.includes('Update all 32 teams'),'league-wide update action exists');
ok(app.includes('Update missing / stale'),'stale-only update action exists');
ok(app.includes('data-update-team="${t}"'),'team-by-team update action exists');
ok(app.includes("refreshSchedule(`update-${b.dataset.updateTeam}`,[b.dataset.updateTeam])"),'team update triggers a real upstream refresh');
ok(app.includes("refreshSchedule('update-all',Object.keys(D.teams))"),'all-team update triggers a real upstream refresh');
ok(app.includes("refreshSchedule('update-stale',targets)"),'stale-only update triggers a real upstream refresh');
ok(app.includes('Canonical live team snapshots'),'Update tab describes canonical snapshot architecture');
ok(app.includes('same unit ratings, FORCE rating, rankings, team pages, matchups, projections, and future forecasts'),'Update Center promises one downstream state');
ok(app.includes("['Offense','teamStats']") && app.includes("['QB','playerStats']") && app.includes("['Pass rush','passRush']") && app.includes("['Scoring / luck','schedule']"),'Update Center covers multiple metric families, not only Pass Rush');
ok(app.includes("['Penalties / player detail','playerStats']"),'player-detail/penalty freshness is included');
ok(app.includes('a live metric family must cover that team\'s latest completed week or it is suppressed'),'hard all-metric freshness policy is rendered');
ok(css.includes('.update-team-grid') && css.includes('.update-metric-list'),'Update Center layout styles exist');
ok(html.includes('model/unit_force_bridge.js'),'canonical Unit-to-FORCE bridge is part of bundle');
console.log(`PASS: V45 Update Center regression (${checks} checks)`);
