const fs=require('fs'),vm=require('vm');
const code=fs.readFileSync('model/live_profiles.js','utf8');
const ctx={window:{},console};vm.createContext(ctx);vm.runInContext(code,ctx);
const L=ctx.window.FORCE_LIVE_PROFILE;let n=0;const ok=(x,m)=>{if(!x)throw new Error(m);n++;};
ok(L.receiverResidualPolicyActive('v114-centered-stabilized-residual'),'V114 receiver residual policy active');
ok(L.rbResidualPolicyActive('v114-centered-stabilized-residual'),'V114 RB residual policy active');
ok(L.UNIT_V114.environmentAlign===true,'V114 environment alignment enabled');
const aligned=L.environmentAlignToHistoricalCenter(.20,.15,.05);
ok(Math.abs(aligned-.10)<1e-12,'environment alignment preserves distance from current center around historical center');
ok(Math.abs(L.environmentAlignToHistoricalCenter(.15,.15,.05)-.05)<1e-12,'current environment center maps exactly to historical center');
const hist=[-0.30,-0.20,-0.10,0.00,0.10,0.20,0.30,0.40];
const med=L.medianValue(hist);
const score=L.continuousPercentileValue(hist,med,true);
ok(Math.abs(score-50)<1e-9,'historical median maps to quality 50');
const src=code;
ok(src.includes("recPositions=receiverResidualPolicyActive(receiverPolicy) ? ['WR','TE']"),'V114 receiver excludes RB/FB');
ok(src.includes('r.receiverResidualEpa=receiverResidualPolicyActive(receiverPolicy)'),'V114 receiver uses residual rather than raw receiving EPA');
ok(src.includes('const rbRecvResidual=rbResidualPolicyActive(rbPolicy) ? partialResidual'),'V114/V115 RB receiving residual path retained');
ok(src.includes('r.receiverCalibratedResidual'),'receiver calibrated signal exposed');
ok(src.includes('r.rbCalibratedComposite'),'RB calibrated signal exposed');
console.log(`PASS: V114 Receiver/RB centering + residual policy (${n} checks)`);
