const fs=require('fs'), vm=require('vm'), path=require('path');
const root=path.resolve(__dirname,'..');
const code=fs.readFileSync(path.join(root,'model/live_profiles.js'),'utf8');
const sandbox={window:{},console}; vm.runInNewContext(code,sandbox);
const L=sandbox.window.FORCE_LIVE_PROFILE;
let n=0; const ok=(x,m)=>{n++; if(!x) throw new Error(m)};
const near=(a,b,t=1e-9)=>Math.abs(a-b)<=t;
ok(near(L.CONTEXT_SCALE.livePenaltyWeights.epa,.40)&&near(L.CONTEXT_SCALE.livePenaltyWeights.wpa,.25)&&near(L.CONTEXT_SCALE.livePenaltyWeights.firstDown,.20)&&near(L.CONTEXT_SCALE.livePenaltyWeights.erasedTd,.15),'approved 40/25/20/15 blend must be restored');
const cal={epa_per_game_rms:2,wpa_per_game_rms:.04,first_downs_per_game_rms:1,erased_tds_per_game_rms:.25,epa_weight:.4,wpa_weight:.25,first_down_weight:.2,erased_td_weight:.15,softness:2,prior_equivalent_games:3};
const neutralPrior={games:17,net_penalty_epa:0,net_penalty_wpa:0,first_downs_for:0,first_downs_against:0,tds_negated_benefit:0,tds_negated_harm:0};
const neutral=L.livePenaltyImpactScore({netPenaltyEpaTotal:0,netPenaltyWpaTotal:0,netFirstDownsTotal:0,netTdsNegatedTotal:0},2,neutralPrior,cal);
ok(near(neutral,50),'neutral four-component context must score 50');
const good=L.livePenaltyImpactScore({netPenaltyEpaTotal:4,netPenaltyWpaTotal:.08,netFirstDownsTotal:2,netTdsNegatedTotal:1},2,neutralPrior,cal);
ok(good>50,'positive causal/event impact must score above neutral');
const epaOnly=L.causalPenaltyScoreFromAverages(2,0,0,0,cal);
const firstOnly=L.causalPenaltyScoreFromAverages(0,0,1,0,cal);
ok(epaOnly>firstOnly,'40% EPA component must outweigh equal-standardized 20% first-down component');
const turnoverAuditA={netPenaltyEpaTotal:4,netPenaltyWpaTotal:.08,netFirstDownsTotal:2,netTdsNegatedTotal:1,netTurnoversNegatedTotal:999};
const turnoverAuditB={...turnoverAuditA,netTurnoversNegatedTotal:-999};
ok(near(L.livePenaltyImpactScore(turnoverAuditA,2,neutralPrior,cal),L.livePenaltyImpactScore(turnoverAuditB,2,neutralPrior,cal)),'erased-turnover audit count must not be separately double-counted');
const app=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');
ok(app.includes('40% causal penalty EPA')&&app.includes('25% causal penalty WPA')&&app.includes('20% net first downs via penalty')&&app.includes('15% net touchdowns erased by penalty'),'approved method must be surfaced in UI');
ok(app.includes('TURNOVERS ERASED BY PENALTY'),'erased turnovers must remain auditable');
ok(app.includes('3RD/4TH-DOWN DRIVE SAVES'),'drive saves must remain auditable');
console.log(`PASS: V88 approved causal penalty scoring (${n} checks)`);
