const fs=require('fs'), vm=require('vm'), path=require('path');
const root=path.resolve(__dirname,'..');
const code=fs.readFileSync(path.join(root,'model/live_profiles.js'),'utf8');
const sandbox={window:{},console}; vm.runInNewContext(code,sandbox);
const L=sandbox.window.FORCE_LIVE_PROFILE;
let n=0; const ok=(x,m)=>{n++;if(!x)throw new Error(m)};
const near=(a,b,t=1e-9)=>Math.abs(a-b)<=t;
ok(near(L.centeredContextScore(0,4),50),'neutral centered score must be 50');
ok(L.centeredContextScore(4,4)>50,'positive context must score above 50');
ok(L.centeredContextScore(-4,4)<50,'negative context must score below 50');
ok(L.centeredContextScore(8,4)>L.centeredContextScore(4,4),'context mapping must be monotonic positive');
ok(L.centeredContextScore(-8,4)<L.centeredContextScore(-4,4),'context mapping must be monotonic negative');
const neutralPen=L.historicalPenaltyImpactScore({net_pen_epa:0,pen_wp_swing:0},17);
ok(near(neutralPen,50),'zero EPA/WPA penalty context must score 50');
const posPen=L.historicalPenaltyImpactScore({net_pen_epa:17,pen_wp_swing:.5},17);
const negPen=L.historicalPenaltyImpactScore({net_pen_epa:-17,pen_wp_swing:-.5},17);
ok(posPen>50 && negPen<50,'historical penalty impact must preserve direction');
const g1=L.livePenaltyImpactScore(15,1), g4=L.livePenaltyImpactScore(15,4);
ok(g1>50 && near(g4,g1),'V97+ current-season-only penalty impact must not inherit a prior or change solely from sample count');
const unshrunk=L.causalPenaltyScoreFromAverages(15,0);
ok(near(g1,unshrunk),'game-1 live penalty impact must equal the current-season causal score when prior_equivalent_games is zero');
const app=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');
ok(app.includes('function luckContextScore'),'luck 0–100 mapper missing');
ok(app.includes('function spreadContextScore'),'spread 0–100 mapper missing');
ok(app.includes('0–100 · 50 neutral'),'context UI should explain unified scale');
ok(app.includes('marketGames ?? 0) >= Number(minGames)'),'four-game market-history gate must remain');
ok(app.includes("return contextScore(Number(ai.residual),4.0)"),'spread residual should map to centered 0–100 score');
ok(app.includes('40/25/20/15') && app.includes('score-aware EPA'),'penalty blend explanation missing');
ok(!app.includes('Penalty impact</span><strong class="${penUnavailable?\'\':Number(pen.net_pen_yards_per_game'), 'context card should not expose raw yard value as headline penalty score');
console.log(`OK: ${n} V62 context-score assertions`);
