const fs=require('fs');
const app=fs.readFileSync('assets/app.js','utf8');
const server=fs.readFileSync('force_server.py','utf8');
const bat=fs.readFileSync('serve_local.bat','utf8');
let n=0; const ok=(x,m)=>{n++; if(!x) throw new Error(m)};
ok(app.includes("const FORCE_DIAG_VERSION = 'V92-DIAG-1'"),'V92 client version missing');
ok(app.includes("diagnosticFetch('health'"),'client does not verify server identity');
ok(app.includes("health?.app_version!=='V92'"),'client does not reject wrong FORCE server version');
ok(app.includes("S.liveTeamStats = canonicalWeeklyRows(teamResult.value, 'team')"),'team refresh still accumulates old browser rows');
ok(app.includes("S.livePlayerStats = canonicalWeeklyRows(playerResult.value, 'player')"),'player refresh still accumulates old browser rows');
ok(!app.includes("S.liveTeamStats = mergeWeeklyRows"),'legacy client merge is still active');
ok(app.includes("diag('schedule:refresh-queued'"),'refreshes during startup are not queued');
ok(app.includes("diag('schedule:refresh-dequeued'"),'queued refreshes are not executed');
ok(!app.includes("schedule:refresh-skipped"),'refresh request can still be silently discarded');
ok(app.includes("bootstrap:verification-retry"),'initial incomplete data is not automatically re-verified');
ok(app.includes("return 'Connecting…'"),'initial state is not distinguished from offline');
ok(server.includes("APP_VERSION = 'V92'"),'server V92 identity missing');
ok(server.includes("if path == '/api/health':"),'health endpoint missing');
ok(server.includes("Port {PORT} is already in use by another application"),'port collision guard missing');
ok(!/^start http:\/\/localhost:8080/m.test(bat),'launcher still opens browser before server bind');
console.log(`PASS: V92 canonical refresh/bootstrap fix (${n} checks)`);
