const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');
let n=0;const ok=(x,m)=>{n++;if(!x)throw new Error(m)};
const a=app.indexOf('function week2EntryState(t)'), b=app.indexOf('function unitAudit(',a);
ok(a>=0&&b>a,'V99 ledger functions must exist');
const code=app.slice(a,b);
ok(code.includes("Object.keys(D.teams||{}).sort()"),'ledger must default to all canonical teams');
ok(code.includes('const entry=week2EntryState(t)'),'ledger must use frozen Week-2 entry state');
ok(code.includes('preserveV98PassRush:true'),'Week-2 entry baseline must preserve V98 historical Pass Rush semantics');
ok(code.includes('const resultElo=causalNow-Number(entry.causalCoreElo||0)'),'result/core movement must be explicit');
ok(code.includes('const regimeElo=regimeNow-Number(entry.regimeElo||0)'),'regime movement must be explicit');
ok(code.includes('const retrospectiveElo=retroNow-Number(entry.retrospectiveElo||0)'),'retrospective movement must be explicit');
ok(code.includes('const unitBridgeElo=Number(current.unitBridge?.eloDelta||0)-Number(entry.unitBridge?.eloDelta||0)'),'unit movement must be explicit');
ok(code.includes('const qbElo=currentQb-entryQb'),'QB movement must be explicit');
ok(code.includes('const computedElo=Number(entry.elo)+resultElo+regimeElo+retrospectiveElo+unitBridgeElo+qbElo'),'ledger must reconcile from baseline plus named deltas');
ok(code.includes('const residual=Number(current.elo)-computedElo'),'ledger must expose unexplained residual');
ok(!/if\s*\(\s*t\s*===?\s*['\"]KC['\"]/.test(code),'ledger must not special-case Kansas City');
ok(!/if\s*\(\s*t\s*===?\s*['\"]DEN['\"]/.test(code),'ledger must not special-case Denver');
console.log(`PASS: V99 32-team rating-ledger contract (${n} checks)`);
