const fs=require('fs');
const app=fs.readFileSync('assets/app.js','utf8');
const live=fs.readFileSync('model/live_profiles.js','utf8');
const server=fs.readFileSync('force_server.py','utf8');
let n=0; const ok=(x,m)=>{if(!x)throw new Error(m);n++;};
ok(app.includes('expected FORCE V121'),'app must require current V107 server identity');
ok(server.includes("APP_VERSION = 'V121'"),'server must advertise current V107');
ok(server.includes('home_coverage_pass_successes'),'server must expose PBP pass success counts');
ok(server.includes("'17'" ) || server.includes('range(1,max_window+1)'),'historical reference must support full-season windows');
ok(live.includes("v106-current-season-stabilized"),'V106 QB policy must exist');
ok(live.includes('epaStabilizerAttempts:150.0'),'EPA reliability stabilizer must be explicit');
ok(live.includes('successStabilizerAttempts:100.0'),'success reliability stabilizer must be explicit');
ok(live.includes('cpoeStabilizerAttempts:60.0'),'CPOE reliability stabilizer must be explicit');
ok(live.includes('passEpaWeight:0.65'),'EPA core weight must be 65%');
ok(live.includes('passSuccessWeight:0.20'),'success core weight must be 20%');
ok(live.includes('cpoeWeight:0.15'),'CPOE core weight must be 15%');
ok(live.includes('currentLeagueQbEpa'),'EPA must shrink toward current-season league environment');
ok(live.includes('currentLeagueQbSuccess'),'success must shrink toward current-season league environment');
ok(live.includes('historical-full-season-scale'),'V106 must use history for scale rather than same-sized sample rank');
console.log(`PASS: V106 contract (${n} checks)`);
