const fs=require('fs'), path=require('path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');
let n=0; const ok=(x,m)=>{n++; if(!x) throw new Error(m)};
ok(app.includes('<span>FORCE change</span>'),'postgame cards must label FORCE change');
ok(app.includes("${post.awayPowerDelta >= 0 ? '+' : ''}${fmt(post.awayPowerDelta)} FORCE"),'away postgame card must display FORCE delta');
ok(app.includes("${post.homePowerDelta >= 0 ? '+' : ''}${fmt(post.homePowerDelta)} FORCE"),'home postgame card must display FORCE delta');
ok(!app.includes('${fmt(post.awayDelta)} Elo</strong>'),'active rematch card must not lead with Elo change');
ok(app.includes('Pregame → Postgame'),'unit update must use customer-facing pregame/postgame wording');
ok(!app.includes('Pregame → canonical current profile'),'canonical profile wording must be removed from active UI');
ok(!app.includes('Live bridge estimate.'),'live-bridge wording must be removed from active UI');
ok(!app.includes('same site · next-week blend'),'next-week blend chip must be removed from active UI');
ok(app.includes('<span>Predicted rematch line</span>'),'rematch line must use concise customer-facing label');
ok(app.includes('<span>Predicted rematch score</span>'),'rematch score must use concise customer-facing label');
ok(app.includes('<div class="exact"><span>Predicted final score</span>'),'FORCEcast score should read Predicted final score');
ok(!app.includes("'.matchup-analysis'"),'V76 keeps visual matchup-analysis cards in exports');
ok(app.includes("'.matchup-strengths'"),'strengths/weaknesses must be stripped from exports');
ok(app.includes('matchup-pair matchup-strengths'),'strength section needs export-targetable class');
console.log(`OK: ${n} V68/V76 customer-facing rematch/export assertions`);
