const fs=require('fs'), path=require('path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8');
let n=0; const ok=(x,m)=>{n++; if(!x) throw new Error(m)};
ok(app.includes("['slate', 'FORCEcast Slate']"),'top navigation must expose FORCEcast Slate');
ok(app.includes('function forcecastSlatePage()'),'slate page renderer missing');
ok(app.includes('const audit=forecastAudit(g,ratings), fc=audit.fc, proj=audit.proj'),'slate must reuse canonical FORCEcast + exact-score projection');
ok(app.includes('Pred final') && app.includes('Win'),'slate must show predicted final and win columns');
ok(app.includes('Math.round((1-fc.probability)*100)') && app.includes('Math.round(fc.probability*100)'),'slate must show both win probabilities');
ok(app.includes('id="slateWeek"'),'slate week selector missing');
ok(app.includes("page === 'slate' ? forcecastSlatePage()"),'slate route missing');
ok(app.includes("if (page === 'slate') return `FORCEcast Slate · Week ${Number(S.slateWeek)||currentWeekNumber()}`"),'slate export label missing');
ok(app.includes("if (clone.querySelector('.slate-board'))"),'slate must have single-page export special case');
ok(app.includes('let the canvas grow vertically instead of paginating'),'slate export must explicitly bypass ordinary pagination');
ok(app.includes("'.slate-controls'"),'week selector must be stripped from social export');
ok(css.includes('.slate-board{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))'),'slate two-column board CSS missing');
ok(css.includes('.slate-team-row') && css.includes('.slate-favorite'),'slate score/probability rows missing styling');
console.log(`OK: ${n} V79 FORCEcast Slate assertions`);
