const fs=require('fs'), vm=require('vm'), path=require('path');
const root=path.resolve(__dirname,'..');
const ctx={window:{}}; vm.createContext(ctx);
for(const rel of ['data/model-data.js','data/matchup-data.js','model/forecast_v2.js','model/live_profiles.js']) vm.runInContext(fs.readFileSync(path.join(root,rel),'utf8'),ctx,{filename:rel});
const D=ctx.window.MODEL_DATA, M=ctx.window.MATCHUP_DATA, F=ctx.window.SIGNAL_FORECAST_V2, LP=ctx.window.FORCE_LIVE_PROFILE;
if(!D||!M||!F||!LP) throw new Error('missing model modules');
const teams=Object.keys(D.teams);
if(teams.length!==32) throw new Error('expected 32 teams');

const pairs=[]; const rest=teams.filter(t=>!['KC','DEN'].includes(t));
pairs.push(['KC','DEN']); for(let i=0;i<rest.length;i+=2) pairs.push([rest[i],rest[i+1]]);
const teamRows=[], playerRows=[], schedule=[], history={};
function teamRow(team,opp,quality){
  const elite=quality===1, bad=quality===-1;
  return {
    season:'2026',week:'1',season_type:'REG',game_id:`2026_01_${team}_${opp}`,team,opponent_team:opp,
    attempts:String(elite?34:bad?38:32), sacks_suffered:String(elite?0:bad?5:2),
    passing_epa:String(elite?12:bad?-10:2), passing_cpoe:String(elite?8:bad?-8:0),
    carries:String(elite?30:bad?22:26), rushing_epa:String(elite?9:bad?-6:1),
    targets:String(elite?32:bad?36:30), receiving_epa:String(elite?11:bad?-8:2),
    penalties:String(elite?2:bad?8:4), penalty_yards:String(elite?15:bad?70:35),
    // Defensive events generated by this team's front.
    def_qb_hits:String(elite?18:bad?1:5), def_sacks:String(elite?4:bad?0:2)
  };
}
function addPlayers(team,opp,quality){
  const elite=quality===1, bad=quality===-1;
  playerRows.push({season:'2026',week:'1',season_type:'REG',game_id:`2026_01_${team}_${opp}`,team,opponent_team:opp,position:'QB',position_group:'QB',player_display_name:`${team} QB`,attempts:String(elite?34:bad?38:32),sacks_suffered:String(elite?0:bad?5:2),passing_epa:String(elite?12:bad?-10:2),passing_cpoe:String(elite?8:bad?-8:0),carries:'4',rushing_epa:String(elite?2:bad?-1:0.2),targets:'0',receiving_epa:'0',def_penalty:'0',def_penalty_yards:'0'});
  playerRows.push({season:'2026',week:'1',season_type:'REG',game_id:`2026_01_${team}_${opp}`,team,opponent_team:opp,position:'RB',position_group:'RB',player_display_name:`${team} RB`,attempts:'0',sacks_suffered:'0',passing_epa:'0',passing_cpoe:'',carries:String(elite?24:bad?17:20),rushing_epa:String(elite?8:bad?-5:1),targets:'5',receiving_epa:String(elite?2:bad?-1:0.3),def_penalty:'0',def_penalty_yards:'0'});
  playerRows.push({season:'2026',week:'1',season_type:'REG',game_id:`2026_01_${team}_${opp}`,team,opponent_team:opp,position:'WR',position_group:'WR',player_display_name:`${team} WR`,attempts:'0',sacks_suffered:'0',passing_epa:'0',passing_cpoe:'',carries:'0',rushing_epa:'0',targets:String(elite?15:bad?13:12),receiving_epa:String(elite?7:bad?-5:1),def_penalty:String(elite?1:bad?6:3),def_penalty_yards:String(elite?5:bad?55:25)});
}
for(const [a,b] of pairs){
  const qa=a==='KC'?1:a==='DEN'?-1:0, qb=b==='KC'?1:b==='DEN'?-1:0;
  teamRows.push(teamRow(a,b,qa),teamRow(b,a,qb)); addPlayers(a,b,qa); addPlayers(b,a,qb);
  const home=a, away=b, hs=home==='KC'?31:home==='DEN'?10:24, as=away==='KC'?31:away==='DEN'?10:20;
  const g={week:1,date:'2026-09-14',home,away,homeScore:hs,awayScore:as}; schedule.push(g);
  history[`1|2026-09-14|${away}|${home}`]={independent:{probability:0.52}};
}
const before=LP.buildProfiles({teamRows:[],playerRows:[],priorProfiles:M.profiles,schedule:[],gameHistory:{},teamIds:teams,priorGames:1});
const after=LP.buildProfiles({teamRows,playerRows,priorProfiles:M.profiles,schedule,gameHistory:history,teamIds:teams,priorGames:1});
const kb=before.KC, ka=after.KC, db=before.DEN, da=after.DEN;
const fails=[]; const checks=[];
function check(name,cond,detail=''){ checks.push({name,ok:!!cond,detail}); if(!cond) fails.push(`${name}${detail?' :: '+detail:''}`); }
function finite(v){return Number.isFinite(Number(v));}
function changed(a,b,eps=1e-9){return finite(a)&&finite(b)&&Math.abs(Number(a)-Number(b))>eps;}
function up(name,a,b){check(name, finite(a)&&finite(b)&&b>a,`${a} -> ${b}`);}
function down(name,a,b){check(name, finite(a)&&finite(b)&&b<a,`${a} -> ${b}`);}

const idx=['offenseIndex','olIndex','frontIndex','passRushIndex','runDefenseIndex','coverageIndex','qbIndex','receiverIndex','rushIndex','defenseIndex','offenseComposite'];
for(const k of idx){
  check(`KC ${k} finite/range`,finite(ka[k])&&ka[k]>=0&&ka[k]<=100,String(ka[k]));
  check(`DEN ${k} finite/range`,finite(da[k])&&da[k]>=0&&da[k]<=100,String(da[k]));
  up(`KC elite game improves ${k}`,Number(kb[k]),Number(ka[k]));
  down(`DEN poor game lowers ${k}`,Number(db[k]),Number(da[k]));
}
const offExpected=.45*ka.offenseIndex+.25*ka.qbIndex+.15*ka.receiverIndex+.15*ka.olIndex;
const defExpected=.36*ka.coverageIndex+.16*ka.passRushIndex+.28*ka.runDefenseIndex+.20*ka.pointsAllowedPerDriveIndex;
check('offense raw composite formula',Math.abs(ka.offenseCompositeRaw-offExpected)<1e-8,`${ka.offenseCompositeRaw} vs ${offExpected}`);
check('offense calibrated composite formula',Math.abs(ka.offenseComposite-LP.calibrateComposite(offExpected,LP.COMPOSITE_V108.offense))<1e-8,`${ka.offenseComposite}`);
check('defense raw composite formula',Math.abs(ka.defenseCompositeRaw-defExpected)<1e-8,`${ka.defenseCompositeRaw} vs ${defExpected}`);
check('defense calibrated composite formula',Math.abs(ka.defenseIndex-LP.calibrateComposite(defExpected,LP.COMPOSITE_V108.defense))<1e-8,`${ka.defenseIndex}`);

up('KC stabilized offensive EPA',Number(kb.off_epa),Number(ka.off_epa));
up('KC QB EPA/play',Number(kb.qb.epa_per_play),Number(ka.qb.epa_per_play));
check('KC live CPOE is true current CPOE, not legacy completion%',Math.abs(Number(ka.qb.cpoe)-Number(ka.qb.live_cpoe))<1e-9 && Math.abs(Number(ka.qb.cpoe))<20,`${ka.qb.cpoe}`);
check('KC legacy completion% preserved separately',finite(ka.qb.prior_completion_pct)&&ka.qb.prior_completion_pct>20,String(ka.qb.prior_completion_pct));
down('KC OL disruption allowed improves',Number(kb.ol.pressure_rate_allowed),Number(ka.ol.pressure_rate_allowed));
check('KC OL sack rate live',finite(ka.ol.sack_rate_allowed)&&ka.ol.sack_rate_allowed===0,String(ka.ol.sack_rate_allowed));
up('KC defensive-front disruption rate improves',Number(kb.dl.pressure_rate),Number(ka.dl.pressure_rate));
check('KC front disruption captures ~half dropbacks',Number(ka.dl.pressure_rate)>=0.45,String(ka.dl.pressure_rate));
check('KC pass EPA allowed favorable',finite(ka.cov.press_adj_epa)&&ka.cov.press_adj_epa<0,String(ka.cov.press_adj_epa));
check('KC receivers live EPA/target favorable',finite(ka.receivers.adj_epa)&&ka.receivers.adj_epa>0,String(ka.receivers.adj_epa));
check('KC RB live rush EPA favorable',finite(ka.rb.rush_epa)&&ka.rb.rush_epa>0,String(ka.rb.rush_epa));
check('KC live scoring moves PPG for upward',ka.scoring.ppg_for>kb.scoring.ppg_for,`${kb.scoring.ppg_for}->${ka.scoring.ppg_for}`);
check('KC live scoring moves PPG against appropriately',finite(ka.scoring.ppg_against),String(ka.scoring.ppg_against));
check('KC luck switches to 2026',String(ka.luck.source).includes('2026')&&ka.luck.g===1,JSON.stringify(ka.luck));
check('KC penalty context live',ka.penalty.live===true&&finite(ka.penalty.net_pen_yards_per_game),JSON.stringify(ka.penalty));
check('KC positive penalty-yard swing in synthetic game',ka.penalty.net_pen_yards_per_game>0,String(ka.penalty.net_pen_yards_per_game));

const rawFields=['offEpa','passEpa','qbEpa','qbCpoe','rushEpa','recvEpa','sackAllowed','pressureAllowedRate','frontPressureRate','frontSackRate','runEpaAllowed','passEpaAllowed','cpoeAllowed','penaltyYardsNet'];
for(const k of rawFields) check(`_live.${k} finite`,finite(ka._live[k]),String(ka._live[k]));
check('live weight Week1 is 50%',Math.abs(ka._live.weight-.5)<1e-9,String(ka._live.weight));


// Exhaustive display-path smoke across all 32 teams after transform.
const displayPaths=[
  'offenseIndex','olIndex','frontIndex','passRushIndex','runDefenseIndex','coverageIndex','qbIndex','receiverIndex','rushIndex','defenseIndex','offenseComposite','off_epa',
  'qb.epa_per_play','qb.cpoe','ol.pressure_rate_allowed','ol.sack_rate_allowed','dl.pressure_rate','dl.sack_rate','dl.run_epa_allowed',
  'cov.press_adj_epa','cov.epa_allowed','cov.cpoe_allowed','receivers.adj_epa','rb.rush_epa',
  'luck.w','luck.l','luck.g','luck.exp_w','luck.exp_l','luck.luck','luck.luck_pct',
  'penalty.net_pen_yards','penalty.net_pen_yards_per_game','penalty.pen_count_for','penalty.pen_count_against','penalty.pen_yards_for','penalty.pen_yards_against',
  'scoring.ppg_for','scoring.ppg_against','_live.games','_live.weight','_live.offEpa','_live.passEpa','_live.qbEpa','_live.qbCpoe','_live.rushEpa','_live.recvEpa',
  '_live.sackAllowed','_live.pressureAllowedRate','_live.frontPressureRate','_live.frontSackRate','_live.runEpaAllowed','_live.passEpaAllowed','_live.cpoeAllowed','_live.penaltyYardsNet'
];
function getPath(o,path){return path.split('.').reduce((a,k)=>a==null?undefined:a[k],o);}
for(const t of teams){
  const p=after[t];
  for(const pathName of displayPaths){
    const v=getPath(p,pathName);
    check(`${t} ${pathName} finite`,finite(v),String(v));
  }
  for(const k of idx) check(`${t} ${k} bounded`,p[k]>=0&&p[k]<=100,String(p[k]));
  const offRaw=.45*p.offenseIndex+.25*p.qbIndex+.15*p.receiverIndex+.15*p.olIndex;
  check(`${t} offense raw formula consistent`,Math.abs(p.offenseCompositeRaw-offRaw)<1e-8,String(p.offenseCompositeRaw));
  check(`${t} offense calibrated formula consistent`,Math.abs(p.offenseComposite-LP.calibrateComposite(offRaw,LP.COMPOSITE_V108.offense))<1e-8,String(p.offenseComposite));
  const defRaw=.36*p.coverageIndex+.16*p.passRushIndex+.28*p.runDefenseIndex+.20*p.pointsAllowedPerDriveIndex;
  check(`${t} defense raw formula consistent`,Math.abs(p.defenseCompositeRaw-defRaw)<1e-8,String(p.defenseCompositeRaw));
  check(`${t} defense calibrated formula consistent`,Math.abs(p.defenseIndex-LP.calibrateComposite(defRaw,LP.COMPOSITE_V108.defense))<1e-8,String(p.defenseIndex));
}

// Result/Elo + QB-return invariants.
const meta=D.meta, cfg=D.config;
function forceScore(elo){const m=meta.meanElo,lo=meta.anchorMin,hi=meta.anchorMax;const out=elo>=m?50+50*(elo-m)/(hi-m):50-50*(m-elo)/(m-lo);return Math.max(0,Math.min(100,out));}
const preKC=D.rankings.find(x=>x.team==='KC').elo, preDEN=D.rankings.find(x=>x.team==='DEN').elo;
const ph=F.independentProbability(preKC,preDEN,cfg.hfa,cfg.scale);
const margin=21, mult=Math.log(margin+1)*2.2/(2.2+.001*Math.abs((preKC+cfg.hfa)-preDEN));
const delta=cfg.k*mult*(1-ph), postKC=preKC+delta, postDEN=preDEN-delta;
up('KC Elo after 21-point win',preKC,postKC); down('DEN Elo after loss',preDEN,postDEN);
up('KC base FORCE after win',forceScore(preKC),forceScore(postKC));
const restore=47.3;
up('KC QB-adjusted FORCE after win',forceScore(preKC+restore),forceScore(postKC+restore));
const preScenario=LP.applyQbCarryoverScenario(kb,forceScore(preKC),forceScore(preKC+restore)).profile;
const postScenario=LP.applyQbCarryoverScenario(ka,forceScore(postKC),forceScore(postKC+restore)).profile;
up('KC QB-adjusted offense after elite win',preScenario.offenseComposite,postScenario.offenseComposite);
up('KC QB-adjusted QB unit after elite win',preScenario.qbIndex,postScenario.qbIndex);
check('QB carryover leaves defense unchanged',Math.abs(postScenario.defenseIndex-ka.defenseIndex)<1e-9,`${ka.defenseIndex}->${postScenario.defenseIndex}`);
check('QB carryover leaves OL unchanged',Math.abs(postScenario.olIndex-ka.olIndex)<1e-9,`${ka.olIndex}->${postScenario.olIndex}`);
check('QB carryover leaves front unchanged',Math.abs(postScenario.frontIndex-ka.frontIndex)<1e-9,`${ka.frontIndex}->${postScenario.frontIndex}`);
check('QB carryover leaves pass rush unchanged',Math.abs(postScenario.passRushIndex-ka.passRushIndex)<1e-9,`${ka.passRushIndex}->${postScenario.passRushIndex}`);
check('QB carryover leaves run defense unchanged',Math.abs(postScenario.runDefenseIndex-ka.runDefenseIndex)<1e-9,`${ka.runDefenseIndex}->${postScenario.runDefenseIndex}`);

// Same-site independent rematch must move toward the winner after its rating rises.
const preP=F.independentProbability(preKC,preDEN,cfg.hfa,cfg.scale), postP=F.independentProbability(postKC,postDEN,cfg.hfa,cfg.scale);
up('same-site rematch win probability moves toward KC',preP,postP);

const snapshot={
  KC:{before:Object.fromEntries(idx.map(k=>[k,kb[k]])),after:Object.fromEntries(idx.map(k=>[k,ka[k]])),raw:{off_epa:ka.off_epa,qb_epa:ka.qb.epa_per_play,qb_cpoe:ka.qb.cpoe,ol_pressure_allowed:ka.ol.pressure_rate_allowed,front_disruption:ka.dl.pressure_rate,coverage_epa_allowed:ka.cov.press_adj_epa,recv_epa_target:ka.receivers.adj_epa,rb_rush_epa:ka.rb.rush_epa,penalty_yards_game:ka.penalty.net_pen_yards_per_game,luck:ka.luck.luck}},
  force:{pre:forceScore(preKC),post:forceScore(postKC),preQBAdjusted:forceScore(preKC+restore),postQBAdjusted:forceScore(postKC+restore),eloDelta:delta},
  scenario:{preOffense:preScenario.offenseComposite,postOffense:postScenario.offenseComposite,preQB:preScenario.qbIndex,postQB:postScenario.qbIndex},
  checks:checks.length,failures:fails
};
fs.writeFileSync(path.join(root,'benchmarks/v27_metric_smoke.json'),JSON.stringify(snapshot,null,2));
if(fails.length){ console.error(fails.join('\n')); process.exit(1); }
console.log(`V27 full metric transform smoke PASS (${checks.length} checks)`);
console.log(JSON.stringify(snapshot,null,2));
