const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');
let n=0; const ok=(x,m)=>{n++; if(!x) throw new Error(m)};
const start=app.indexOf("  const NFL_SCHEDULE_TIME_ZONE = 'America/New_York';");
const endMarker='  window.FORCE_FORMAT_KICKOFF_TIME = formatKickoffTime;';
const end=app.indexOf(endMarker,start);
ok(start>=0 && end>start,'shared kickoff formatter block missing');
const code=app.slice(start,end+endMarker.length);
const ctx={window:{},Intl,Date,Number,String,Object}; vm.createContext(ctx); vm.runInContext(code,ctx);
const f=ctx.window.FORCE_FORMAT_KICKOFF_TIME;
ok(typeof f==='function','debug kickoff formatter not exposed');
ok(f('2026-09-27','20:20','America/New_York')==='8:20 PM ET','Eastern display wrong');
ok(f('2026-09-27','20:20','America/Chicago')==='7:20 PM CT','Central display wrong');
ok(f('2026-09-27','20:20','America/Denver')==='6:20 PM MT','Mountain display wrong');
ok(f('2026-09-27','20:20','America/Los_Angeles')==='5:20 PM PT','Pacific display wrong');
ok(f('2026-12-20','20:20','America/Chicago')==='7:20 PM CT','standard-time conversion wrong');
ok(!app.includes("g.time?` · ${g.time}`"),'slate still leaks raw military time');
ok(!app.includes("g.time ? ' · ' + g.time : ''"),'game header still leaks raw military time');
ok((app.match(/formatKickoffTime\(g\.date,g\.time\)/g)||[]).length>=3,'shared formatter not used on all game-time surfaces');
console.log(`OK: ${n} V121 kickoff-time assertions`);
