const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8');
let n=0; const ok=(x,m)=>{n++;if(!x)throw new Error(m)};
ok(app.includes('function buildPlayoffExportPages(clone)'), 'special playoff export builder missing');
ok(app.includes("makeRoot(1200, 675, 'playoff-export-overview')"), '16:9 overview dimensions missing');
ok(app.includes("makeRoot(675, 1200, 'playoff-export-mobile')"), '9:16 mobile dimensions missing');
ok(app.includes("filename: `force-playoffs-${new Date().toISOString().slice(0, 10)}-overview-16x9.png`"), 'overview filename missing');
ok(app.includes("${conf.toLowerCase()}-mobile.png"), 'conference mobile filename missing');
ok(app.includes("clone.querySelector('.playoff-grid') ? buildPlayoffExportPages(clone) : null"), 'playoff export must bypass generic pagination');
ok(app.includes('page.width || config.layoutWidth'), 'per-page export widths missing');
ok(app.includes('page.scale || config.scale'), 'per-page export scale missing');
ok(css.includes('.playoff-export-overview-grid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important'), 'overview must show both conferences side-by-side');
ok(css.includes('.playoff-export-mobile'), 'mobile playoff export styles missing');
ok(app.includes("force-playoffs-${stamp}-overview-plus-mobile.zip"), 'dedicated playoff ZIP name missing');
ok(!app.includes("expected FORCE V121"), 'stale V121 client identity');
ok(app.includes("expected FORCE V124"), 'V123 client identity missing');
console.log(`OK: ${n} V121 playoff export assertions`);
