const fs=require('fs'), path=require('path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const logo=fs.readFileSync(path.join(root,'assets/force-vector-logo.svg'),'utf8');
const board=fs.readFileSync(path.join(root,'assets/force-vector-board.svg'),'utf8');
let n=0; const ok=(x,m)=>{n++;if(!x)throw new Error(m)};
ok(app.includes('assets/force-approved-mark.png'),'topbar must use approved PNG Vector-F mark');
ok(app.includes('assets/force-approved-board.png'),'About FORCE must use approved PNG identity board');
ok(index.includes('assets/force-approved-favicon.png'),'favicon must use approved PNG mark');
ok(app.includes('assets/force-approved-export-logo.png'),'export identity must use approved PNG asset');
ok(app.includes('Football Objective Rating & Comparative Efficiency'),'export identity must spell out FORCE');
ok(app.includes('async function inlineExportBrandImages'),'page-level brand SVGs must be inlined for PNG export');
ok(app.includes('Promise.all([inlineExportTeamLogos(clone), inlineExportBrandImages(clone)])'),'PNG pipeline must inline both team and FORCE brand images');
ok(css.includes('--brand-cyan:#32d5e8'),'V48 cyan product accent missing');
ok(css.includes('--brand-teal:#18c99b')&&css.includes('--brand-gold:#f2bb47')&&css.includes('--brand-crimson:#e84258'),'V48 signature colors missing');
ok(css.includes('url("force-yard-rail.svg")'),'field yard-rail page framing missing');
ok(board.includes('M0 22h11M0 42h11M0 62h11M0 82h11') || board.includes('M0 22h11'), 'identity board needs four minor ticks between major yard marks');
ok(app.includes('force-approved-export-logo.png'),'1–100 rating motif is preserved in approved PNG export asset');
ok(!app.includes('src="assets/force-field-logo.svg"'),'runtime must not use legacy field-arc logo');
console.log(`OK: ${n} V48 Vector-F brand assertions`);
