import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {DIR,units,pairs,benchmarkSpecs,finite,validateInput,category,rawValue,rawKey} from './architecture.mjs';
import {mean,quantile,rank,correlation,partial,distribution,cluster,CONVENTIONS,packing,mappedComparison} from './stats.mjs';
import {semanticContract} from './semantic_contract.mjs';
const verifiedFacts=JSON.parse(fs.readFileSync(DIR+'/inputs/independent_facts.json','utf8'));
export function analyze(x,unitMap=units,benchmarkMap=benchmarkSpecs){semanticContract(x,unitMap,benchmarkMap);validateInput(x);const ids=Object.keys(x.teams).sort(),rows=ids.map(t=>x.teams[t]),v=(section,k)=>rows.map(r=>r[section]?.[k]??null),def=k=>['coverageIndex','passRushIndex','runDefenseIndex','pointsAllowedPerDriveIndex','defenseIndex'].includes(k);
 const rankTeams=(section,k,higher=true)=>{const vals=v(section,k).map(z=>finite(z)?z*(higher?1:-1):null),rs=rank(vals);return ids.map((t,i)=>({team:t,value:v(section,k)[i],rank:finite(rs[i])?vals.filter(finite).length+1-rs[i]:null})).filter(z=>z.rank!==null).sort((a,b)=>a.rank-b.rank||a.team.localeCompare(b.team));};
 const distributions={},intermediate={},alignments={},tails={};
 for(const u of units){const display=distribution(v('display',u.key)),raw=distribution(rows.map(r=>rawValue(r,u)));const live=distribution(v('liveGrade',u.key));distributions[u.key]={label:u.label,rawScope:u.scope,display,packing:packing(v('display',u.key)),raw,rawKeyByTeam:Object.fromEntries(ids.map(t=>[t,rawKey(x.teams[t],u)])),liveGrade:live,clustering:cluster(display),bins:Object.fromEntries([[-Infinity,40],[40,50],[50,60],[60,70],[70,80],[80,90],[90,Infinity]].map(([lo,hi])=>[`${lo}..${hi}`,v('display',u.key).filter(z=>finite(z)&&z>=lo&&z<hi).length])),roundedDistinct:{rankingsInteger:new Set(v('display',u.key).map(z=>z.toFixed(0))).size,teamBoardOneDecimal:new Set(v('display',u.key).map(z=>z.toFixed(1))).size},displayRanks:rankTeams('display',u.key),rawRanks:(()=>{const vals=rows.map(r=>rawValue(r,u)*(u.higher?1:-1)),rr=rank(vals);return ids.map((team,i)=>({team,value:rawValue(rows[i],u),rank:33-rr[i]})).sort((a,b)=>a.rank-b.rank||a.team.localeCompare(b.team));})()};
  alignments[u.key]=benchmarkSpecs[u.key].map(([b,higher,boundary])=>{const y=v('benchmarks',b).map(z=>finite(z)?z*(higher?1:-1):null),r=correlation(v('display',u.key),y),br=rankTeams('benchmarks',b,higher),dr=rankTeams('display',u.key),loo=ids.map((_,i)=>correlation(v('display',u.key).filter((_,j)=>j!==i),y.filter((_,j)=>j!==i)).pearson).filter(finite);
   return {benchmark:b,direction:higher?'higher':'lower',boundary,category:category(u.key,b),...r,top5Overlap:dr.slice(0,5).filter(z=>br.slice(0,5).some(a=>a.team===z.team)).length,bottom5Overlap:dr.slice(-5).filter(z=>br.slice(-5).some(a=>a.team===z.team)).length,leaveOneTeamOutPearson:[Math.min(...loo),Math.max(...loo)],outliers:dr.map(z=>({...z,benchmarkRank:br.find(b=>b.team===z.team)?.rank??null,benchmarkValue:rows[ids.indexOf(z.team)].benchmarks[b]})).filter(z=>finite(z.benchmarkRank)&&Math.abs(z.rank-z.benchmarkRank)>=10),ranks:br};});
  const summary=z=>({team:z.team,rank:z.rank,display:z.value,raw:rawValue(x.teams[z.team],u),rawKey:rawKey(x.teams[z.team],u),benchmarks:benchmarkSpecs[u.key].slice(0,2).map(([key,,boundary])=>({key,value:x.teams[z.team].benchmarks[key],boundary})),interpretation:'Same-snapshot diagnostic; benchmark ranks/outliers retained separately, no independent predictive certification'});
  tails[u.key]={top5:distributions[u.key].displayRanks.slice(0,5).map(summary),bottom5:distributions[u.key].displayRanks.slice(-5).map(summary)};
 }
 for(const k of ['qbEpaPerPlay','qbStabilizedEpa','qbAnyA','qbPassSuccessRate','qbStabilizedSuccess','qbCpoe','qbStabilizedCpoe','recvEpa','receiverResidualEpa','receiverStabilizedResidual','receiverCalibratedResidual','rbRushEpa','rbRecvEpa','rbRecvResidualEpa','rbComposite','rbCompositeOrthogonal','rbStabilizedRushEpa','rbStabilizedRecvResidualEpa','rbStabilizedComposite','rbCalibratedComposite','pbpPressureAllowedRate','oppPassEpa','oppCpoe','frontPressureRate','frontSackRate','selectedPassRushComposite','oppRushEpa','offensivePointsPerDrive','defensivePointsPerDrive','offenseCompositeRaw','defenseCompositeRaw'])intermediate[k]={...distribution(v('raw',k)),ranks:rankTeams('raw',k,!['pbpPressureAllowedRate','oppPassEpa','oppCpoe','defensivePointsPerDrive','oppRushEpa'].includes(k))};
 const dependencies=pairs.map(([a,b])=>{const ua=units.find(u=>u.key===a),ub=units.find(u=>u.key===b),vx=v('display',a),vy=v('display',b),control=def(a)&&def(b)?'defEpa':'offEpa',adjacent=def(a)&&def(b)?'defensivePointsPerDrive':'offensivePointsPerDrive';return {a,b,display:correlation(vx,vy),rawQualityProxy:correlation(rows.map(r=>rawValue(r,ua)*(ua.higher?1:-1)),rows.map(r=>rawValue(r,ub)*(ub.higher?1:-1))),liveGrade:correlation(v('liveGrade',a),v('liveGrade',b)),partialCore:partial(vx,vy,[rows.map(r=>r.core)]),partialOutcome:{control,result:partial(vx,vy,[v('raw',control)])},partialCoreAndAdjacentOutcome:{controls:['core',adjacent],result:partial(vx,vy,[rows.map(r=>r.core),v('raw',adjacent)])}};});
 const discordance={};for(const [a,b] of [['receiverIndex','qbIndex'],['rbIndex','olIndex'],['coverageIndex','passRushIndex']]){
  const ra=rankTeams('display',a),rb=rankTeams('display',b);discordance[a+'__'+b]=ra.map(z=>({team:z.team,a,b,scoreA:z.value,rankA:z.rank,scoreB:rb.find(q=>q.team===z.team).value,rankB:rb.find(q=>q.team===z.team).rank,gap:z.rank-rb.find(q=>q.team===z.team).rank})).sort((x,y)=>Math.abs(y.gap)-Math.abs(x.gap)||x.team.localeCompare(y.team));
 }
 const receiver={beta:rows[0].raw.receiverOrthogonalBeta,unadjustedVsQbAttempt:correlation(v('raw','recvEpa'),v('raw','qbAttemptEpa')),residualVsQbAttempt:correlation(v('raw','receiverResidualEpa'),v('raw','qbAttemptEpa')),stabilizedVsQbAttempt:correlation(v('raw','receiverStabilizedResidual'),v('raw','qbAttemptEpa')),displayVsQbDisplay:correlation(v('display','receiverIndex'),v('display','qbIndex')),displayVsPassingEpa:correlation(v('display','receiverIndex'),v('raw','passEpa')),displayVsPassSuccess:correlation(v('display','receiverIndex'),v('raw','qbPassSuccessRate')),displayVsScoring:correlation(v('display','receiverIndex'),v('display','pointsScoredPerDriveIndex')),top5OverlapWithQb:distributions.receiverIndex.displayRanks.slice(0,5).filter(z=>distributions.qbIndex.displayRanks.slice(0,5).some(q=>q.team===z.team)).length,stabilizationIqrRatio:intermediate.receiverStabilizedResidual.iqr/intermediate.receiverResidualEpa.iqr,rawToHistoricalIqr:intermediate.receiverResidualEpa.iqr/(rows[0].historicalSpread.receiver.p75-rows[0].historicalSpread.receiver.p25)};
 const rb={rushVsDisplay:correlation(v('raw','rbRushEpa'),v('display','rbIndex')),receivingVsDisplay:correlation(v('raw','rbRecvResidualEpa'),v('display','rbIndex')),rushStabilizationIqrRatio:intermediate.rbStabilizedRushEpa.iqr/intermediate.rbRushEpa.iqr,recvStabilizationIqrRatio:intermediate.rbStabilizedRecvResidualEpa.iqr/intermediate.rbRecvResidualEpa.iqr,compositeStabilizationIqrRatio:intermediate.rbStabilizedComposite.iqr/intermediate.rbCompositeOrthogonal.iqr,rawToHistoricalIqr:intermediate.rbCompositeOrthogonal.iqr/(rows[0].historicalSpread.rb.p75-rows[0].historicalSpread.rb.p25)};
 const stageComparisons={};
 const compare=(key,field,ref,higher=true,scope='scalar mapping input')=>{stageComparisons[key]={field,scope,...mappedComparison(v('raw',field),rows[0].historicalSpread[ref],higher)};};
 compare('receiverIndex','receiverCalibratedResidual','receiver');compare('rbIndex','rbCalibratedComposite','rb');compare('qbIndex','qbStabilizedEpa','qb',true,'EPA component only; not whole multicomponent QB grade');
 // OL consumes opportunity-aligned references; do not pool references of different sample sizes.
 stageComparisons.olIndex={scope:'pass-protection disruption allowed; quality oriented; reference groups kept separate',strata:Object.fromEntries([...new Set(rows.map(r=>r.historicalSpread.ol.n))].sort((a,b)=>a-b).map(n=>{const group=rows.filter(r=>r.historicalSpread.ol.n===n);return [n,{teams:ids.filter(t=>x.teams[t].historicalSpread.ol.n===n),sampleLimit:group.length<12?'Too sparse for scale conclusions':'Single-snapshot descriptive comparison',...mappedComparison(group.map(r=>r.raw.pbpPressureAllowedRate),group[0].historicalSpread.ol,false)}];}))};
 stageComparisons.passRushIndex={scope:'Weekly grading uses current league disruption ranks, not historical CDF; selected composite is not ranked for those28. PFR uses opportunity-aligned charted composite reference.',strata:Object.fromEntries([...new Set(rows.filter(r=>r.metadata.passRushProvider==='pfr-advanced').map(r=>r.historicalSpread.passRush.n))].sort((a,b)=>a-b).map(n=>{const group=rows.filter(r=>r.metadata.passRushProvider==='pfr-advanced'&&r.historicalSpread.passRush.n===n);return [n,{nCurrent:group.length,sampleLimit:'Two-team strata cannot support compression conclusions',...mappedComparison(group.map(r=>r.raw.selectedPassRushComposite),group[0].historicalSpread.passRush)}];}))};
 for(const u of units)if(!stageComparisons[u.key])stageComparisons[u.key]={status:'NOT APPLICABLE',scope:['offenseComposite','defenseIndex'].includes(u.key)?'Already-normalized composite grades and analytic soft-tail transformation, not empirical historical CDF':'Current-league rank map (coverage includes CPOE); no comparable historical CDF'};
 const diagnoses={};for(const u of units){let shrink=null;if(u.key==='receiverIndex')shrink=receiver.stabilizationIqrRatio;if(u.key==='rbIndex')shrink=rb.compositeStabilizationIqrRatio;if(u.key==='qbIndex')shrink=intermediate.qbStabilizedEpa.iqr/intermediate.qbEpaPerPlay.iqr;
  const p=distributions[u.key].packing,normal=u.key==='receiverIndex'?'LIKELY':['olIndex','qbIndex'].includes(u.key)||p.conventions.centralPacking?'POSSIBLE':'NONE';
  diagnoses[u.key]={method:'ANALYST-ASSESSMENT BASED ON AUDIT EVIDENCE',stabilizationIqrRatio:shrink,conventions:p.conventions,normalizationConcern:normal,classification:u.key==='receiverIndex'?'Stabilization plus calibrated historical-CDF upper-band compression':u.key==='qbIndex'?'EPA-component attenuation; full grade wide':p.conventions.centralPacking?'Middle packing despite wide tails':'No lead under these measured facets',boundary:'Open MD-07/MD-08 boundary evidence, not a normalization selection. NONE is conditional; provider/component limits remain.'};}
 const bank=[];
 function add(t,key,reason){
  const row=x.teams[t],u=units.find(z=>z.key===key),rank=distributions[key].displayRanks.find(z=>z.team===t).rank;
  const nonFormulaChecks=alignments[key].filter(a=>a.category.startsWith('B.'));
  const selected=[...nonFormulaChecks,...alignments[key].filter(a=>!a.category.startsWith('B.'))].slice(0,2);
  const checks=selected.map(a=>({key:a.benchmark,value:row.benchmarks[a.benchmark],rank:a.ranks.find(q=>q.team===t)?.rank??null,boundary:a.boundary,category:a.category}));
  const officialFacts=verifiedFacts.teamFacts.filter(f=>f.team===t&&f.units.includes(key));
  const opposite=checks.some(b=>rank<=8&&b.rank>=25||rank>=25&&b.rank<=8),bothGap=checks.length===2&&checks.every(b=>Math.abs(rank-b.rank)>=10);
  const limited=['passRushIndex','olIndex'].includes(key);
  const classification=opposite||bothGap||limited?'QUESTIONABLE':'NO OPPOSITE-QUARTILE CONTRADICTION';
  const scope={qbIndex:'multicomponent QB outcome; checks are ingredients, not isolated skill',receiverIndex:'partially residualized receiving EPA with stabilization/prior; check yards and first downs are same-feed outcomes',rbIndex:'70/30 rushing/receiving EPA room with separate stabilizers and prior',olIndex:'pass protection only; public Offensive line label exceeds scope, and rushing check is a scope contrast',coverageIndex:'sack-free EPA plus CPOE allowed; passing outcomes also reflect pressure/opponents',passRushIndex:'provider '+row.metadata.passRushProvider+'; true charted pressure and hit/sack disruption are not interchangeable',runDefenseIndex:'current rush EPA allowed versus old run-stop prior; same-feed efficiency and first downs can disagree',pointsAllowedPerDriveIndex:'drive prevention outcome with neutral50 one-game prior, not a defender rating'}[key];
  const evidence=checks.map(c=>c.key+' rank '+c.rank+' (value '+c.value+')').join('; ');
  const caseNotes={
   'SF__qbIndex':'EPA and ANY/A both rank1 support own-component arithmetic; they cannot independently validate QB skill.',
   'SF__receiverIndex':'First-down rank1 and yards/target rank4 corroborate a receiving outcome tail that also coexists with top QB play; residual skill separation remains unresolved.',
   'BUF__rbIndex':'Room efficiency and first downs support this top tail; Cook official facts corroborate rushing production without certifying the 70/30 room construct.',
   'SF__olIndex':'Zero sacks corroborate protection, but are a subset of disrupted dropbacks; run YPC cannot certify an all-line rating.',
   'MIN__coverageIndex':'Best success-allowed rank but only rank11 yards/attempt: the favorable tail is not uniform across passing outcomes.',
   'MIN__passRushIndex':'Official sacks corroborate disruption, but do not turn the weekly hit/sack proxy into charted true pressure.',
   'TB__runDefenseIndex':'EPA tail and low yards allowed broadly align; first-down rank6 is less extreme and no isolated run-stopping attribution is identified.',
   'MIN__pointsAllowedPerDriveIndex':'Total points-against tail corroborates broad scoreboard prevention; qualifying offensive points and all scoreboard points differ.',
   'PHI__receiverIndex':'Displayed rank10 versus receiving ranks22/21 is a two-check mismatch even without opposite quartiles; strong WR relative to QB does not clear it.',
   'CHI__receiverIndex':'WR rank19 versus QB rank9 is cross-unit discordance; receiving outcomes rank14/12 are less weak than the displayed room grade.',
   'JAX__rbIndex':'Room rank9 versus efficiency ranks7/5 is not opposite-tail disagreement; this does not imply pass-protection OL must match rushing.',
   'TEN__rbIndex':'Low room grade and first-down rank31 coexist with midtable YPC rank18; strong pass-protection OL is not run-blocking proof.',
   'KC__coverageIndex':'Coverage rank4 versus rush rank29 illustrates distinct displayed archetypes; success rank12 is weaker than the yards/attempt tail.',
   'DET__coverageIndex':'Coverage rank30 and pass-outcome ranks31/27 agree directionally despite rush rank5; pressure effectiveness cannot certify coverage skill.',
   'JAX__coverageIndex':'Coverage rank10 versus success rank25 and yards/attempt rank31 is a two-check contradiction; EPA/CPOE, prior and context require separate tracing.',
   'NE__runDefenseIndex':'Worst displayed run grade is markedly weaker than both efficiency checks; an EPA-based tail is not validated by broad rushing outcomes.',
   'WAS__runDefenseIndex':'Displayed lower quartile conflicts with first-down rank5 and middling yards/attempt; EPA context and prior cannot be assumed interchangeable with first downs.',
   'BUF__runDefenseIndex':'Displayed rank29 is substantially weaker than yards rank15 and first-down rank19; prior/live blend is a construct lead, not proven formula failure.',
   'NYJ__runDefenseIndex':'Displayed upper quartile conflicts with both weaker efficiency checks; the optimistic EPA grade does not establish isolated defender talent.',
   'SF__runDefenseIndex':'Displayed rank20 understates both favorable yards and first-down ranks9/7; prior/live drift must remain open.',
   'LV__runDefenseIndex':'Displayed rank11 is substantially stronger than yards rank31 and tied first-down rank23.5; this is not a clean validity pass.'
  };
  let interpretation=t+' '+key+' displayed rank '+rank+': '+evidence+'. '+scope+'. ';
  interpretation+=(caseNotes[t+'__'+key]??'Frozen live/prior decomposition is retained below; no external certification.')+' ';
  interpretation+=opposite||bothGap?'Observed rank discordance warrants construct/prior investigation; no certified causal defect.':'No opposite-quartile contradiction is only a weak screen, not a validity pass.';
  if(t==='KC'&&key==='rbIndex')interpretation+=' Live '+row.liveGrade.rbIndex+', effective prior '+row.prior.rbIndex+', '+row.metadata.playerStatGames+' live games and '+row.metadata.priorGames+' prior games explain display drag; Walker facts corroborate production, not formula failure.';
  if(key==='runDefenseIndex')interpretation+=' Live grade '+row.liveGrade[key]+' versus effective prior '+row.prior[key]+'.';
  bank.push({team:t,unit:key,reason,raw:rawValue(row,u),rawKey:rawKey(row,u),display:row.display[key],rank,checks,officialFacts,classification,interpretation});
 }
 for(const key of ['qbIndex','receiverIndex','rbIndex','olIndex']){const d=distributions[key].displayRanks;add(d[0].team,key,'Highest displayed offense-unit tail');}
 add('KC','rbIndex','Owner-supplied case corrected to Walker currently on KC');
 for(const key of ['coverageIndex','passRushIndex','runDefenseIndex','pointsAllowedPerDriveIndex'])add(distributions[key].displayRanks[0].team,key,'Highest displayed defense-unit tail');
 for(const [pair,cases] of Object.entries(discordance))for(const c of [cases.find(c=>c.gap<0),cases.find(c=>c.gap>0)].filter(Boolean))add(c.team,c.a,'Discordance '+pair+': rank gap '+c.gap);
 for(const team of ['NE','WAS','BUF','NYJ','SF','LV'])add(team,'runDefenseIndex','Both non-formula rank gaps >=10');add('JAX','coverageIndex','Coverage same-feed discordance');
 const providers=Object.fromEntries([...new Set(rows.map(r=>r.metadata.passRushProvider))].sort().map(p=>{const teams=ids.filter(t=>x.teams[t].metadata.passRushProvider===p);return [p,{n:teams.length,teams,display:distribution(teams.map(t=>x.teams[t].display.passRushIndex)),raw:distribution(teams.map(t=>rawValue(x.teams[t],units.find(u=>u.key==='passRushIndex')))),boundary:'Nonrandom provider assignment; charted true pressure and weekly hit+sack proxy are not interchangeable.'}];}));
 const summary=units.map(u=>{const d=distributions[u.key],adj=dependencies.filter(p=>p.a===u.key||p.b===u.key).sort((a,b)=>Math.abs(b.display.pearson??0)-Math.abs(a.display.pearson??0))[0];const classes={qbIndex:'A',receiverIndex:'B',olIndex:'A',rbIndex:'B',coverageIndex:'A',passRushIndex:'E',runDefenseIndex:'B',pointsScoredPerDriveIndex:'A',pointsAllowedPerDriveIndex:'A',offenseComposite:'A',defenseIndex:'A',offenseIndex:'A'},classification=classes[u.key];return {key:u.key,label:u.label,displaySd:d.display.sd,displayMiddle80:d.display.middle80,rawSd:d.raw.sd,rawIqr:d.raw.iqr,clustering:d.clustering,strongestAdjacent:adj?{pair:[adj.a,adj.b],r:adj.display.pearson}:null,core:correlation(v('display',u.key),rows.map(r=>r.core)),teamOutcome:correlation(v('display',u.key),v('raw',def(u.key)?'defEpa':'offEpa')),benchmarkAlignment:alignments[u.key].map(a=>({key:a.benchmark,r:a.pearson,boundary:a.boundary})),bankResult:bank.filter(b=>b.unit===u.key).map(b=>({team:b.team,result:b.classification})),predictiveEvidence:'UNAVAILABLE',assessmentRationale:{qbIndex:'A only for own multicomponent outcome arithmetic; four checks are ingredients, EPA attenuation remains open',receiverIndex:'B: residualization helps but descriptive context association and calibrated upper-band compression remain',olIndex:'A internally as pass protection; D public label scope; sacks are part-whole evidence, rushing not validation',rbIndex:'B: directionally coherent room outcomes, weak context independence and confirmed prior-reference defect',coverageIndex:'Narrow A only for sack-free pass outcomes; same-feed checks do not independently certify coverage talent',passRushIndex:'E: mixed true-pressure and weekly proxy paths, no uniform independent charting benchmark',runDefenseIndex:'B: old run-stop prior/current EPA drift r=.081 and six two-benchmark rank discordances',pointsScoredPerDriveIndex:'A only as broad drive outcome, not position-group skill',pointsAllowedPerDriveIndex:'A only as broad drive outcome, not position-group skill',offenseComposite:'A arithmetic composite only, not independently validated new construct',defenseIndex:'A arithmetic composite only, not independently validated new construct',offenseIndex:'A diagnostic arithmetic only; sole benchmark is tautological'}[u.key],assessmentMethod:'ANALYST-ASSESSMENT BASED ON AUDIT EVIDENCE',internalConstructCoherence:classification,externalValidationStrength:'E. INSUFFICIENT — zero genuinely independent statistical benchmarks',publicLabelScope:u.key==='olIndex'?'D. Offensive line materially broader than pass protection':u.scope,md07:classification,normalization:diagnoses[u.key].normalizationConcern,rawDiagnosis:diagnoses[u.key].classification};});
 return {conventions:CONVENTIONS,stageComparisons,runPriorLive:correlation(v('prior','runDefenseIndex'),v('liveGrade','runDefenseIndex')),distributions,intermediate,dependencies,receiver,rb,discordance,alignments,tails,diagnoses,bank,providers,summary};
}
export function artifacts(a){return {'compression_robustness.json':{conventions:a.conventions,display:Object.fromEntries(Object.entries(a.distributions).map(([k,d])=>[k,d.packing])),mappedStages:a.stageComparisons,runPriorLive:a.runPriorLive},'unit_distributions.json':{conventions:a.conventions,units:a.distributions,intermediate:a.intermediate},'unit_dependencies.json':{pairs:a.dependencies,receiver:a.receiver,rb:a.rb,discordance:a.discordance,providers:a.providers},'benchmark_alignment.json':a.alignments,'pathology_bank.json':{criteria:a.conventions.pathology,cases:a.bank,extremes:a.tails},'unit_summary.json':{diagnosis:a.diagnoses,matrix:a.summary},'unit_audit.csv':['unit,display_sd,display_middle80,raw_sd,raw_iqr,clustering,md07,normalization',...a.summary.map(r=>[r.key,r.displaySd,r.displayMiddle80,r.rawSd,r.rawIqr,r.clustering,r.md07,r.normalization].join(','))].join('\n')+'\n'};}
export function serialize(a){const verify=o=>{if(typeof o==='number'&&!Number.isFinite(o))throw new Error('non-finite statistic cannot be serialized as null');if(o&&typeof o==='object')for(const v of Object.values(o))verify(v);};verify(a);return Object.fromEntries(Object.entries(artifacts(a)).map(([p,x])=>[p,typeof x==='string'?x:JSON.stringify(x,null,2)+'\n']));}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const x=JSON.parse(fs.readFileSync(DIR+'/inputs/current_snapshot.json','utf8'));const results=serialize(analyze(x));for(const [p,t] of Object.entries(results))fs.writeFileSync(DIR+'/results/'+p,t);console.log('MD07 current analysis: 12 units, 16 required pairs, 7 deterministic artifacts');
}
