import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {DIR,units,pairs,benchmarkSpecs,finite,validateInput} from './architecture.mjs';
import {mean,quantile,rank,correlation,partial,distribution,cluster,CONVENTIONS} from './stats.mjs';
const verifiedFacts=JSON.parse(fs.readFileSync(DIR+'/inputs/independent_facts.json','utf8'));
export function analyze(x){validateInput(x);const ids=Object.keys(x.teams).sort(),rows=ids.map(t=>x.teams[t]),v=(section,k)=>rows.map(r=>r[section]?.[k]??null),def=k=>['coverageIndex','passRushIndex','runDefenseIndex','pointsAllowedPerDriveIndex','defenseIndex'].includes(k);
 const rankTeams=(section,k,higher=true)=>{const vals=v(section,k).map(z=>finite(z)?z*(higher?1:-1):null),rs=rank(vals);return ids.map((t,i)=>({team:t,value:v(section,k)[i],rank:finite(rs[i])?vals.filter(finite).length+1-rs[i]:null})).filter(z=>z.rank!==null).sort((a,b)=>a.rank-b.rank||a.team.localeCompare(b.team));};
 const distributions={},intermediate={},alignments={},tails={};
 for(const u of units){const display=distribution(v('display',u.key)),raw=distribution(v('raw',u.raw));const live=distribution(v('liveGrade',u.key));distributions[u.key]={label:u.label,rawScope:u.scope,display,raw,liveGrade:live,clustering:cluster(display),bins:Object.fromEntries([[-Infinity,40],[40,50],[50,60],[60,70],[70,80],[80,90],[90,Infinity]].map(([lo,hi])=>[`${lo}..${hi}`,v('display',u.key).filter(z=>finite(z)&&z>=lo&&z<hi).length])),roundedDistinct:{rankingsInteger:new Set(v('display',u.key).map(z=>z.toFixed(0))).size,teamBoardOneDecimal:new Set(v('display',u.key).map(z=>z.toFixed(1))).size},displayRanks:rankTeams('display',u.key),rawRanks:rankTeams('raw',u.raw,u.higher)};
  alignments[u.key]=benchmarkSpecs[u.key].map(([b,higher,boundary])=>{const y=v('benchmarks',b).map(z=>finite(z)?z*(higher?1:-1):null),r=correlation(v('display',u.key),y),br=rankTeams('benchmarks',b,higher),dr=rankTeams('display',u.key),loo=ids.map((_,i)=>correlation(v('display',u.key).filter((_,j)=>j!==i),y.filter((_,j)=>j!==i)).pearson).filter(finite);
   return {benchmark:b,direction:higher?'higher':'lower',boundary,...r,top5Overlap:dr.slice(0,5).filter(z=>br.slice(0,5).some(a=>a.team===z.team)).length,bottom5Overlap:dr.slice(-5).filter(z=>br.slice(-5).some(a=>a.team===z.team)).length,leaveOneTeamOutPearson:[Math.min(...loo),Math.max(...loo)],outliers:dr.map(z=>({...z,benchmarkRank:br.find(b=>b.team===z.team)?.rank??null,benchmarkValue:rows[ids.indexOf(z.team)].benchmarks[b]})).filter(z=>finite(z.benchmarkRank)&&Math.abs(z.rank-z.benchmarkRank)>=10),ranks:br};});
  const summary=z=>({team:z.team,rank:z.rank,display:z.value,raw:x.teams[z.team].raw[u.raw],benchmarks:benchmarkSpecs[u.key].slice(0,2).map(([key,,boundary])=>({key,value:x.teams[z.team].benchmarks[key],boundary})),interpretation:'Same-snapshot diagnostic; benchmark ranks/outliers retained separately, no independent predictive certification'});
  tails[u.key]={top5:distributions[u.key].displayRanks.slice(0,5).map(summary),bottom5:distributions[u.key].displayRanks.slice(-5).map(summary)};
 }
 for(const k of ['qbEpaPerPlay','qbStabilizedEpa','qbAnyA','qbPassSuccessRate','qbStabilizedSuccess','qbCpoe','qbStabilizedCpoe','recvEpa','receiverResidualEpa','receiverStabilizedResidual','receiverCalibratedResidual','rbRushEpa','rbRecvEpa','rbRecvResidualEpa','rbComposite','rbCompositeOrthogonal','rbStabilizedRushEpa','rbStabilizedRecvResidualEpa','rbStabilizedComposite','rbCalibratedComposite','pbpPressureAllowedRate','oppPassEpa','oppCpoe','frontPressureRate','frontSackRate','selectedPassRushComposite','oppRushEpa','offensivePointsPerDrive','defensivePointsPerDrive','offenseCompositeRaw','defenseCompositeRaw'])intermediate[k]={...distribution(v('raw',k)),ranks:rankTeams('raw',k,!['pbpPressureAllowedRate','oppPassEpa','oppCpoe','defensivePointsPerDrive','oppRushEpa'].includes(k))};
 const dependencies=pairs.map(([a,b])=>{const ua=units.find(u=>u.key===a),ub=units.find(u=>u.key===b),vx=v('display',a),vy=v('display',b),control=def(a)&&def(b)?'defEpa':'offEpa',adjacent=def(a)&&def(b)?'defensivePointsPerDrive':'offensivePointsPerDrive';return {a,b,display:correlation(vx,vy),rawQualityProxy:correlation(v('raw',ua.raw).map(z=>finite(z)?z*(ua.higher?1:-1):null),v('raw',ub.raw).map(z=>finite(z)?z*(ub.higher?1:-1):null)),liveGrade:correlation(v('liveGrade',a),v('liveGrade',b)),partialCore:partial(vx,vy,[rows.map(r=>r.core)]),partialOutcome:{control,result:partial(vx,vy,[v('raw',control)])},partialCoreAndAdjacentOutcome:{controls:['core',adjacent],result:partial(vx,vy,[rows.map(r=>r.core),v('raw',adjacent)])}};});
 const discordance={};for(const [a,b] of [['receiverIndex','qbIndex'],['rbIndex','olIndex'],['coverageIndex','passRushIndex']]){
  const ra=rankTeams('display',a),rb=rankTeams('display',b);discordance[a+'__'+b]=ra.map(z=>({team:z.team,a,b,scoreA:z.value,rankA:z.rank,scoreB:rb.find(q=>q.team===z.team).value,rankB:rb.find(q=>q.team===z.team).rank,gap:z.rank-rb.find(q=>q.team===z.team).rank})).sort((x,y)=>Math.abs(y.gap)-Math.abs(x.gap)||x.team.localeCompare(y.team));
 }
 const receiver={beta:rows[0].raw.receiverOrthogonalBeta,unadjustedVsQbAttempt:correlation(v('raw','recvEpa'),v('raw','qbAttemptEpa')),residualVsQbAttempt:correlation(v('raw','receiverResidualEpa'),v('raw','qbAttemptEpa')),stabilizedVsQbAttempt:correlation(v('raw','receiverStabilizedResidual'),v('raw','qbAttemptEpa')),displayVsQbDisplay:correlation(v('display','receiverIndex'),v('display','qbIndex')),displayVsPassingEpa:correlation(v('display','receiverIndex'),v('raw','passEpa')),displayVsPassSuccess:correlation(v('display','receiverIndex'),v('raw','qbPassSuccessRate')),displayVsScoring:correlation(v('display','receiverIndex'),v('display','pointsScoredPerDriveIndex')),top5OverlapWithQb:distributions.receiverIndex.displayRanks.slice(0,5).filter(z=>distributions.qbIndex.displayRanks.slice(0,5).some(q=>q.team===z.team)).length,stabilizationIqrRatio:intermediate.receiverStabilizedResidual.iqr/intermediate.receiverResidualEpa.iqr,rawToHistoricalIqr:intermediate.receiverResidualEpa.iqr/(rows[0].historicalSpread.receiver.p75-rows[0].historicalSpread.receiver.p25)};
 const rb={rushVsDisplay:correlation(v('raw','rbRushEpa'),v('display','rbIndex')),receivingVsDisplay:correlation(v('raw','rbRecvResidualEpa'),v('display','rbIndex')),rushStabilizationIqrRatio:intermediate.rbStabilizedRushEpa.iqr/intermediate.rbRushEpa.iqr,recvStabilizationIqrRatio:intermediate.rbStabilizedRecvResidualEpa.iqr/intermediate.rbRecvResidualEpa.iqr,compositeStabilizationIqrRatio:intermediate.rbStabilizedComposite.iqr/intermediate.rbCompositeOrthogonal.iqr,rawToHistoricalIqr:intermediate.rbCompositeOrthogonal.iqr/(rows[0].historicalSpread.rb.p75-rows[0].historicalSpread.rb.p25)};
 const diagnoses={};for(const u of units){let shrink=null,historicalRatio=null;if(u.key==='receiverIndex'){shrink=receiver.stabilizationIqrRatio;historicalRatio=receiver.rawToHistoricalIqr;}if(u.key==='rbIndex'){shrink=rb.compositeStabilizationIqrRatio;historicalRatio=rb.rawToHistoricalIqr;}if(u.key==='qbIndex')shrink=intermediate.qbStabilizedEpa.iqr/intermediate.qbEpaPerPlay.iqr;
 const marked=finite(shrink)&&shrink<.5||finite(historicalRatio)&&historicalRatio<.5,compressed=distributions[u.key].display.middle80<30,normal=compressed&&finite(historicalRatio)&&historicalRatio>=.5;diagnoses[u.key]={classification:marked?(normal?'C. BOTH':'A. RAW-SIGNAL COMPRESSION'):normal?'B. DISPLAY-NORMALIZATION COMPRESSION':'D. NEITHER',stabilizationIqrRatio:shrink,currentVsHistoricalRawIqrRatio:historicalRatio,normalizationConcern:normal?'POSSIBLE':'NONE',boundary:'A-D conditional descriptive convention; missing ratios remain null. Multivariate QB/coverage and mixed-provider rush not reduced to a validated scalar skill scale.'};}
 const bank=[];
 function add(t,key,reason){
  const row=x.teams[t],u=units.find(z=>z.key===key),rank=distributions[key].displayRanks.find(z=>z.team===t).rank;
  const independentChecks=alignments[key].filter(a=>a.boundary.includes('non-formula'));
  const selected=(independentChecks.length?independentChecks:alignments[key]).slice(0,2);
  const checks=selected.map(a=>({key:a.benchmark,value:row.benchmarks[a.benchmark],rank:a.ranks.find(q=>q.team===t)?.rank??null,boundary:a.boundary}));
  const officialFacts=verifiedFacts.teamFacts.filter(f=>f.team===t&&f.units.includes(key));
  const contradictions=checks.filter(b=>rank<=8&&b.rank>=25||rank>=25&&b.rank<=8);
  const limited=key==='passRushIndex'||(!independentChecks.length&&!officialFacts.length);
  const classification=contradictions.length||limited?'QUESTIONABLE':'PASS';
  bank.push({team:t,unit:key,reason,raw:row.raw[u.raw],display:row.display[key],rank,checks,officialFacts,classification,
   interpretation:contradictions.length?'Observable outcome disagreement; inspect scope, receiving/context and prior. Not a verified causal defect.':limited?'Ingredient-only or provider-heterogeneous evidence is insufficient for independent unit-skill certification; direction is plausible, no clear pathology established.':'Broadly coherent on available non-formula outcome or official facts, or construct explains discordance; not predictive certification.'});
 }
 for(const key of ['qbIndex','receiverIndex','rbIndex','olIndex']){const d=distributions[key].displayRanks;add(d[0].team,key,'Highest displayed offense-unit tail');}
 add('KC','rbIndex','Owner-supplied case corrected to Walker currently on KC');
 for(const key of ['coverageIndex','passRushIndex','runDefenseIndex','pointsAllowedPerDriveIndex'])add(distributions[key].displayRanks[0].team,key,'Highest displayed defense-unit tail');
 for(const [pair,cases] of Object.entries(discordance))for(const c of [cases.find(c=>c.gap<0),cases.find(c=>c.gap>0)].filter(Boolean))add(c.team,c.a,'Discordance '+pair+': rank gap '+c.gap);
 const providers=Object.fromEntries([...new Set(rows.map(r=>r.metadata.passRushProvider))].sort().map(p=>{const teams=ids.filter(t=>x.teams[t].metadata.passRushProvider===p);return [p,{n:teams.length,teams,display:distribution(teams.map(t=>x.teams[t].display.passRushIndex)),raw:distribution(teams.map(t=>x.teams[t].raw.selectedPassRushComposite)),boundary:'Nonrandom provider assignment; charted true pressure and weekly hit+sack proxy are not interchangeable.'}];}));
 const summary=units.map(u=>{const d=distributions[u.key],adj=dependencies.filter(p=>p.a===u.key||p.b===u.key).sort((a,b)=>Math.abs(b.display.pearson??0)-Math.abs(a.display.pearson??0))[0];let classification='E. INSUFFICIENT EVIDENCE';if(['qbIndex','olIndex','coverageIndex','runDefenseIndex','pointsScoredPerDriveIndex','pointsAllowedPerDriveIndex','offenseIndex','offenseComposite','defenseIndex'].includes(u.key))classification='A. CURRENT FORMULA APPEARS SOUND; NO MATERIAL MD-07 DEFECT FOUND';if(['receiverIndex','rbIndex'].includes(u.key))classification='B. MEASUREMENT APPEARS DIRECTIONALLY SOUND BUT CONTEXT-INDEPENDENCE IS WEAK';return {key:u.key,label:u.label,displaySd:d.display.sd,displayMiddle80:d.display.middle80,rawSd:d.raw.sd,rawIqr:d.raw.iqr,clustering:d.clustering,strongestAdjacent:adj?{pair:[adj.a,adj.b],r:adj.display.pearson}:null,core:correlation(v('display',u.key),rows.map(r=>r.core)),teamOutcome:correlation(v('display',u.key),v('raw',def(u.key)?'defEpa':'offEpa')),benchmarkAlignment:alignments[u.key].map(a=>({key:a.benchmark,r:a.pearson,boundary:a.boundary})),bankResult:bank.filter(b=>b.unit===u.key).map(b=>({team:b.team,result:b.classification})),predictiveEvidence:'UNAVAILABLE',md07:classification,normalization:diagnoses[u.key].normalizationConcern,rawDiagnosis:diagnoses[u.key].classification};});
 return {conventions:CONVENTIONS,distributions,intermediate,dependencies,receiver,rb,discordance,alignments,tails,diagnoses,bank,providers,summary};
}
export function artifacts(a){return {'unit_distributions.json':{conventions:a.conventions,units:a.distributions,intermediate:a.intermediate},'unit_dependencies.json':{pairs:a.dependencies,receiver:a.receiver,rb:a.rb,discordance:a.discordance,providers:a.providers},'benchmark_alignment.json':a.alignments,'pathology_bank.json':{criteria:a.conventions.pathology,cases:a.bank,extremes:a.tails},'unit_summary.json':{diagnosis:a.diagnoses,matrix:a.summary},'unit_audit.csv':['unit,display_sd,display_middle80,raw_sd,raw_iqr,clustering,md07,normalization',...a.summary.map(r=>[r.key,r.displaySd,r.displayMiddle80,r.rawSd,r.rawIqr,r.clustering,r.md07,r.normalization].join(','))].join('\n')+'\n'};}
export function serialize(a){const verify=o=>{if(typeof o==='number'&&!Number.isFinite(o))throw new Error('non-finite statistic cannot be serialized as null');if(o&&typeof o==='object')for(const v of Object.values(o))verify(v);};verify(a);return Object.fromEntries(Object.entries(artifacts(a)).map(([p,x])=>[p,typeof x==='string'?x:JSON.stringify(x,null,2)+'\n']));}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const x=JSON.parse(fs.readFileSync(DIR+'/inputs/current_snapshot.json','utf8'));const results=serialize(analyze(x));for(const [p,t] of Object.entries(results))fs.writeFileSync(DIR+'/results/'+p,t);console.log('MD07 current analysis: 12 units, 16 required pairs, 6 deterministic artifacts');
}
