// Descriptive n=32 statistics, with explicit finite/missing handling and midrank ties.
import {finite} from './architecture.mjs';
export const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
export function quantile(a,p){a=a.filter(finite).sort((x,y)=>x-y);if(!a.length)return null;const x=(a.length-1)*p,l=Math.floor(x);return a[l]+(a[Math.ceil(x)]-a[l])*(x-l);}
export function rank(a){return a.map(x=>!finite(x)?null:1+a.filter(v=>finite(v)&&v<x).length+(a.filter(v=>v===x).length-1)/2);}
export function pearson(x,y){const a=x.map((v,i)=>[v,y[i]]).filter(r=>r.every(finite));if(a.length<3)return {n:a.length,r:null};const mx=mean(a.map(r=>r[0])),my=mean(a.map(r=>r[1]));let xx=0,yy=0,xy=0;for(const [x,y] of a){xx+=(x-mx)**2;yy+=(y-my)**2;xy+=(x-mx)*(y-my);}return {n:a.length,r:xx>0&&yy>0?xy/Math.sqrt(xx*yy):null};}
export function correlation(x,y){const a=x.map((v,i)=>[v,y[i]]).filter(r=>r.every(finite)),xx=a.map(r=>r[0]),yy=a.map(r=>r[1]);return {n:a.length,pearson:pearson(xx,yy).r,spearman:pearson(rank(xx),rank(yy)).r};}
// Residualize both variables on a centered intercept + <=2 controls using Gram-Schmidt.
// No outcome fitting/prediction or tuned model. Reject singular/near-singular controls.
export function partial(x,y,controls){const a=x.map((v,i)=>[v,y[i],...controls.map(c=>c[i])]).filter(r=>r.every(finite));if(a.length<12||controls.length>2)return {n:a.length,r:null,reason:'insufficient sample/too many controls'};
 const center=v=>{const m=mean(v);return v.map(x=>x-m);},dot=(x,y)=>x.reduce((s,v,i)=>s+v*y[i],0);let xx=center(a.map(r=>r[0])),yy=center(a.map(r=>r[1]));const qs=[];
 for(let k=0;k<controls.length;k++){let c=center(a.map(r=>r[k+2]));const original=dot(c,c);for(const q of qs){const b=dot(c,q);c=c.map((v,i)=>v-b*q[i]);}const s=dot(c,c);if(s<1e-10||s/original<1e-8)return {n:a.length,r:null,reason:'singular/near-collinear controls'};qs.push(c.map(v=>v/Math.sqrt(s)));}
 for(const q of qs){const bx=dot(xx,q),by=dot(yy,q);xx=xx.map((v,i)=>v-bx*q[i]);yy=yy.map((v,i)=>v-by*q[i]);}return {n:a.length,r:pearson(xx,yy).r,controls:controls.length,reason:'descriptive partial Pearson; controls are not causal confounder identification'};}
export function distribution(values){const a=values.filter(finite).sort((a,b)=>a-b);if(!a.length)return {n:0,missing:values.length};const m=mean(a),median=quantile(a,.5),p10=quantile(a,.1),p25=quantile(a,.25),p75=quantile(a,.75),p90=quantile(a,.9);return {n:a.length,missing:values.length-a.length,min:a[0],max:a.at(-1),mean:m,median,sd:Math.sqrt(mean(a.map(x=>(x-m)**2))),p10,p25,p75,p90,iqr:p75-p25,range:a.at(-1)-a[0],middle80:p90-p10,tailCount:Math.min(5,a.length),top5Spread:a.length>=5?a.at(-1)-a.at(-5):null,bottom5Spread:a.length>=5?a[4]-a[0]:null,top5Mean:a.length>=5?mean(a.slice(-5)):null,bottom5Mean:a.length>=5?mean(a.slice(0,5)):null,top5MinusMedian:a.length>=5?mean(a.slice(-5))-median:null,medianMinusBottom5:a.length>=5?median-mean(a.slice(0,5)):null,withinMedian:Object.fromEntries([2,5,10].map(w=>[w,a.filter(x=>Math.abs(x-median)<=w).length])),adjacentSpacing:a.slice(1).map((v,i)=>v-a[i]),distinct:new Set(a).size};}
export const CONVENTIONS={quantiles:'linear (n-1)*p; population SD; midrank ties',displayClustering:'C1 middle80 <30; C2 good-band ranks6-15 span <10; C3 >=8/32 teams in an inclusive rolling6-point band. Separate descriptive facets, not validated football thresholds. Sensitivity at band spans8/10/12 and packing counts8/10 is retained.',rawCompression:'Stabilized/current IQR <.50 denotes marked component attenuation, not whole-grade failure.',normalizationCompression:'Like-for-like calibrated values versus the actual consumed mapping reference; component and provider limitations explicit. No unstabilized/raw ratio used as a normalization clearance.',pathology:'NO OPPOSITE-QUARTILE CONTRADICTION means only that the available checks do not occupy opposite quartiles. QUESTIONABLE includes two >=10-rank same-feed discordances or important scope/evidence limits. CLEAR PATHOLOGY cannot be certified without sufficiently independent external evidence.',discordance:'Absolute rank gap >=10; no tuning targets.',alignment:'A independent external; B same-feed different transformation; C direct ingredient/near-tautological; D official factual corroboration outside the 33 statistical comparisons.',historical:'Exact causal predictive validation UNAVAILABLE'};
export function packing(values){
 const a=values.filter(finite).sort((a,b)=>b-a),d=distribution(a),span=(lo,hi)=>a.length>=hi?a[lo-1]-a[hi-1]:null;
 const rolling=width=>{let best={count:0,lower:null,upper:null};for(const lo of a){const count=a.filter(v=>v>=lo&&v<=lo+width).length;if(count>best.count)best={count,lower:lo,upper:lo+width};}return best;};
 return {p75MinusMedian:d.p75-d.median,p90MinusMedian:d.p90-d.median,medianMinusP10:d.median-d.p10,upperHalfSpread:span(1,Math.ceil(a.length/2)),rank6To15Spread:span(6,15),rank4To15Spread:span(4,15),atLeast70:a.filter(v=>v>=70).length,in40To60:a.filter(v=>v>=40&&v<=60).length,rolling5:rolling(5),rolling6:rolling(6),within10OfMedian:d.withinMedian[10],conventions:{middle80:d.middle80<30,goodBand:span(6,15)<10,centralPacking:rolling(6).count>=8},sensitivity:{goodBandThresholds:Object.fromEntries([8,10,12].map(t=>[t,span(6,15)<t])),packingThresholds:Object.fromEntries([8,10].map(t=>[t,rolling(6).count>=t]))}};
}
export function mappedComparison(values,ref,higher=true){
 const d=distribution(values.map(v=>v*(higher?1:-1))),q=higher?ref:{...ref,p10:-ref.p90,p25:-ref.p75,p75:-ref.p25,p90:-ref.p10};
 return {current:d,reference:q,iqrRatio:d.iqr/(q.p75-q.p25),middle80Ratio:d.middle80/(q.p90-q.p10),upperBandRatio:(d.p90-d.p75)/(q.p90-q.p75),aboveReferenceP75:values.filter(v=>v*(higher?1:-1)>q.p75).length,belowReferenceP25:values.filter(v=>v*(higher?1:-1)<q.p25).length};
}
export function cluster(d){return d.middle80<15?'VERY COMPRESSED':d.middle80<30?'COMPRESSED':d.middle80<=60?'REASONABLY DISCRIMINATIVE':'VERY WIDE';}
