// Descriptive n=32 statistics, with explicit finite/missing handling and midrank ties.
import {finite} from './architecture.mjs';
export const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
export function quantile(a,p){a=a.filter(finite).sort((x,y)=>x-y);if(!a.length)return null;const x=(a.length-1)*p,l=Math.floor(x);return a[l]+(a[Math.ceil(x)]-a[l])*(x-l);}
export function rank(a){return a.map(x=>!finite(x)?null:1+a.filter(v=>finite(v)&&v<x).length+(a.filter(v=>v===x).length-1)/2);}
export function pearson(x,y){const a=x.map((v,i)=>[v,y[i]]).filter(r=>r.every(finite));if(a.length<3)return {n:a.length,r:null};const mx=mean(a.map(r=>r[0])),my=mean(a.map(r=>r[1]));let xx=0,yy=0,xy=0;for(const [x,y] of a){xx+=(x-mx)**2;yy+=(y-my)**2;xy+=(x-mx)*(y-my);}return {n:a.length,r:xx>0&&yy>0?xy/Math.sqrt(xx*yy):null};}
export function correlation(x,y){const a=x.map((v,i)=>[v,y[i]]).filter(r=>r.every(finite)),xx=a.map(r=>r[0]),yy=a.map(r=>r[1]);return {n:a.length,pearson:pearson(xx,yy).r,spearman:pearson(rank(xx),rank(yy)).r};}
// Residualize both variables on a centered intercept + <=2 controls using Gram-Schmidt.
// No outcome fitting/prediction or tuned model. Reject singular/near-singular controls.
export function partial(x,y,controls){const a=x.map((v,i)=>[v,y[i],...controls.map(c=>c[i])]).filter(r=>r.every(finite));if(a.length<12||controls.length>2)return {n:a.length,r:null,reason:'insufficient sample/too many controls'};
 const center=v=>{const m=mean(v);return v.map(x=>x-m);},dot=(x,y)=>x.reduce((s,v,i)=>s+v*y[i],0);let xx=center(a.map(r=>r[0])),yy=center(a.map(r=>r[1]));const qs=[];
 for(let k=0;k<controls.length;k++){let c=center(a.map(r=>r[k+2]));const original=dot(c,c);for(const q of qs){const b=dot(c,q);c=c.map((v,i)=>v-b*q[i]);}const s=dot(c,c);if(s<1e-10||s/original<1e-8)return {n:a.length,r:null,reason:'singular/near-collinear controls'};qs.push(c.map(v=>v/Math.sqrt(s)));}
 for(const q of qs){const bx=dot(xx,q),by=dot(yy,q);xx=xx.map((v,i)=>v-bx*q[i]);yy=yy.map((v,i)=>v-by*q[i]);}return {n:a.length,r:pearson(xx,yy).r,controls:controls.length,reason:'descriptive partial Pearson; controls are not causal confounder identification'};}
export function distribution(values){const a=values.filter(finite).sort((a,b)=>a-b);if(!a.length)return {n:0,missing:values.length};const m=mean(a),median=quantile(a,.5),p10=quantile(a,.1),p25=quantile(a,.25),p75=quantile(a,.75),p90=quantile(a,.9);return {n:a.length,missing:values.length-a.length,min:a[0],max:a.at(-1),mean:m,median,sd:Math.sqrt(mean(a.map(x=>(x-m)**2))),p10,p25,p75,p90,iqr:p75-p25,range:a.at(-1)-a[0],middle80:p90-p10,tailCount:Math.min(5,a.length),top5Spread:a.length>=5?a.at(-1)-a.at(-5):null,bottom5Spread:a.length>=5?a[4]-a[0]:null,top5Mean:a.length>=5?mean(a.slice(-5)):null,bottom5Mean:a.length>=5?mean(a.slice(0,5)):null,top5MinusMedian:a.length>=5?mean(a.slice(-5))-median:null,medianMinusBottom5:a.length>=5?median-mean(a.slice(0,5)):null,withinMedian:Object.fromEntries([2,5,10].map(w=>[w,a.filter(x=>Math.abs(x-median)<=w).length])),adjacentSpacing:a.slice(1).map((v,i)=>v-a[i]),distinct:new Set(a).size};}
export const CONVENTIONS={quantiles:'linear interpolation at (n-1)*p; population SD; midrank ties',displayClustering:'middle-80% span <15 VERY COMPRESSED; 15..<30 COMPRESSED; 30..60 REASONABLY DISCRIMINATIVE; >60 VERY WIDE. Descriptive display convention, not validated football thresholds.',rawCompression:'IQR after reliability stabilization / IQR before <0.50 means marked stabilization compression. With available like-for-like historical benchmark, current physical IQR / historical IQR <0.50 means raw signal compression relative to that benchmark. QB/coverage scalar proxies do not cover full multivariate formula. Cross-unit physical units are not directly comparable.',normalizationCompression:'Middle-80 displayed span <30 with raw current/historical IQR >=0.50 suggests display compression (with marked stabilization compression, classify BOTH). A-D classification is conditional on available scalar evidence, not a scale redesign.',pathology:'PASS: direction of score broadly aligns with non-formula observable facts, or discordance is explained by scope/prior/components. QUESTIONABLE: opposite score/benchmark quartiles or important construct ambiguity. CLEAR PATHOLOGY requires two genuinely independent facts on the same intended construct and unexplained opposite tails; this package cannot certify that with same-feed benchmarks alone.',discordance:'Absolute displayed rank gap >=10 defines notable discordance; upper/lower quartile pair defines strong opposite-tail discordance. Cases selected systematically, not tuning targets.',alignment:'Ingredient alignment separated from non-formula outcomes; same-feed non-formula benchmarks are not independent providers or ground truth.',historical:'UNAVAILABLE for exact causal current-production unit predictive validation; no proxy replay represented as canonical validation'};
export function cluster(d){return d.middle80<15?'VERY COMPRESSED':d.middle80<30?'COMPRESSED':d.middle80<=60?'REASONABLY DISCRIMINATIVE':'VERY WIDE';}
